/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually
  documentationSidebar: [
    {
      type: 'html',
      value: 'Getting Started',
      className: 'sidebar-section-header',
    },
    {
      type: 'category',
      label: 'Introduction',
      link: {
        type: 'doc',
        id: 'getting-started/intro',
      },
      collapsible: true,
      collapsed: false,
      items: [
        {
          type: 'doc',
          id: 'getting-started/introduction-to-solana',
          label: 'Introduction to Solana'
        },
      ]
    },
  ],
  /* other sidebars
  ...require("./sidebars/kotlinSidebar.js"),
  ...require("./sidebars/reactNativeSidebar.js"),
  ...require("./sidebars/flutterSidebar.js"),
  ...require("./sidebars/unitySidebar.js"),
  ...require("./sidebars/unrealSidebar.js"),
  ...require("./sidebars/dappStoreSidebar.js"),
  ...require("./sidebars/referenceSidebar.js"),
  ...require("./sidebars/sagaSidebar.js"),
  */
};

module.exports = sidebars;
