/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],
  //mainnetSidebar: [{type: 'autogenerated', dirName: 'mainnet-networks'}],


  mainnetSidebar: [
    'intro',
    {
      type: 'html',
      value: '<img style="height:32px;" src="/img/osmosis.svg" alt="Osmosis" />', // The HTML to be rendered
      items: ['mainnet-networks/osmosis'],
      defaultStyle: true, // Use the default menu item styling
    },
    {
      type: 'category',
      label: 'Tutorial',
      items: ['tutorial-basics/create-a-document'],
    },
  ],

};

export default sidebars;
