/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],
  //mainnetSidebar: [{type: 'autogenerated', dirName: 'mainnet-networks'}],
  testnetSidebar: [{type: 'autogenerated', dirName: 'testnet-networks'}],


  mainnetSidebar: [
    {
      type: 'html',
      value: 'Cosmos',
      className: 'sidebar-section-header',
    },
    {
      type: 'category',
      label: 'Osmosis',
      link: {
        type: 'doc',
        id: 'mainnet-networks/osmosis',
        image: "/img/osmosis.svg",
      },
      collapsible: true,
      items: [{type: 'autogenerated', dirName: 'mainnet-networks/osmosis'}],
    },
  ],

};

export default sidebars;
