# App
CHAIN_NAME="Dymension"
CHAIN_SYSTEM_NAME="dymension"
CHAIN_ICON="dymension-icon.svg"
CHAIN_BACKGROUND_COLOR="#dbb447"

# NODERS
STAKE_URL="https://wallet.keplr.app/?modal=staking&chain=dymension_1100-1&validator_address=dymvaloper1ta56hcqaxj55wu8emarnw090gk5uq4366uz572&step_id=3&action_id=stake"
RESTAKE_URL="https://restake.app/dymension/dymvaloper1ta56hcqaxj55wu8emarnw090gk5uq4366uz572"
VALIDATOR_URL="https://dymension.explorers.guru/validator/dymvaloper1ta56hcqaxj55wu8emarnw090gk5uq4366uz572"
EXPLORER_URL=""
EXPLORER_IMAGE="dymension-exp.png"
APP_URL="https://dymensionhub.org"
APP_IMAGE="dymension-app.png"
FAUCET_URL=""

# Blockchain
CHAIN_ID="auto"
CHAIN_DENOM_PRETTY="DYM"
CHAIN_DENOM="adym"
CHAIN_FEES="300000000000"

# Binary
VERSION="auto"
DAEMON_NAME="dymd"
DAEMON_SERVICE="dymd.service"
DAEMON_HOME="~/.dymension"

# Endpoints
ENDPOINT_RPC="https://dymension-rpc.noders.services"
ENDPOINT_API="https://dymension-api.noders.services"
ENDPOINT_JRPC="https://dymension-jsonrpc.noders.services"
ENDPOINT_GRPC="dymension-grpc.noders.services:443"
ENDPOINT_PEER="auto"
ENDPOINT_COSMOSLIST="https://cosmoslist.co/mainnet/dymension"
ENDPOINT_SEED="5707bb72616deaf595eb79def6e371e50085f403@dymension-seed.noders.services:20533"

# Social
SOCIAL_WEBSITE="https://dymension.xyz/"
SOCIAL_GITHUB="https://github.com/dymensionxyz"
SOCIAL_DISCORD="https://discord.gg/dymension"
SOCIAL_X="https://twitter.com/dymension"
SOCIAL_TELEGRAM="https://t.me/dymensionXYZ"

# Other
SNAPSHOT_URL="https://snapshots.noders.services/dymension"
GITHUB_FOLDER_NAME="auto"

# Updates
UPDATE_MAIN=true
UPDATE_CATEGORY=true
UPDATE_INSTALL=true
UPDATE_UPGRADE=true
UPDATE_SNAPSHOT=true
UPDATE_STATESYNC=true
UPDATE_LIVE_PEERS=true
UPDATE_CLI_CHEATSHEET=true
UPDATE_ENDPOINTS=true
UPDATE_MONITORING=true
UPDATE_PUBLIC_ENDPOINTS=true

# Feature toggles

# Node installation
SHOW_INSTALLATION_GUIDE=true
SHOW_UPGRADE_GUIDE=true
SHOW_GENESIS=true
SHOW_CLI=true

# Endpoints and Sync
SHOW_ENDPOINTS=true
SHOW_STATE_SYNC=true
SHOW_SNAPSHOT=true
SHOW_LIVE_PEERS=true
SHOW_SEED=true
SHOW_ADDRESS_BOOK=true

# Tools
SHOW_EXPLORERS_LIST=true
SHOW_PUBLIC_ENDPOINTS=true
SHOW_USEFUL_TOOLS=true
SHOW_UPGRADE_WATCHER=false
SHOW_MONITORING=true

# Monitoring Configuration
MONITORING_PROMETHEUS_PORT="9090"
MONITORING_GRAFANA_PORT="3000"
MONITORING_NODE_METRICS_PORT="26661"
MONITORING_GRAFANA_PASSWORD="admin123"
MONITORING_MAX_MISSED_BLOCKS="5"
