# App
CHAIN_NAME="Osmosis"
CHAIN_SYSTEM_NAME="osmosis"
CHAIN_ICON="osmosis-icon.svg"
CHAIN_BACKGROUND_COLOR="#AB00C2"

# NODERS
STAKE_URL=""
RESTAKE_URL=""
VALIDATOR_URL=""
EXPLORER_URL=""
EXPLORER_IMAGE=""
APP_URL=""
APP_IMAGE=""
FAUCET_URL=""

# Blockchain
CHAIN_ID="auto"
CHAIN_DENOM="uosmo"
CHAIN_FEES="20000"

# Binary
VERSION="auto"
DAEMON_NAME="osmosisd"
DAEMON_SERVICE="osmosisd.service"
DAEMON_HOME="~/.osmosisd"

# Endpoints
ENDPOINT_RPC="https://osmosis-rpc.noders.services"
ENDPOINT_API="https://osmosis-api.noders.services"
ENDPOINT_JRPC=""
ENDPOINT_GRPC="osmosis-grpc.noders.services:443"
ENDPOINT_PEER="auto"
ENDPOINT_COSMOSLIST="https://cosmoslist.co/mainnet/osmosis"

# Social
SOCIAL_WEBSITE="https://app.osmosis.zone/"
SOCIAL_GITHUB="https://github.com/osmosis-labs/osmosis"
SOCIAL_DISCORD="https://discord.com/invite/osmosis"
SOCIAL_X="https://twitter.com/osmosiszone"
SOCIAL_TELEGRAM="https://t.me/osmosiszone"

# Other
SNAPSHOT_URL="https://snapshots.noders.services/osmosis"
GITHUB_FOLDER_NAME="auto"

# Updates
UPDATE_MAIN=true
UPDATE_CATEGORY=true
UPDATE_INSTALL=true
UPDATE_UPGRADE=true
UPDATE_SNAPSHOT=true
UPDATE_STATESYNC=true
UPDATE_LIVE_PEERS=true
UPDATE_CLI_CHEATSHEET=true
UPDATE_ENDPOINTS=true
UPDATE_MONITORING=true

# Feature toggles

# Node installation
SHOW_INSTALLATION_GUIDE=true
SHOW_UPGRADE_GUIDE=true
SHOW_GENESIS=true
SHOW_CLI=true

# Endpoints and Sync
SHOW_ENDPOINTS=true
SHOW_STATE_SYNC=true
SHOW_SNAPSHOT=true
SHOW_LIVE_PEERS=true
SHOW_SEED=true
SHOW_ADDRESS_BOOK=true

# Tools
SHOW_EXPLORERS_LIST=true
SHOW_PUBLIC_ENDPOINTS=false
SHOW_USEFUL_TOOLS=true
SHOW_UPGRADE_WATCHER=false
SHOW_MONITORING=true

# Monitoring Configuration
MONITORING_PROMETHEUS_PORT="9090"
MONITORING_GRAFANA_PORT="3000"
MONITORING_NODE_METRICS_PORT="26661"
MONITORING_GRAFANA_PASSWORD="admin123"
MONITORING_MAX_MISSED_BLOCKS="5"

