# App
CHAIN_NAME="Mantra"
CHAIN_SYSTEM_NAME="mantra"
CHAIN_ICON="mantra-icon.svg"
CHAIN_BACKGROUND_COLOR="#FE99D0"

# NODERS
STAKE_URL=""
RESTAKE_URL=""
VALIDATOR_URL="https://testnet.itrocket.net/mantra/staking/mantravaloper1aysxyetv0y7sfe0v70akyjn3kkjc6qyt5dlewa"
EXPLORER_URL=""
APP_URL=""
APP_IMAGE=""
FAUCET_URL=""

# Blockchain
CHAIN_ID="auto"
CHAIN_DENOM="uom"
CHAIN_FEES="20000"

# Binary
VERSION="auto"
DAEMON_NAME="mantrachaind"
DAEMON_SERVICE="mantrachaind.service"
DAEMON_HOME="~/.mantrachaind"

# Endpoints
ENDPOINT_RPC="https://mantra-t-rpc.noders.services"
ENDPOINT_API="https://mantra-t-api.noders.services"
ENDPOINT_JRPC=""
ENDPOINT_GRPC="mantra-t-grpc.noders.services:443"
ENDPOINT_PEER="auto"
ENDPOINT_SEED="0767221d878318764af082adac089eee9f1cdb4e@mantra-t-seed.noders.services:25133"
ENDPOINT_COSMOSLIST="https://cosmoslist.co/testnet/mantra"

# Social
SOCIAL_WEBSITE="https://www.mantrachain.io/"
SOCIAL_GITHUB="https://github.com/MANTRA-Finance/public"
SOCIAL_DISCORD="https://discord.gg/gfks4TwAJV"
SOCIAL_X="https://twitter.com/MANTRA_Chain"
SOCIAL_TELEGRAM="https://t.me/MANTRA_Chain"

# Other
SNAPSHOT_URL="https://snapshots-t.noders.services/mantra"
GITHUB_FOLDER_NAME="auto"

# Updates
UPDATE_MAIN=true
UPDATE_CATEGORY=true
UPDATE_INSTALL=true
UPDATE_UPGRADE=true
UPDATE_SNAPSHOT=true
UPDATE_STATESYNC=true
UPDATE_LIVE_PEERS=true
UPDATE_CLI_CHEATSHEET=true
UPDATE_ENDPOINTS=true
UPDATE_MONITORING=true
UPDATE_PUBLIC_ENDPOINTS=true

# Feature toggles

# Node installation
SHOW_INSTALLATION_GUIDE=true
SHOW_UPGRADE_GUIDE=true
SHOW_GENESIS=true
SHOW_CLI=true

# Endpoints and Sync
SHOW_ENDPOINTS=true
SHOW_STATE_SYNC=true
SHOW_SNAPSHOT=true
SHOW_LIVE_PEERS=true
SHOW_SEED=true
SHOW_ADDRESS_BOOK=true

# Tools
SHOW_EXPLORERS_LIST=true
SHOW_PUBLIC_ENDPOINTS=true
SHOW_USEFUL_TOOLS=true
SHOW_UPGRADE_WATCHER=false
SHOW_MONITORING=true

# Monitoring Configuration
MONITORING_PROMETHEUS_PORT="9090"
MONITORING_GRAFANA_PORT="3000"
MONITORING_NODE_METRICS_PORT="26661"
MONITORING_GRAFANA_PASSWORD="admin123"
MONITORING_MAX_MISSED_BLOCKS="5"
MONITORING_DASHBOARD_ID="15991"
