# App
CHAIN_NAME="ZeroGravity"
CHAIN_SYSTEM_NAME="og"
CHAIN_ICON="og-icon.svg"
CHAIN_BACKGROUND_COLOR="#dc6bbd"

# NODERS
STAKE_URL=""
RESTAKE_URL=""
VALIDATOR_URL="https://testnet.0g.explorers.guru/validator/0gvaloper1w24g8xczpxuy5y87lwv0dyq9n27mlyul3xf2zk"
EXPLORER_URL="https://0ghub.org/explorer"
EXPLORER_IMAGE="og-exp.png"
APP_URL="https://0ghub.org/"
APP_IMAGE="og-app.png"
FAUCET_URL=""

# Blockchain
CHAIN_ID="auto"
CHAIN_DENOM_PRETTY="OG"
CHAIN_DENOM="neuron"
CHAIN_FEES="200000000"

# Binary
VERSION="auto"
DAEMON_NAME="0gchaind"
DAEMON_SERVICE="og.service"
DAEMON_HOME="~/.0gchain"

# Endpoints
ENDPOINT_RPC="https://og-t-rpc.noders.services"
ENDPOINT_API=""
ENDPOINT_JRPC="https://og-t-json.noders.services"
ENDPOINT_GRPC="og-t-grpc.noders.services:443"
ENDPOINT_PEER="auto"
ENDPOINT_SEED="dbf6036f6a2bdc952d58678756dc835dff0abbc7@og-t-seed.noders.services:23833"
ENDPOINT_COSMOSLIST="https://cosmoslist.co/testnet/og"

# Social
SOCIAL_WEBSITE="https://0g.ai/"
SOCIAL_GITHUB="https://github.com/0glabs/0g-chain"
SOCIAL_DISCORD="http://discord.gg/0glabs"
SOCIAL_X="https://twitter.com/0G_labs"
SOCIAL_TELEGRAM="https://t.me/web3_0glabs"

# Other
SNAPSHOT_URL="https://snapshots-t.noders.services/og"
GITHUB_FOLDER_NAME="auto"

# Updates
UPDATE_MAIN=true
UPDATE_CATEGORY=true
UPDATE_INSTALL=true
UPDATE_UPGRADE=true
UPDATE_SNAPSHOT=true
UPDATE_STATESYNC=true
UPDATE_LIVE_PEERS=true
UPDATE_CLI_CHEATSHEET=true
UPDATE_ENDPOINTS=true
UPDATE_MONITORING=true
UPDATE_PUBLIC_ENDPOINTS=true

# Feature toggles

# Node installation
SHOW_INSTALLATION_GUIDE=true
SHOW_UPGRADE_GUIDE=true
SHOW_GENESIS=true
SHOW_CLI=true

# Endpoints and Sync
SHOW_ENDPOINTS=true
SHOW_STATE_SYNC=true
SHOW_SNAPSHOT=true
SHOW_LIVE_PEERS=true
SHOW_SEED=true
SHOW_ADDRESS_BOOK=true

# Tools
SHOW_EXPLORERS_LIST=true
SHOW_PUBLIC_ENDPOINTS=true
SHOW_USEFUL_TOOLS=true
SHOW_UPGRADE_WATCHER=false
SHOW_MONITORING=true

# Monitoring Configuration
MONITORING_PROMETHEUS_PORT="9090"
MONITORING_GRAFANA_PORT="3000"
MONITORING_NODE_METRICS_PORT="26661"
MONITORING_GRAFANA_PASSWORD="admin123"
MONITORING_MAX_MISSED_BLOCKS="5"
MONITORING_DASHBOARD_ID="15991"
