# App
CHAIN_NAME="Althea"
CHAIN_SYSTEM_NAME="althea"
CHAIN_ICON="althea-icon.svg"
CHAIN_BACKGROUND_COLOR=""

# Blockchain
CHAIN_ID="auto"
CHAIN_DENOM="aalthea"
CHAIN_FEES="300000000000"

# Binary
VERSION="auto"
DAEMON_NAME="althea"
DAEMON_SERVICE="althea.service"
DAEMON_HOME="~/.althea"

# Endpoints
ENDPOINT_RPC="https://althea-rpc.noders.services"
ENDPOINT_API="https://althea-api.noders.services"
ENDPOINT_JRPC=""
ENDPOINT_GRPC="https://althea-grpc.noders.services:443"
ENDPOINT_PEER="auto"
ENDPOINT_COSMOSLIST="https://cosmoslist.co/mainnet/althea"

# Social
SOCIAL_WEBSITE="https://www.althea.net/"
SOCIAL_GITHUB="https://github.com/althea-net/althea-chain"
SOCIAL_DISCORD="https://discord.gg/hHx7HxcycF"
SOCIAL_X="https://twitter.com/AltheaNetwork"
SOCIAL_TELEGRAM=""

# Other
SNAPSHOT_URL="https://snapshots.noders.services/althea"
GITHUB_FOLDER_NAME="auto"
VALIDATOR_URL=""

# Updates
UPDATE_MAIN=true
UPDATE_CATEGORY=true
UPDATE_INSTALL=true
UPDATE_UPGRADE=true
UPDATE_SNAPSHOT=true
UPDATE_STATESYNC=true
UPDATE_LIVE_PEERS=true
UPDATE_CLI_CHEATSHEET=true

# Feature toggles
# Node installation
SHOW_INSTALLATION_GUIDE=true
SHOW_UPGRADE_GUIDE=true
SHOW_GENESIS=true
SHOW_CLI=true
# Endpoints and Sync
SHOW_ENDPOINTS=true
SHOW_STATE_SYNC=true
SHOW_SNAPSHOT=true
SHOW_LIVE_PEERS=true
SHOW_SEED=true
SHOW_ADDRESS_BOOK=true
# Tools
SHOW_EXPLORERS_LIST=false
SHOW_PUBLIC_ENDPOINTS=false
SHOW_USEFUL_TOOLS=false
SHOW_UPGRADE_WATCHER=false
