# Blockchain
CHAIN_NAME="Andromeda"
CHAIN_SYSTEM_NAME="andromeda"
CHAIN_ID="auto"
CHAIN_DESCRIPTION="""Andromeda Protocol introduces a groundbreaking innovation in the realm of decentralized technology with its Andromeda Operating System (aOS).

Positioned as the first decentralized, on-chain operating system, aOS serves as the foundation for a comprehensive suite of products, tools, and utilities across multiple blockchains. Here's an overview of what makes Andromeda stand out:

Multi-Chain and On-Chain Suite: Andromeda is designed to operate seamlessly across various blockchains, providing an all-encompassing environment for the development and deployment of Web3 applications.

Decentralized Operating System (aOS): At the heart of Andromeda is the Andromeda Operating System (aOS), which is described as the starting point for Web3. This innovative platform facilitates the creation, management, and execution of decentralized applications (dApps) on a scale never seen before.

Inter-Blockchain Communication (IBC): Utilizing IBC, Andromeda enhances connectivity across the blockchain ecosystem. This feature allows for the efficient transport of lightweight configuration data between chains, facilitating seamless interaction and integration between different projects within the Cosmos network and beyond.

Accessibility for Creators and Developers: Andromeda lowers the entry barrier for creators and developers of all skill levels. With its suite of intuitive tools and interfaces, individuals can easily navigate and leverage the vast design space offered by the platform.

Rapid Development with ADOs: The introduction of Andromeda Digital Objects (ADOs) revolutionizes the development process, reducing timeframes from months to minutes. ADOs are unique tools that enable quick creation and composition of Web3 apps, significantly accelerating the development cycle.

Integration and Partnerships: Andromeda boasts integrations with several key blockchain platforms such as Juno, Archway, Sei, Oraichain, Injective, Terra, Stargaze, Secret, Axelar, and more, demonstrating its commitment to fostering a connected and cooperative blockchain ecosystem.

Community and Engagement: The project places a strong emphasis on community interaction and engagement, inviting users to connect across various channels to explore how Andromeda can facilitate their Web3 endeavors.

Andromeda Protocol is on a mission to make Web3 more accessible, efficient, and scalable by providing an innovative platform that bridges the gap between various blockchain networks and simplifies the development process for creators and developers worldwide."""

CHAIN_DENOM="uandr"
CHAIN_FEES="3000"

# Binary
DAEMON_NAME="andromedad"
DAEMON_VERSION="andromeda-1-v0.1.0"
DAEMON_SERVICE="andromedad.service"
DAEMON_HOME="~/.andromeda"

# Endpoints
ENDPOINT_RPC=""
ENDPOINT_API=""
ENDPOINT_GRPCWEB=""
ENDPOINT_GRPC=""
ENDPOINT_PEER="auto"

# Social
SOCIAL_WEBSITE="https://www.andromedaprotocol.io/"
SOCIAL_GITHUB="https://github.com/andromedaprotocol"
SOCIAL_DISCORD="https://discord.gg/GBd6buKYyZ"
SOCIAL_X="https://twitter.com/andromedaprot"
SOCIAL_TELEGRAM="https://t.me/andromedaprotocol"

# Other
DOWNLOAD_URL="h"
GITHUB_FOLDER_NAME="auto"

# Updates
UPDATE_MAIN=true
UPDATE_CATEGORY=true
UPDATE_UPGRADE=true
UPDATE_SNAPSHOT=true
UPDATE_STATESYNC=true
UPDATE_LIVE_PEERS=true
UPDATE_CLI_CHEATSHEET=true
