# App
CHAIN_NAME="Andromeda"
CHAIN_SYSTEM_NAME="andromeda"
CHAIN_ICON="andromeda-icon.svg"
CHAIN_BACKGROUND_COLOR="#EC2842"

# Blockchain
CHAIN_ID="auto"
CHAIN_DENOM_PRETTY="ANDR"
CHAIN_DENOM="uandr"
CHAIN_FEES="20000"

# Binary
VERSION="auto"
DAEMON_NAME="andromedad"
DAEMON_SERVICE="andromedad.service"
DAEMON_HOME="~/.andromeda"

# Endpoints
ENDPOINT_RPC="https://andromeda-rpc.noders.services"
ENDPOINT_API="https://andromeda-api.noders.services"
ENDPOINT_JRPC=""
ENDPOINT_GRPC="andromeda-grpc.noders.services:443"
ENDPOINT_PEER="auto"
ENDPOINT_COSMOSLIST="https://cosmoslist.co/mainnet/andromeda"

# Social
SOCIAL_WEBSITE="https://www.andromedaprotocol.io/"
SOCIAL_GITHUB="https://github.com/andromedaprotocol"
SOCIAL_DISCORD="https://discord.gg/GBd6buKYyZ"
SOCIAL_X="https://twitter.com/andromedaprot"
SOCIAL_TELEGRAM="https://t.me/andromedaprotocol"

# Other
SNAPSHOT_URL="https://snapshots.noders.services/andromeda"
GITHUB_FOLDER_NAME="auto"
VALIDATOR_URL="https://andromeda.explorers.guru/validator/andrvaloper1t8zsecgzc5025k3s0mthdm6vt82p5p0v48p2ry"

# Updates
UPDATE_MAIN=true
UPDATE_CATEGORY=true
UPDATE_INSTALL=true
UPDATE_UPGRADE=true
UPDATE_SNAPSHOT=true
UPDATE_STATESYNC=true
UPDATE_LIVE_PEERS=true
UPDATE_CLI_CHEATSHEET=true
UPDATE_ENDPOINTS=true

# Feature toggles
# Node installation
SHOW_INSTALLATION_GUIDE=true
SHOW_UPGRADE_GUIDE=true
SHOW_GENESIS=true
SHOW_CLI=true
# Endpoints and Sync
SHOW_ENDPOINTS=true
SHOW_STATE_SYNC=true
SHOW_SNAPSHOT=true
SHOW_LIVE_PEERS=true
SHOW_SEED=true
SHOW_ADDRESS_BOOK=true
# Tools
SHOW_EXPLORERS_LIST=true
SHOW_PUBLIC_ENDPOINTS=false
SHOW_USEFUL_TOOLS=true
SHOW_UPGRADE_WATCHER=false
