# Blockchain
CHAIN_NAME="Andromeda"
CHAIN_SYSTEM_NAME="andromeda"
CHAIN_ID="auto"
VERSION="auto"
CHAIN_DESCRIPTION="""# Andromeda Protocol: Unveiling the aOS

The Andromeda Protocol heralds a new era in decentralized technology with its Andromeda Operating System (aOS), the first decentralized, on-chain operating system. It facilitates seamless development across blockchains, offering a unique suite of Web3 tools and utilities. Key features include multi-chain support, IBC for easy data transport, accessible tools for creators, rapid development with Andromeda Digital Objects (ADOs), and extensive integration with major blockchain platforms. Andromeda aims to enhance Web3 accessibility, efficiency, and scalability, fostering a rich ecosystem for developers and creators globally.

"""
[CHAIN_DESCRIPTION_END]

CHAIN_DENOM="uandr"
CHAIN_FEES="3000"

# Binary
DAEMON_NAME="andromedad"
DAEMON_SERVICE="andromedad.service"
DAEMON_HOME="~/.andromeda"

# Endpoints
ENDPOINT_RPC="https://andromeda-rpc.noders.services"
ENDPOINT_API="https://andromeda-api.noders.services"
ENDPOINT_JRPC=""
ENDPOINT_GRPC="http://andromeda-grpc.noders.services:34090"
ENDPOINT_PEER="auto"
ENDPOINT_COSMOSLIST="https://cosmoslist.co/mainnet/andromeda"

# Social
SOCIAL_WEBSITE="https://www.andromedaprotocol.io/"
SOCIAL_GITHUB="https://github.com/andromedaprotocol"
SOCIAL_DISCORD="https://discord.gg/GBd6buKYyZ"
SOCIAL_X="https://twitter.com/andromedaprot"
SOCIAL_TELEGRAM="https://t.me/andromedaprotocol"

# Other
DOWNLOAD_URL="https://config.noders.services/andromeda"
GITHUB_FOLDER_NAME="auto"
VALIDATOR_LINK="https://andromeda.explorers.guru/validator/andrvaloper1t8zsecgzc5025k3s0mthdm6vt82p5p0v48p2ry"

# Updates
UPDATE_MAIN=true
UPDATE_CATEGORY=true
UPDATE_INSTALL=true
UPDATE_UPGRADE=true
UPDATE_SNAPSHOT=true
UPDATE_STATESYNC=true
UPDATE_LIVE_PEERS=true
UPDATE_CLI_CHEATSHEET=true
