# Blockchain
CHAIN_NAME="Archway"
CHAIN_SYSTEM_NAME="archway"
CHAIN_ID="auto"
CHAIN_DESCRIPTION="""Archway is a dynamic project designed to empower developers by integrating innovative economic models with blockchain technology.

                   It functions as a multi-chain launchpad for decentralized applications (dApps), offering a suite of tools and modules that facilitate the development, deployment, and monetization of dApps. Here's a concise overview of its key features:

                   Smart Contract Premiums: Archway allows developers to embed a fee mechanism directly into their dApp's smart contracts, ensuring that developers receive 100% of these fees as revenue.

                   Inflationary Yield Engine: A portion of the network's token inflation is shared with dApps. Specifically, 25% of this inflation goes to dApp developers, while the remaining 75% is allocated to validators, supporting the network's security and efficiency.

                   Gas Fee Rebates: To incentivize usage and development on the platform, Archway offers gas fee rebates, where developers earn tokens each time their contract is executed. These tokens are distributed evenly between the developers and validators, fostering a balanced ecosystem.

                   Technical and Economic Framework: Archway's infrastructure is built on top of the Cosmos network, leveraging Tendermint consensus for scalability and interoperability. The project emphasizes a sustainable growth model, with detailed documentation available on its tech stack, economic principles, and intuitive tooling options.

                   For developers and stakeholders interested in blockchain and dApp development, Archway presents a comprehensive platform that not only simplifies the development process but also introduces a novel approach to dApp monetization and network participation rewards."""
CHAIN_DENOM="aarch"
CHAIN_FEES="3000000000"

# Binary
DAEMON_NAME="archwayd"
DAEMON_VERSION="v4.0.3"
DAEMON_SERVICE="aurad.service"
DAEMON_HOME="~/.archwayd"

# Endpoints
ENDPOINT_RPC=""
ENDPOINT_API=""
ENDPOINT_GRPCWEB=""
ENDPOINT_GRPC=""
ENDPOINT_PEER="auto"

# Social
SOCIAL_WEBSITE="https://archway.io/"
SOCIAL_GITHUB="https://github.com/archway-network"
SOCIAL_DISCORD="https://discord.gg/5FVvx3WGfa"
SOCIAL_X="https://twitter.com/archwayhq"
SOCIAL_TELEGRAM="https://t.me/archway_hq"

# Other
DOWNLOAD_URL="h"
GITHUB_FOLDER_NAME="auto"

# Updates
UPDATE_MAIN=true
UPDATE_CATEGORY=true
UPDATE_UPGRADE=true
UPDATE_SNAPSHOT=true
UPDATE_STATESYNC=true
UPDATE_LIVE_PEERS=true
UPDATE_CLI_CHEATSHEET=true
