# Blockchain
CHAIN_NAME="Archway"
CHAIN_SYSTEM_NAME="archway"
CHAIN_ID="auto"
VERSION="auto"
CHAIN_DESCRIPTION="""# Archway: Empowering dApp Development

Archway is redefining dApp development by integrating innovative economic models with blockchain technology. It provides a multi-chain launchpad with tools for creating, deploying, and monetizing dApps. Key features include smart contract premiums, an inflationary yield engine, gas fee rebates, and a robust framework built on Cosmos for scalability and interoperability. Archway's platform is designed for developers seeking a seamless development process with new monetization avenues, promoting a sustainable ecosystem for both creators and validators.

"""
[CHAIN_DESCRIPTION_END]

CHAIN_DENOM="aarch"
CHAIN_FEES="3000000000"

# Binary
DAEMON_NAME="archwayd"
DAEMON_SERVICE="archway.service"
DAEMON_HOME="~/.archwayd"

# Endpoints
ENDPOINT_RPC="https://archway-rpc.noders.services"
ENDPOINT_API="https://archway-api.noders.services"
ENDPOINT_JRPC=""
ENDPOINT_GRPC="archway-grpc.noders.services:13090"
ENDPOINT_PEER="auto"

# Social
SOCIAL_WEBSITE="https://archway.io/"
SOCIAL_GITHUB="https://github.com/archway-network"
SOCIAL_DISCORD="https://discord.gg/5FVvx3WGfa"
SOCIAL_X="https://twitter.com/archwayhq"
SOCIAL_TELEGRAM="https://t.me/archway_hq"

# Other
DOWNLOAD_URL="https://config.noders.services/archway"
GITHUB_FOLDER_NAME="auto"
VALIDATOR_LINK="https://archway.explorers.guru/validator/archwayvaloper173zlk665f6f4hl8rnmelhql9qkttc2e79z5xn6"

# Updates
UPDATE_MAIN=true
UPDATE_CATEGORY=true
UPDATE_INSTALL=true
UPDATE_UPGRADE=true
UPDATE_SNAPSHOT=true
UPDATE_STATESYNC=true
UPDATE_LIVE_PEERS=true
UPDATE_CLI_CHEATSHEET=true
