# Blockchain
CHAIN_NAME="Arkeo"
CHAIN_SYSTEM_NAME="arkeo"
CHAIN_ID="auto"
VERSION="auto"
CHAIN_DESCRIPTION=""" # Arkeo

Arkeo was created to provide decentralized applications with increased development velocity, censorship-resistance, and most importantly to be a needed tool in fully decentralizing the UI layer of the web3 stack, all while reducing reliance on centralized data sources. In short, Arkeo is a free-market solution for decentralized infrastructure.

"""
[CHAIN_DESCRIPTION_END]

CHAIN_DENOM="uarkeo"
CHAIN_FEES="20000"

# Binary
DAEMON_NAME="arkeod"
DAEMON_SERVICE="arkeo.service"
DAEMON_HOME="~/.arkeo"

# Endpoints
ENDPOINT_RPC="https://arkeo-rpc.noders.services"
ENDPOINT_API="https://arkeo-api.noders.services"
ENDPOINT_JRPC=""
ENDPOINT_GRPC="https://arkeo-grpc.noders.services:443"
ENDPOINT_PEER="auto"
ENDPOINT_COSMOSLIST="https://cosmoslist.co/mainnet/arkeo"

# Social
SOCIAL_WEBSITE="https://arkeo.network/"
SOCIAL_GITHUB="https://github.com/arkeonetwork"
SOCIAL_DISCORD="https://discord.gg/BfEHpm6uFc"
SOCIAL_X="https://twitter.com/arkeonetwork"
SOCIAL_TELEGRAM=""

# Other
SNAPSHOT_URL="https://snapshots.noders.services/arkeo"
GITHUB_FOLDER_NAME="auto"
VALIDATOR_URL="https://exp.utsa.tech/arkeo-main/staking/arkeovaloper1rnfgv6uhry6ywl880mgz4rmxm8csqwd74plfuu"

# Updates
UPDATE_MAIN=true
UPDATE_CATEGORY=true
UPDATE_INSTALL=true
UPDATE_UPGRADE=true
UPDATE_SNAPSHOT=true
UPDATE_STATESYNC=true
UPDATE_LIVE_PEERS=true
UPDATE_CLI_CHEATSHEET=true
