# App
CHAIN_NAME="Atomone"
CHAIN_SYSTEM_NAME="atomone"
CHAIN_ICON="atomone-icon.svg"
CHAIN_BACKGROUND_COLOR="#2c2a4b"

# NODERS
STAKE_URL="https://wallet.keplr.app/?modal=staking&chain=atomone-1&validator_address=atonevaloper1f2r68y2htcmp4rfe2wfn9f3nvzh9xsq9y0vdyz&step_id=3&action_id=stake"
RESTAKE_URL="https://restake.app/atomone/atonevaloper1f2r68y2htcmp4rfe2wfn9f3nvzh9xsq9y0vdyz"
VALIDATOR_URL="https://ping.pub/atomone/staking/atonevaloper1f2r68y2htcmp4rfe2wfn9f3nvzh9xsq9y0vdyz"
EXPLORER_URL=""
EXPLORER_IMAGE="atomone-exp.png"
APP_URL=""
APP_IMAGE=""
FAUCET_URL="https://faucet.noders.services/atomone"

# Blockchain
CHAIN_ID="auto"
CHAIN_DENOM_PRETTY="ATONE"
CHAIN_DENOM="uatone"
CHAIN_FEES="20000"

# Binary
VERSION="auto"
DAEMON_NAME="atomoned"
DAEMON_SERVICE="atomone.service"
DAEMON_HOME="~/.atomone"

# Endpoints
ENDPOINT_RPC="https://atomone-rpc.noders.services"
ENDPOINT_API="https://atomone-api.noders.services"
ENDPOINT_JRPC=""
ENDPOINT_GRPC="atomone-grpc.noders.services:443"
ENDPOINT_PEER="auto"
ENDPOINT_COSMOSLIST="https://cosmoslist.co/mainnet/atomone"
ENDPOINT_SEED="177ad7d9765ed3f55b734ccb9b27330a7340a86c@atomone-seed.noders.services:14533"

# Social
SOCIAL_WEBSITE=""
SOCIAL_GITHUB="https://github.com/atomone-hub/atomone"
SOCIAL_DISCORD="https://discord.gg/FEgcVkNYBA"
SOCIAL_X="https://x.com/_atomone"
SOCIAL_TELEGRAM=""

# Other
SNAPSHOT_URL="https://snapshots.noders.services/atomone"
GITHUB_FOLDER_NAME="auto"

# Updates
UPDATE_MAIN=true
UPDATE_CATEGORY=true
UPDATE_INSTALL=true
UPDATE_UPGRADE=true
UPDATE_SNAPSHOT=true
UPDATE_STATESYNC=true
UPDATE_LIVE_PEERS=true
UPDATE_CLI_CHEATSHEET=true
UPDATE_ENDPOINTS=true

# Feature toggles
# Node installation
SHOW_INSTALLATION_GUIDE=true
SHOW_UPGRADE_GUIDE=true
SHOW_GENESIS=true
SHOW_CLI=true
# Endpoints and Sync
SHOW_ENDPOINTS=true
SHOW_STATE_SYNC=true
SHOW_SNAPSHOT=true
SHOW_LIVE_PEERS=true
SHOW_SEED=true
SHOW_ADDRESS_BOOK=true
# Tools
SHOW_EXPLORERS_LIST=true
SHOW_PUBLIC_ENDPOINTS=false
SHOW_USEFUL_TOOLS=true
SHOW_UPGRADE_WATCHER=false
