# Blockchain
CHAIN_NAME="Aura"
CHAIN_SYSTEM_NAME="aura"
CHAIN_ID="auto"
VERSION="auto"
CHAIN_DESCRIPTION="""# Aura Network: Accelerating Global NFT Adoption

Aura Network, a Layer-1 blockchain, focuses on scalability, interoperability, and user experience to drive NFT adoption. It offers high transaction efficiency, seamless cross-chain communication, developer-friendly tools, intuitive user interfaces, and an energy-efficient consensus mechanism. Ideal for dApps, NFT marketplaces, gaming, and social media, Aura Network aims to enhance blockchain accessibility and foster a sustainable, interconnected digital ecosystem.

"""
[CHAIN_DESCRIPTION_END]

CHAIN_DENOM="uaura"
CHAIN_FEES="3000"

# Binary
DAEMON_NAME="aurad"
DAEMON_SERVICE="aurad.service"
DAEMON_HOME="~/.aura"

# Endpoints
ENDPOINT_RPC="https://aura-rpc.noders.services"
ENDPOINT_API="https://aura-api.noders.services"
ENDPOINT_JRPC=""
ENDPOINT_GRPC="http://aura-grpc.noders.services:17090"
ENDPOINT_PEER="auto"
ENDPOINT_COSMOSLIST="https://cosmoslist.co/mainnet/aura"

# Social
SOCIAL_WEBSITE="https://aura.network/"
SOCIAL_GITHUB="https://github.com/aura-nw"
SOCIAL_DISCORD="https://discord.com/invite/ZFHepmtZvr"
SOCIAL_X="https://twitter.com/AuraNetworkHQ"
SOCIAL_TELEGRAM="https://t.me/AuraNetworkOfficial"

# Other
DOWNLOAD_URL="https://config.noders.services/aura"
GITHUB_FOLDER_NAME="auto"
VALIDATOR_LINK="https://aurascan.io/validators/auravaloper1vvqz6j3ucxr6n0ejdz4ck602lnyjew93cgcw4m"

# Updates
UPDATE_MAIN=true
UPDATE_CATEGORY=true
UPDATE_INSTALL=true
UPDATE_UPGRADE=true
UPDATE_SNAPSHOT=true
UPDATE_STATESYNC=true
UPDATE_LIVE_PEERS=true
UPDATE_CLI_CHEATSHEET=true
