# App
CHAIN_NAME="Aura"
CHAIN_SYSTEM_NAME="aura"
CHAIN_ICON="aura-icon.svg"
CHAIN_BACKGROUND_COLOR=""

# Blockchain
CHAIN_ID="auto"
CHAIN_DENOM="uaura"
CHAIN_FEES="20000"

# Binary
VERSION="auto"
DAEMON_NAME="aurad"
DAEMON_SERVICE="aurad.service"
DAEMON_HOME="~/.aura"

# Endpoints
ENDPOINT_RPC="https://aura-rpc.noders.services"
ENDPOINT_API="https://aura-api.noders.services"
ENDPOINT_JRPC=""
ENDPOINT_GRPC="https://aura-grpc.noders.services:443"
ENDPOINT_PEER="auto"
ENDPOINT_COSMOSLIST="https://cosmoslist.co/mainnet/aura"

# Social
SOCIAL_WEBSITE="https://aura.network/"
SOCIAL_GITHUB="https://github.com/aura-nw"
SOCIAL_DISCORD="https://discord.com/invite/ZFHepmtZvr"
SOCIAL_X="https://twitter.com/AuraNetworkHQ"
SOCIAL_TELEGRAM="https://t.me/AuraNetworkOfficial"

# Other
SNAPSHOT_URL="https://snapshots.noders.services/aura"
GITHUB_FOLDER_NAME="auto"
VALIDATOR_URL="https://aurascan.io/validators/auravaloper1vvqz6j3ucxr6n0ejdz4ck602lnyjew93cgcw4m"

# Updates
UPDATE_MAIN=true
UPDATE_CATEGORY=true
UPDATE_INSTALL=true
UPDATE_UPGRADE=true
UPDATE_SNAPSHOT=true
UPDATE_STATESYNC=true
UPDATE_LIVE_PEERS=true
UPDATE_CLI_CHEATSHEET=true
UPDATE_ENDPOINTS=true

# Feature toggles
# Node installation
SHOW_INSTALLATION_GUIDE=true
SHOW_UPGRADE_GUIDE=true
SHOW_GENESIS=true
SHOW_CLI=true
# Endpoints and Sync
SHOW_ENDPOINTS=true
SHOW_STATE_SYNC=true
SHOW_SNAPSHOT=true
SHOW_LIVE_PEERS=true
SHOW_SEED=true
SHOW_ADDRESS_BOOK=true
# Tools
SHOW_EXPLORERS_LIST=false
SHOW_PUBLIC_ENDPOINTS=false
SHOW_USEFUL_TOOLS=false
SHOW_UPGRADE_WATCHER=false
