# App
CHAIN_NAME="BitSong"
CHAIN_SYSTEM_NAME="bitsong"
CHAIN_ICON="bitsong-icon.svg"
CHAIN_BACKGROUND_COLOR="#F42172"

# NODERS
STAKE_URL=""
RESTAKE_URL="https://restake.app/bitsong/bitsongvaloper19qtzdsu57hf5jmcyy5t2uuh0y45q4ah7hrwk4n"
VALIDATOR_URL="https://ping.pub/bitsong/staking/bitsongvaloper19qtzdsu57hf5jmcyy5t2uuh0y45q4ah7hrwk4n"
EXPLORER_URL=""
EXPLORER_IMAGE=""
APP_URL=""
APP_IMAGE=""
FAUCET_URL=""

# Blockchain
CHAIN_ID="auto"
CHAIN_DENOM="ubtsg"
CHAIN_FEES="20000"

# Binary
VERSION="auto"
DAEMON_NAME="bitsongd"
DAEMON_SERVICE="bitsongd.service"
DAEMON_HOME="~/.bitsongd"

# Endpoints
ENDPOINT_RPC="https://bitsong-rpc.noders.services"
ENDPOINT_API="https://bitsong-api.noders.services"
ENDPOINT_JRPC=""
ENDPOINT_GRPC="bitsong-grpc.noders.services:443"
ENDPOINT_PEER="auto"
ENDPOINT_SEED="955a296a5b32b8c91ae1a573edb4e9f9983e7c5f@bitsong-seed.noders.services:16033"
ENDPOINT_COSMOSLIST="https://cosmoslist.co/mainnet/bitsong"

# Social
SOCIAL_WEBSITE="https://bitsong.io/"
SOCIAL_GITHUB="https://github.com/bitsongofficial"
SOCIAL_DISCORD="https://discord.com/invite/mZC9Yk3"
SOCIAL_X="https://twitter.com/bitsongofficial"
SOCIAL_TELEGRAM="https://t.me/BitSongOfficial"

# Other
SNAPSHOT_URL="https://snapshots.noders.services/bitsong"
GITHUB_FOLDER_NAME="auto"

# Updates
UPDATE_MAIN=true
UPDATE_CATEGORY=true
UPDATE_INSTALL=true
UPDATE_UPGRADE=true
UPDATE_SNAPSHOT=true
UPDATE_STATESYNC=true
UPDATE_LIVE_PEERS=true
UPDATE_CLI_CHEATSHEET=true
UPDATE_ENDPOINTS=true
UPDATE_MONITORING=true

# Feature toggles
# Node installation
SHOW_INSTALLATION_GUIDE=true
SHOW_UPGRADE_GUIDE=true
SHOW_GENESIS=true
SHOW_CLI=true
# Endpoints and Sync
SHOW_ENDPOINTS=true
SHOW_STATE_SYNC=true
SHOW_SNAPSHOT=true
SHOW_LIVE_PEERS=true
SHOW_SEED=true
SHOW_ADDRESS_BOOK=true
# Tools
SHOW_EXPLORERS_LIST=true
SHOW_PUBLIC_ENDPOINTS=false
SHOW_USEFUL_TOOLS=true
SHOW_UPGRADE_WATCHER=false
# Monitoring Configuration
MONITORING_PROMETHEUS_PORT="9090"
MONITORING_GRAFANA_PORT="3000"
MONITORING_NODE_METRICS_PORT="26660"
MONITORING_GRAFANA_PASSWORD="admin123"
MONITORING_MAX_MISSED_BLOCKS="5"
MONITORING_DASHBOARD_ID="15991"
