# Blockchain
CHAIN_NAME="BitSong"
CHAIN_SYSTEM_NAME="bitsong"
CHAIN_ID="auto"
VERSION="auto"
CHAIN_DESCRIPTION="""# BitSong: A New Era in Music Streaming

BitSong revolutionizes music streaming with blockchain, offering direct artist compensation, decentralized distribution, tokenization of music assets, fan engagement rewards, and transparent royalties management. It aims to solve industry inefficiencies, enhancing fairness and connection between artists and fans. BitSong opens up new investment opportunities, facilitates crowdfunding, and streamlines music licensing, marking a significant shift towards a more equitable and transparent music ecosystem.

"""
[CHAIN_DESCRIPTION_END]

CHAIN_DENOM="ubtsg"
CHAIN_FEES="20000"

# Binary
DAEMON_NAME="bitsongd"
DAEMON_SERVICE="bitsongd.service"
DAEMON_HOME="~/.bitsongd"

# Endpoints
ENDPOINT_RPC="https://bitsong-rpc.noders.services"
ENDPOINT_API="https://bitsong-api.noders.services"
ENDPOINT_JRPC=""
ENDPOINT_GRPC="https://bitsong-grpc.noders.services:443"
ENDPOINT_PEER="auto"
ENDPOINT_COSMOSLIST="https://cosmoslist.co/mainnet/bitsong"

# Social
SOCIAL_WEBSITE="https://bitsong.io/"
SOCIAL_GITHUB="https://github.com/bitsongofficial"
SOCIAL_DISCORD="https://discord.com/invite/mZC9Yk3"
SOCIAL_X="https://twitter.com/bitsongofficial"
SOCIAL_TELEGRAM="https://t.me/BitSongOfficial"

# Other
DOWNLOAD_URL="https://snapshots.noders.services/bitsong"
GITHUB_FOLDER_NAME="auto"
VALIDATOR_LINK="https://ping.pub/bitsong/staking/bitsongvaloper19qtzdsu57hf5jmcyy5t2uuh0y45q4ah7hrwk4n"

# Updates
UPDATE_MAIN=true
UPDATE_CATEGORY=true
UPDATE_INSTALL=true
UPDATE_UPGRADE=true
UPDATE_SNAPSHOT=true
UPDATE_STATESYNC=true
UPDATE_LIVE_PEERS=true
UPDATE_CLI_CHEATSHEET=true
