# Blockchain
CHAIN_NAME="BitSong"
CHAIN_SYSTEM_NAME="bitsong"
CHAIN_ID="auto"
CHAIN_DESCRIPTION="""Artists, Fans, Managers and Labels in One Single Holistic Ecosystem: $BTSG. Earn real-time royalties, discover exclusive content, mint and trade Fantokens, buy & sell NFTs

BitSong is a blockchain-based music streaming platform designed to revolutionize the music industry by leveraging the power of decentralized technology to benefit artists, listeners, and stakeholders within the music ecosystem. Aimed at solving the inefficiencies and transparency issues plaguing the traditional music industry, BitSong utilizes blockchain technology to create a more equitable, efficient, and direct connection between artists, fans, and music-related services.

Key Features of BitSong:
Direct Artist Compensation: BitSong enables artists to receive direct compensation for their music, bypassing traditional intermediaries. Payments are made automatically and transparently using smart contracts, ensuring that artists are fairly compensated for streams and downloads.

Decentralized Distribution: The platform offers a decentralized distribution system that reduces reliance on major record labels and distribution platforms. This approach not only empowers independent artists but also ensures a wider variety of music is accessible to fans.

Tokenization of Music Assets: BitSong leverages tokenization to represent music assets on the blockchain. This allows for the creation of unique, tradable tokens associated with specific music pieces or royalties, opening new investment opportunities within the music industry.

Fan Engagement and Rewards: Listeners can earn rewards in BitSong's native tokens by engaging with the platform, such as streaming music, participating in voting, or contributing to the community. This system encourages active participation and fosters a stronger artist-fan connection.

Transparent Royalties Management: The platform ensures transparency in royalties management and distribution. Artists and rights holders can track their earnings in real-time, providing clarity and trust in the financial aspects of music streaming.

Applications of BitSong:
BitSong is suitable for a range of applications within the music industry, including:

Streaming services that offer a wide range of music to listeners while ensuring artists are compensated fairly.

Crowdfunding campaigns for new music projects, allowing artists to raise funds directly from their fans.

Music licensing platforms for movies, commercials, and games, simplifying the process of acquiring rights and ensuring transparent compensation.

Conclusion:
BitSong represents a transformative approach to the music industry, leveraging blockchain technology to address long-standing challenges such as transparency, fair compensation, and artist autonomy. By creating a decentralized ecosystem that benefits all stakeholders, BitSong aims to redefine the relationship between artists and fans, making it more direct, rewarding, and sustainable. With its innovative features and focus on empowering artists and engaging listeners, BitSong is poised to make a significant impact on the future of music distribution and consumption."""

CHAIN_DENOM="ubtsg"
CHAIN_FEES="3000"

# Binary
DAEMON_NAME="bitsongd"
DAEMON_VERSION="v0.15.0"
DAEMON_SERVICE="bitsongd.service"
DAEMON_HOME="~/.bitsongd"

# Endpoints
ENDPOINT_RPC=""
ENDPOINT_API=""
ENDPOINT_GRPCWEB=""
ENDPOINT_GRPC=""
ENDPOINT_PEER="auto"

# Social
SOCIAL_WEBSITE="https://bitsong.io/"
SOCIAL_GITHUB="https://github.com/bitsongofficial"
SOCIAL_DISCORD="https://discord.com/invite/mZC9Yk3"
SOCIAL_X="https://twitter.com/bitsongofficial"
SOCIAL_TELEGRAM="https://t.me/BitSongOfficial"

# Other
DOWNLOAD_URL="h"
GITHUB_FOLDER_NAME="auto"

# Updates
UPDATE_MAIN=true
UPDATE_CATEGORY=true
UPDATE_UPGRADE=true
UPDATE_SNAPSHOT=true
UPDATE_STATESYNC=true
UPDATE_LIVE_PEERS=true
UPDATE_CLI_CHEATSHEET=true
