# App
CHAIN_NAME="Celestia"
CHAIN_SYSTEM_NAME="celestia"
CHAIN_ICON="celestia-icon.svg"
CHAIN_BACKGROUND_COLOR="#7B2BF9"

# NODERS
STAKE_URL="https://wallet.keplr.app/?modal=staking&chain=celestia&validator_address=celestiavaloper139mu0a0ucz0gmrkavm5wjar2lpx7yvxq3e25e5&step_id=3&action_id=stake"
RESTAKE_URL="https://restake.app/celestia/celestiavaloper139mu0a0ucz0gmrkavm5wjar2lpx7yvxq3e25e5"
VALIDATOR_URL="https://celestia.explorers.guru/validator/celestiavaloper139mu0a0ucz0gmrkavm5wjar2lpx7yvxq3e25e5"
EXPLORER_URL="https://celestiahub.org/explorer"
APP_URL="https://celestiahub.org"
APP_IMAGE="celestia-community-app.png"

# Blockchain
CHAIN_ID="auto"
CHAIN_DENOM_PRETTY="TIA"
CHAIN_DENOM="utia"
CHAIN_FEES="20000"

# Binary
VERSION="auto"
DAEMON_NAME="celestia-appd"
DAEMON_SERVICE="celestia-appd.service"
DAEMON_HOME="~/.celestia-app"

# Endpoints
ENDPOINT_RPC="https://celestia-rpc.noders.services"
ENDPOINT_API="https://celestia-api.noders.services"
ENDPOINT_JRPC=""
ENDPOINT_GRPC="https://celestia-grpc.noders.services:443"
ENDPOINT_PEER="auto"
ENDPOINT_COSMOSLIST="https://cosmoslist.co/mainnet/celestia"
ENDPOINT_SEED="6a1e1fd9f5a2ee93c86a8657ab329f11648b91dc@celestia-seed.noders.services:11633"

# Social
SOCIAL_WEBSITE="https://celestia.org/"
SOCIAL_GITHUB="https://github.com/celestiaorg/celestia-app"
SOCIAL_DISCORD="https://discord.gg/celestiacommunity"
SOCIAL_X="https://twitter.com/CelestiaOrg"
SOCIAL_TELEGRAM="https://t.me/celestiaru"

# Other
SNAPSHOT_URL="https://snapshots.noders.services/celestia"
GITHUB_FOLDER_NAME="auto"

# Updates
UPDATE_MAIN=true
UPDATE_CATEGORY=true
UPDATE_INSTALL=false
UPDATE_UPGRADE=true
UPDATE_SNAPSHOT=true
UPDATE_STATESYNC=true
UPDATE_LIVE_PEERS=true
UPDATE_CLI_CHEATSHEET=true
