# Blockchain
CHAIN_NAME="Celestia"
CHAIN_SYSTEM_NAME="celestia"
CHAIN_ID="auto"
CHAIN_DESCRIPTION="""Celestia stands out as a groundbreaking project within the blockchain ecosystem, offering a modular data availability network designed to scale securely with user growth.

It simplifies the process of launching personalized blockchains by providing a foundational layer that prioritizes data availability. Here's a concise overview of its core features:

Modularity: Celestia is crafted as a minimal blockchain that focuses on ordering and publishing transactions without executing them. This distinct separation between the consensus and execution layers modularizes the blockchain technology stack, allowing for greater flexibility and scalability.

Data Availability: At the heart of Celestia's innovation is its approach to ensuring data availability. This is crucial for verifying the validity of transactions without the need to download the entire blockchain. It addresses the fundamental question of whether transaction data has been published and is accessible for verification purposes.

Decoupling Consensus and Execution: By separating the consensus mechanism from transaction execution, Celestia enables a more efficient and scalable blockchain infrastructure. This architecture allows developers to build customized execution environments atop the Celestia network, tailored to their specific application needs.

Proof of Stake (PoS) Layer: Celestia incorporates a PoS layer for its data availability, ensuring a secure and decentralized mechanism for network participation. This not only contributes to the network's security but also promotes an energy-efficient consensus mechanism compared to traditional proof-of-work systems.

Celestia's innovative approach to blockchain architecture represents a significant step forward in the development of decentralized technologies. It offers developers and organizations the tools to create more scalable, efficient, and flexible blockchain solutions, paving the way for a new era of blockchain applications that can cater to the growing demands of users and industries."""

CHAIN_DENOM="utia"
CHAIN_FEES="3000"

# Binary
DAEMON_NAME="celestia-appd"
DAEMON_VERSION="v1.6.0"
DAEMON_SERVICE="celestia-appd.service"
DAEMON_HOME="~/.celestia-app"

# Endpoints
ENDPOINT_RPC=""
ENDPOINT_API=""
ENDPOINT_GRPCWEB=""
ENDPOINT_GRPC=""
ENDPOINT_PEER="auto"

# Social
SOCIAL_WEBSITE="https://celestia.org/"
SOCIAL_GITHUB="https://github.com/celestiaorg"
SOCIAL_DISCORD="https://discord.gg/celestiacommunity"
SOCIAL_X="https://twitter.com/CelestiaOrg"
SOCIAL_TELEGRAM="https://t.me/celestiaru"

# Other
DOWNLOAD_URL="h"
GITHUB_FOLDER_NAME="auto"

# Updates
UPDATE_MAIN=true
UPDATE_CATEGORY=true
UPDATE_UPGRADE=true
UPDATE_SNAPSHOT=true
UPDATE_STATESYNC=true
UPDATE_LIVE_PEERS=true
UPDATE_CLI_CHEATSHEET=true
