# App
CHAIN_NAME="Desmos"
CHAIN_SYSTEM_NAME="desmos"
CHAIN_ICON="desmos-icon.svg"
CHAIN_BACKGROUND_COLOR="#E97E58"

# NODERS
STAKE_URL=""
RESTAKE_URL="https://restake.app/desmos/desmosvaloper1pequu0gsvh9ay5rx2xyg6j7eratwufu560dpnu"
VALIDATOR_URL="https://bigdipper.live/desmos/validators/desmosvaloper1pequu0gsvh9ay5rx2xyg6j7eratwufu560dpnu"
EXPLORER_URL=""
EXPLORER_IMAGE=""
APP_URL=""
APP_IMAGE=""
FAUCET_URL=""

# Blockchain
CHAIN_ID="auto"
CHAIN_DENOM="udsm"
CHAIN_FEES="20000"

# Binary
VERSION="auto"
DAEMON_NAME="desmos"
DAEMON_SERVICE="desmos.service"
DAEMON_HOME="~/.desmos"

# Endpoints
ENDPOINT_RPC="https://desmos-rpc.noders.services"
ENDPOINT_API="https://desmos-api.noders.services"
ENDPOINT_JRPC=""
ENDPOINT_GRPC="desmos-grpc.noders.services:443"
ENDPOINT_PEER="auto"
ENDPOINT_SEED="5a40a86aad501a21816c4cb1be393dc9a4bda9b6@desmos-seed.noders.services:16233"
ENDPOINT_COSMOSLIST="https://cosmoslist.co/mainnet/desmos"

# Social
SOCIAL_WEBSITE="https://desmos.network/"
SOCIAL_GITHUB="https://github.com/desmos-labs"
SOCIAL_DISCORD="https://discord.desmos.network/"
SOCIAL_X="https://twitter.com/desmosnetwork"
SOCIAL_TELEGRAM="https://t.me/desmosnetwork"

# Other
SNAPSHOT_URL="https://snapshots.noders.services/desmos"
GITHUB_FOLDER_NAME="auto"

# Updates
UPDATE_MAIN=true
UPDATE_CATEGORY=true
UPDATE_INSTALL=true
UPDATE_UPGRADE=true
UPDATE_SNAPSHOT=true
UPDATE_STATESYNC=true
UPDATE_LIVE_PEERS=true
UPDATE_CLI_CHEATSHEET=true
UPDATE_ENDPOINTS=true
UPDATE_MONITORING=true

# Feature toggles

# Node installation
SHOW_INSTALLATION_GUIDE=true
SHOW_UPGRADE_GUIDE=true
SHOW_GENESIS=true
SHOW_CLI=true

# Endpoints and Sync
SHOW_ENDPOINTS=true
SHOW_STATE_SYNC=true
SHOW_SNAPSHOT=true
SHOW_LIVE_PEERS=true
SHOW_SEED=true
SHOW_ADDRESS_BOOK=true

# Tools
SHOW_EXPLORERS_LIST=true
SHOW_PUBLIC_ENDPOINTS=false
SHOW_USEFUL_TOOLS=true
SHOW_UPGRADE_WATCHER=false

# Monitoring Configuration
MONITORING_PROMETHEUS_PORT="9090"
MONITORING_GRAFANA_PORT="3000"
MONITORING_NODE_METRICS_PORT="26660"
MONITORING_GRAFANA_PASSWORD="admin123"
MONITORING_MAX_MISSED_BLOCKS="5"
MONITORING_DASHBOARD_ID="15991"
