# Blockchain
CHAIN_NAME="Desmos"
CHAIN_SYSTEM_NAME="desmos"
CHAIN_ID="auto"
VERSION="auto"
CHAIN_DESCRIPTION="""# Desmos: Empowering Decentralized Social Networking

Desmos revolutionizes social media, focusing on user empowerment, data sovereignty, and censorship resistance. It features decentralized identities for user privacy, content monetization through cryptocurrencies, and community-driven governance. Ensuring interoperability with other DApps, Desmos fosters an open ecosystem for diverse social interactions, challenging traditional social platforms by prioritizing privacy, freedom of expression, and direct creator compensation.

"""
[CHAIN_DESCRIPTION_END]

CHAIN_DENOM="uosmo"
CHAIN_FEES="3000"

# Binary
DAEMON_NAME="desmos"
DAEMON_SERVICE="desmos.service"
DAEMON_HOME="~/.desmos"

# Endpoints
ENDPOINT_RPC="https://desmos-rpc.noders.services"
ENDPOINT_API="https://desmos-api.noders.services"
ENDPOINT_JRPC=""
ENDPOINT_GRPC="desmos-grpc.noders.services:27090"
ENDPOINT_PEER="auto"

# Social
SOCIAL_WEBSITE="https://desmos.network/"
SOCIAL_GITHUB="https://github.com/desmos-labs"
SOCIAL_DISCORD="https://discord.desmos.network/"
SOCIAL_X="https://twitter.com/desmosnetwork"
SOCIAL_TELEGRAM="https://t.me/desmosnetwork"

# Other
DOWNLOAD_URL="https://config.noders.services/desmos"
GITHUB_FOLDER_NAME="auto"
VALIDATOR_LINK="https://www.mintscan.io/desmos/validators/desmosvaloper1pequu0gsvh9ay5rx2xyg6j7eratwufu560dpnu"

# Updates
UPDATE_MAIN=true
UPDATE_CATEGORY=true
UPDATE_INSTALL=true
UPDATE_UPGRADE=true
UPDATE_SNAPSHOT=true
UPDATE_STATESYNC=true
UPDATE_LIVE_PEERS=true
UPDATE_CLI_CHEATSHEET=true
