# App
CHAIN_NAME="Desmos"
CHAIN_SYSTEM_NAME="desmos"
CHAIN_ICON="desmos-icon.svg"
CHAIN_BACKGROUND_COLOR=""

# Blockchain
CHAIN_ID="auto"\
CHAIN_DENOM="udsm"
CHAIN_FEES="20000"

# Binary
VERSION="auto"
DAEMON_NAME="desmos"
DAEMON_SERVICE="desmos.service"
DAEMON_HOME="~/.desmos"

# Endpoints
ENDPOINT_RPC="https://desmos-rpc.noders.services"
ENDPOINT_API="https://desmos-api.noders.services"
ENDPOINT_JRPC=""
ENDPOINT_GRPC="https://desmos-grpc.noders.services:443"
ENDPOINT_PEER="auto"
ENDPOINT_COSMOSLIST="https://cosmoslist.co/mainnet/desmos"

# Social
SOCIAL_WEBSITE="https://desmos.network/"
SOCIAL_GITHUB="https://github.com/desmos-labs"
SOCIAL_DISCORD="https://discord.desmos.network/"
SOCIAL_X="https://twitter.com/desmosnetwork"
SOCIAL_TELEGRAM="https://t.me/desmosnetwork"

# Other
SNAPSHOT_URL="https://snapshots.noders.services/desmos"
GITHUB_FOLDER_NAME="auto"
VALIDATOR_URL="https://ping.pub/desmos/staking/desmosvaloper1pequu0gsvh9ay5rx2xyg6j7eratwufu560dpnu"

# Updates
UPDATE_MAIN=true
UPDATE_CATEGORY=true
UPDATE_INSTALL=true
UPDATE_UPGRADE=true
UPDATE_SNAPSHOT=true
UPDATE_STATESYNC=true
UPDATE_LIVE_PEERS=true
UPDATE_CLI_CHEATSHEET=true

# Feature toggles
# Node installation
SHOW_INSTALLATION_GUIDE=true
SHOW_UPGRADE_GUIDE=true
SHOW_GENESIS=true
SHOW_CLI=true
# Endpoints and Sync
SHOW_ENDPOINTS=true
SHOW_STATE_SYNC=true
SHOW_SNAPSHOT=true
SHOW_LIVE_PEERS=true
SHOW_SEED=true
SHOW_ADDRESS_BOOK=true
# Tools
SHOW_EXPLORERS_LIST=false
SHOW_PUBLIC_ENDPOINTS=false
SHOW_USEFUL_TOOLS=false
SHOW_UPGRADE_WATCHER=false
