# Blockchain
CHAIN_NAME="Fuel"
CHAIN_SYSTEM_NAME="fuel"
CHAIN_ID="auto"
VERSION="auto"
CHAIN_DESCRIPTION="""# Fuel
Fuel addresses a creeping centralization infecting the blockchain ecosystem, igniting a high-throughput architecture built for mass adoption, retaining low node requirements.

"""
[CHAIN_DESCRIPTION_END]

CHAIN_DENOM="fuel"
CHAIN_FEES="10"

# Binary
DAEMON_NAME="fuelsequencerd"
DAEMON_SERVICE="fuel.service"
DAEMON_HOME="~/.fuelsequencer"

# Endpoints
ENDPOINT_RPC="https://fuel-rpc.noders.services"
ENDPOINT_API="https://fuel-api.noders.services"
ENDPOINT_JRPC=""
ENDPOINT_GRPC="https://fuel-grpc.noders.services:443"
ENDPOINT_PEER="auto"
ENDPOINT_COSMOSLIST="https://cosmoslist.co/mainnet/fuel"

# Social
SOCIAL_WEBSITE="https://fuel.network/"
SOCIAL_GITHUB="https://github.com/FuelLabs"
SOCIAL_DISCORD="https://discord.com/invite/xfpK4Pe"
SOCIAL_X="https://x.com/fuel_network"
SOCIAL_TELEGRAM=""

# Other
SNAPSHOT_URL="https://snapshots.noders.services/fuel"
GITHUB_FOLDER_NAME="auto"
VALIDATOR_URL="https://mainnet.itrocket.net/fuel/staking/fuelsequencervaloper1hhzm5ud6a026lj84axxa98w258cgfxgkp6jr8l"

# Updates
UPDATE_MAIN=true
UPDATE_CATEGORY=true
UPDATE_INSTALL=true
UPDATE_UPGRADE=true
UPDATE_SNAPSHOT=true
UPDATE_STATESYNC=true
UPDATE_LIVE_PEERS=true
UPDATE_CLI_CHEATSHEET=true

# Feature toggles
# Node installation
SHOW_INSTALLATION_GUIDE=true
SHOW_UPGRADE_GUIDE=true
SHOW_GENESIS=true
SHOW_CLI=true
# Endpoints and Sync
SHOW_ENDPOINTS=true
SHOW_STATE_SYNC=true
SHOW_SNAPSHOT=true
SHOW_LIVE_PEERS=true
SHOW_SEED=true
SHOW_ADDRESS_BOOK=true
# Tools
SHOW_EXPLORERS_LIST=false
SHOW_PUBLIC_ENDPOINTS=false
SHOW_USEFUL_TOOLS=false
SHOW_UPGRADE_WATCHER=false
