# App
CHAIN_NAME="Gitopia"
CHAIN_SYSTEM_NAME="gitopia"
CHAIN_ICON="gitopia-icon.svg"
CHAIN_BACKGROUND_COLOR="#7269CA"

# Blockchain
CHAIN_ID="auto"
CHAIN_DENOM="ulore"
CHAIN_FEES="20000"

# Binary
VERSION="auto"
DAEMON_NAME="gitopiad"
DAEMON_SERVICE="gitopiad.service"
DAEMON_HOME="~/.gitopia"

# Endpoints
ENDPOINT_RPC="https://gitopia-rpc.noders.services"
ENDPOINT_API="https://gitopia-api.noders.services"
ENDPOINT_JRPC=""
ENDPOINT_GRPC="gitopia-grpc.noders.services:443"
ENDPOINT_PEER="auto"
ENDPOINT_COSMOSLIST="https://cosmoslist.co/mainnet/gitopia"

# Social
SOCIAL_WEBSITE="https://gitopia.com/"
SOCIAL_GITHUB="https://github.com/gitopia"
SOCIAL_DISCORD="https://discord.com/invite/aqsKW3hUHD"
SOCIAL_X="https://twitter.com/gitopiaDAO"
SOCIAL_TELEGRAM="https://t.me/Gitopia"

# Other
SNAPSHOT_URL="https://snapshots.noders.services/gitopia"
GITHUB_FOLDER_NAME="auto"
VALIDATOR_URL="https://ping.pub/gitopia/staking/gitopiavaloper1fpwhn7tevwz657rg00mc7zcf9eq4tg0a703dw8"

# Updates
UPDATE_MAIN=true
UPDATE_CATEGORY=true
UPDATE_INSTALL=true
UPDATE_UPGRADE=true
UPDATE_SNAPSHOT=true
UPDATE_STATESYNC=true
UPDATE_LIVE_PEERS=true
UPDATE_CLI_CHEATSHEET=true
UPDATE_ENDPOINTS=true

# Feature toggles
# Node installation
SHOW_INSTALLATION_GUIDE=true
SHOW_UPGRADE_GUIDE=true
SHOW_GENESIS=true
SHOW_CLI=true
# Endpoints and Sync
SHOW_ENDPOINTS=true
SHOW_STATE_SYNC=true
SHOW_SNAPSHOT=true
SHOW_LIVE_PEERS=true
SHOW_SEED=true
SHOW_ADDRESS_BOOK=true
# Tools
SHOW_EXPLORERS_LIST=true
SHOW_PUBLIC_ENDPOINTS=false
SHOW_USEFUL_TOOLS=false
SHOW_UPGRADE_WATCHER=false
