# Blockchain
CHAIN_NAME="Gitopia"
CHAIN_SYSTEM_NAME="gitopia"
CHAIN_ID="auto"
VERSION="auto"
CHAIN_DESCRIPTION="""# Gitopia: Empowering Developer Collaboration

Gitopia leverages blockchain to offer a decentralized code hosting platform, ensuring transparency, security, and immutability. It addresses centralization issues, promoting open-source development and community-driven projects. Features include decentralized governance, collaboration tools, and incentive mechanisms to reward contributions. Ideal for projects valuing transparency and community involvement, Gitopia fosters a secure, collaborative environment for developers globally.

"""
[CHAIN_DESCRIPTION_END]

CHAIN_DENOM="ulore"
CHAIN_FEES="3000"

# Binary
DAEMON_NAME="gitopiad"
DAEMON_SERVICE="gitopiad.service"
DAEMON_HOME="~/.gitopia"

# Endpoints
ENDPOINT_RPC="https://gitopia-rpc.noders.services"
ENDPOINT_API="https://gitopia-api.noders.services"
ENDPOINT_JRPC=""
ENDPOINT_GRPC="https://gitopia-grpc.noders.services:443"
ENDPOINT_PEER="auto"
ENDPOINT_COSMOSLIST="https://cosmoslist.co/mainnet/gitopia"

# Social
SOCIAL_WEBSITE="https://gitopia.com/"
SOCIAL_GITHUB="https://github.com/gitopia"
SOCIAL_DISCORD="https://discord.com/invite/aqsKW3hUHD"
SOCIAL_X="https://twitter.com/gitopiaDAO"
SOCIAL_TELEGRAM="https://t.me/Gitopia"

# Other
DOWNLOAD_URL="https://snapshots.noders.services/gitopia"
GITHUB_FOLDER_NAME="auto"
VALIDATOR_LINK="https://ping.pub/gitopia/staking/gitopiavaloper1fpwhn7tevwz657rg00mc7zcf9eq4tg0a703dw8"

# Updates
UPDATE_MAIN=true
UPDATE_CATEGORY=true
UPDATE_INSTALL=true
UPDATE_UPGRADE=true
UPDATE_SNAPSHOT=true
UPDATE_STATESYNC=true
UPDATE_LIVE_PEERS=true
UPDATE_CLI_CHEATSHEET=true
