# Blockchain
CHAIN_NAME="Haqq"
CHAIN_SYSTEM_NAME="haqq"
CHAIN_ID="auto"
VERSION="auto"
CHAIN_DESCRIPTION="""
# IslamicCoin: A Shariah-Compliant Digital Currency

IslamicCoin is designed for the Islamic community, ensuring Shariah compliance, promoting ethical investments, and supporting financial inclusion. It leverages blockchain for transparency and security, incorporates charitable mechanisms for Zakat and Sadaqah, and facilitates investments with a positive social impact. IslamicCoin aims to bridge traditional Islamic finance with modern digital currencies, offering a platform for global accessibility and ethical financial practices, appealing to Muslims and ethical investors alike.

"""
[CHAIN_DESCRIPTION_END]

CHAIN_DENOM="aISLM"
CHAIN_FEES="300000000000"

# Binary
DAEMON_NAME="haqqd"
DAEMON_SERVICE="haqqd.service"
DAEMON_HOME="~/.haqqd"

# Endpoints
ENDPOINT_RPC="https://haqq-rpc.noders.services"
ENDPOINT_API="https://haqq-api.noders.services"
ENDPOINT_JRPC="https://haqq-jsonrpc.noders.services"
ENDPOINT_GRPC="https://haqq-grpc.noders.services:443"
ENDPOINT_PEER="auto"
ENDPOINT_COSMOSLIST="https://cosmoslist.co/mainnet/haqq"

# Social
SOCIAL_WEBSITE="https://haqq.network/"
SOCIAL_GITHUB="https://github.com/haqq-network"
SOCIAL_DISCORD="https://discord.gg/CDtXuQG3Vd"
SOCIAL_X="https://twitter.com/The_HaqqNetwork"
SOCIAL_TELEGRAM="https://t.me/islamiccoin_int"

# Other
SNAPSHOT_URL="https://snapshots.noders.services/haqq"
GITHUB_FOLDER_NAME="auto"
VALIDATOR_URL="https://haqq.explorers.guru/validator/haqqvaloper1hgggrfgjeu4d5nveh03c6w37magsuqcy84p44t"

# Updates
UPDATE_MAIN=true
UPDATE_CATEGORY=true
UPDATE_INSTALL=true
UPDATE_UPGRADE=true
UPDATE_SNAPSHOT=true
UPDATE_STATESYNC=true
UPDATE_LIVE_PEERS=true
UPDATE_CLI_CHEATSHEET=true

# Feature toggles
# Node installation
SHOW_INSTALLATION_GUIDE=true
SHOW_UPGRADE_GUIDE=true
SHOW_GENESIS=true
SHOW_CLI=true
# Endpoints and Sync
SHOW_ENDPOINTS=true
SHOW_STATE_SYNC=true
SHOW_SNAPSHOT=true
SHOW_LIVE_PEERS=true
SHOW_SEED=true
SHOW_ADDRESS_BOOK=true
# Tools
SHOW_EXPLORERS_LIST=false
SHOW_PUBLIC_ENDPOINTS=false
SHOW_USEFUL_TOOLS=false
SHOW_UPGRADE_WATCHER=false
