# Blockchain
CHAIN_NAME="Humans"
CHAIN_SYSTEM_NAME="humans"
CHAIN_ID="auto"
VERSION="auto"
CHAIN_DESCRIPTION="""# Humans.ai: Ethical AI on Blockchain

Humans.ai integrates blockchain with AI for decentralized, ethical AI development, emphasizing community-driven innovation and ethical governance. It features a tokenized economy for rewarding contributions, prioritizes data privacy, and supports cross-industry AI applications. Aimed at fostering responsible AI development, Humans.ai champions transparency, user privacy, and equitable value distribution, setting a new standard for AI technologies across healthcare, finance, education, and more.

"""
[CHAIN_DESCRIPTION_END]

CHAIN_DENOM="aheart"
CHAIN_FEES="3000"

# Binary
DAEMON_NAME="humansd"
DAEMON_SERVICE="humansd.service"
DAEMON_HOME="~/.humansd"

# Endpoints
ENDPOINT_RPC="https://humans-rpc.noders.services"
ENDPOINT_API="https://humans-api.noders.services"
ENDPOINT_JCWEB="https://humans-jsonrpc.noders.services"
ENDPOINT_GRPC="humans-grpc.noders.services:21090"
ENDPOINT_PEER="auto"

# Social
SOCIAL_WEBSITE="https://humans.ai/"
SOCIAL_GITHUB="https://github.com/humansdotai"
SOCIAL_DISCORD="https://discord.gg/humansdotai/"
SOCIAL_X="https://twitter.com/humansdotai"
SOCIAL_TELEGRAM="https://t.me/humansdotai"

# Other
DOWNLOAD_URL="https://config.noders.services/humans"
GITHUB_FOLDER_NAME="auto"
VALIDATOR_LINK="https://humans.explorers.guru/validator/humanvaloper1xl4lxgvwesnehdkfpn92ku8fk99lkrk6kmjc98"

# Updates
UPDATE_MAIN=true
UPDATE_CATEGORY=true
UPDATE_INSTALL=true
UPDATE_UPGRADE=true
UPDATE_SNAPSHOT=true
UPDATE_STATESYNC=true
UPDATE_LIVE_PEERS=true
UPDATE_CLI_CHEATSHEET=true
