# App
CHAIN_NAME="Humans"
CHAIN_SYSTEM_NAME="humans"
CHAIN_ICON="humans-icon.svg"
CHAIN_BACKGROUND_COLOR="#5EFEC6"

# NODERS
STAKE_URL=""
RESTAKE_URL="https://restake.app/humans/humanvaloper1xl4lxgvwesnehdkfpn92ku8fk99lkrk6kmjc98"
VALIDATOR_URL="https://humans.explorers.guru/validator/humanvaloper1xl4lxgvwesnehdkfpn92ku8fk99lkrk6kmjc98"
EXPLORER_URL=""
EXPLORER_IMAGE=""
APP_URL=""
APP_IMAGE=""
FAUCET_URL=""

# Blockchain
CHAIN_ID="auto"
CHAIN_DENOM="aheart"
CHAIN_FEES="300000000000"

# Binary
VERSION="auto"
DAEMON_NAME="humansd"
DAEMON_SERVICE="humansd.service"
DAEMON_HOME="~/.humansd"

# Endpoints
ENDPOINT_RPC="https://humans-rpc.noders.services"
ENDPOINT_API="https://humans-api.noders.services"
ENDPOINT_JCWEB="https://humans-jsonrpc.noders.services"
ENDPOINT_GRPC="humans-grpc.noders.services:443"
ENDPOINT_PEER="auto"
ENDPOINT_SEED="2c347efd728f2c61930622bd69727280c18346a8@humans-seed.noders.services:18433"
ENDPOINT_COSMOSLIST="https://cosmoslist.co/mainnet/humans"

# Social
SOCIAL_WEBSITE="https://humans.ai/"
SOCIAL_GITHUB="https://github.com/humansdotai"
SOCIAL_DISCORD="https://discord.gg/humansdotai/"
SOCIAL_X="https://twitter.com/humansdotai"
SOCIAL_TELEGRAM="https://t.me/humansdotai"

# Other
SNAPSHOT_URL="https://snapshots.noders.services/humans"
GITHUB_FOLDER_NAME="auto"

# Updates
UPDATE_MAIN=true
UPDATE_CATEGORY=true
UPDATE_INSTALL=true
UPDATE_UPGRADE=true
UPDATE_SNAPSHOT=true
UPDATE_STATESYNC=true
UPDATE_LIVE_PEERS=true
UPDATE_CLI_CHEATSHEET=true
UPDATE_ENDPOINTS=true
UPDATE_MONITORING=true

# Feature toggles

# Node installation
SHOW_INSTALLATION_GUIDE=true
SHOW_UPGRADE_GUIDE=true
SHOW_GENESIS=true
SHOW_CLI=true

# Endpoints and Sync
SHOW_ENDPOINTS=true
SHOW_STATE_SYNC=true
SHOW_SNAPSHOT=true
SHOW_LIVE_PEERS=true
SHOW_SEED=true
SHOW_ADDRESS_BOOK=true

# Tools
SHOW_EXPLORERS_LIST=true
SHOW_PUBLIC_ENDPOINTS=false
SHOW_USEFUL_TOOLS=true
SHOW_UPGRADE_WATCHER=false

# Monitoring Configuration
MONITORING_PROMETHEUS_PORT="9090"
MONITORING_GRAFANA_PORT="3000"
MONITORING_NODE_METRICS_PORT="26661"
MONITORING_GRAFANA_PASSWORD="admin123"
MONITORING_MAX_MISSED_BLOCKS="5"
MONITORING_DASHBOARD_ID="15991"
