# Blockchain
CHAIN_NAME="Injective"
CHAIN_SYSTEM_NAME="injective"
CHAIN_ID="auto"
CHAIN_DESCRIPTION="""Injective Protocol heralds a new era in decentralized finance (DeFi) by introducing the first layer-2 decentralized exchange protocol that unlocks the full potential of borderless finance by supporting margin trading, derivatives, and futures.

Positioned as a fully decentralized platform, Injective Protocol enables users to trade without any restrictions, giving them the power to trade on any derivative market of their choosing. Here's an overview of what sets Injective Protocol apart:

Fully Decentralized Trading: Injective Protocol is pioneering the field of decentralized finance by offering a fully decentralized trading experience. This ensures that users have complete control over their funds without the need for intermediaries, thereby eliminating any points of failure.

Layer-2 Speed and Efficiency: By leveraging layer-2 solutions, Injective Protocol offers lightning-fast trade execution and settlement with near-zero gas fees. This scalability solution ensures that the platform can handle the high volume of transactions without compromising on speed or cost.

Interoperable Blockchain: Injective Protocol is built to be fully interoperable, allowing seamless cross-chain trading. This means users can trade across different blockchains, opening up a wide range of trading possibilities and access to diverse markets.

Decentralized Order Book: Unlike many DeFi platforms that rely on automated market makers (AMMs), Injective Protocol utilizes a fully decentralized order book. This feature provides traders with the traditional trading experience they are accustomed to, offering more flexibility and control over their trades.

Community-Driven Network: The governance of Injective Protocol is entirely community-driven, allowing token holders to propose and vote on changes to the protocol. This ensures that the platform remains aligned with the needs and interests of its users.

Innovative Financial Instruments: Injective Protocol is not just limited to traditional crypto assets. It also introduces a wide array of innovative financial instruments, including exotic derivatives, forex, synthetics, and more, all of which are accessible through a secure and decentralized platform.

Integration and Partnerships: Injective Protocol has established strong partnerships with leading blockchain and DeFi projects to enhance its ecosystem. These collaborations aim to bring new markets and opportunities to users, further enriching the trading experience.

Injective Protocol is on a mission to democratize finance by providing a highly scalable, interoperable, and fully decentralized trading platform. It is designed to cater to all levels of traders, from beginners to institutional, by offering an intuitive interface, advanced trading features, and access to a wide range of markets, all while ensuring security, transparency, and control over one's own assets."""
CHAIN_DENOM="inj"
CHAIN_FEES="3000"

# Binary
DAEMON_NAME="injectived"
DAEMON_VERSION="v1.12.1"
DAEMON_SERVICE="injectived.service"
DAEMON_HOME="~/.injectived"

# Endpoints
ENDPOINT_RPC=""
ENDPOINT_API=""
ENDPOINT_GRPCWEB=""
ENDPOINT_GRPC=""
ENDPOINT_PEER="auto"

# Social
SOCIAL_WEBSITE="https://injective.com/"
SOCIAL_GITHUB="https://github.com/InjectiveLabs"
SOCIAL_DISCORD="https://discord.com/invite/NK4qdbv"
SOCIAL_X="https://twitter.com/Injective"
SOCIAL_TELEGRAM="https://t.me/joininjective"

# Other
DOWNLOAD_URL="https://snapshots.mainnet.noders.team/injective/"
GITHUB_FOLDER_NAME="auto"

# Updates
UPDATE_MAIN=true
UPDATE_CATEGORY=true
UPDATE_UPGRADE=true
UPDATE_SNAPSHOT=true
UPDATE_STATESYNC=true
UPDATE_LIVE_PEERS=true
UPDATE_CLI_CHEATSHEET=true
