# Blockchain
CHAIN_NAME="Injective"
CHAIN_SYSTEM_NAME="injective"
CHAIN_ID="auto"
VERSION_HAND="v1.12.1"
VERSION="auto"
CHAIN_DESCRIPTION="""# Injective Protocol: Pioneering DeFi Trading

Injective Protocol revolutionizes DeFi by offering a decentralized, permissionless, and scalable trading platform for spot and derivatives across blockchains. Key features include fully decentralized trading, cross-chain capabilities, zero gas fees, high performance, customizable market creation, and robust security measures. Catering to a broad audience, it supports diverse trading strategies and assets, making it a versatile choice for traders and investors seeking an inclusive, efficient, and secure trading experience in the DeFi ecosystem.

"""
[CHAIN_DESCRIPTION_END]

CHAIN_DENOM="inj"
CHAIN_FEES="3000"

# Binary
DAEMON_NAME="injectived"
DAEMON_SERVICE="injectived.service"
DAEMON_HOME="~/.injectived"

# Endpoints
ENDPOINT_RPC="https://injective-rpc.noders.services"
ENDPOINT_API="https://injective-api.noders.services"
ENDPOINT_JRPC=""
ENDPOINT_GRPC="http://injective-grpc.noders.services:33090"
ENDPOINT_PEER="auto"

# Social
SOCIAL_WEBSITE="https://injective.com/"
SOCIAL_GITHUB="https://github.com/InjectiveLabs"
SOCIAL_DISCORD="https://discord.com/invite/NK4qdbv"
SOCIAL_X="https://twitter.com/Injective"
SOCIAL_TELEGRAM="https://t.me/joininjective"

# Other
DOWNLOAD_URL="https://config.noders.services/injective"
GITHUB_FOLDER_NAME="auto"
VALIDATOR_LINK="https://www.mintscan.io/injective/validators/injvaloper17ucaxqrwmzak0g98ly3r6h30zm3r5ph4c68n6k"

# Updates
UPDATE_MAIN=true
UPDATE_CATEGORY=true
UPDATE_INSTALL=true
UPDATE_UPGRADE=true
UPDATE_SNAPSHOT=true
UPDATE_STATESYNC=true
UPDATE_LIVE_PEERS=true
UPDATE_CLI_CHEATSHEET=true
