# App
CHAIN_NAME="Jackal"
CHAIN_SYSTEM_NAME="jackal"
CHAIN_ICON="jackal-icon.svg"
CHAIN_BACKGROUND_COLOR=""

# Blockchain
CHAIN_ID="auto"
VERSION_HAND="v3.2.1"
CHAIN_DENOM="ujckl"
CHAIN_FEES="20000"

# Binary
VERSION="auto"
DAEMON_NAME="canined"
DAEMON_SERVICE="canined.service"
DAEMON_HOME="~/.canine"

# Endpoints
ENDPOINT_RPC="https://jackal-rpc.noders.services"
ENDPOINT_API="https://jackal-api.noders.services"
ENDPOINT_JRPC=""
ENDPOINT_GRPC="https://jackal-grpc.noders.services:443"
ENDPOINT_PEER="auto"
ENDPOINT_COSMOSLIST="https://cosmoslist.co/mainnet/jackal"

# Social
SOCIAL_WEBSITE="https://www.jackalprotocol.com/"
SOCIAL_GITHUB="https://github.com/JackalLabs/canine-chain"
SOCIAL_DISCORD="https://discord.com/invite/5GKym3p6rj"
SOCIAL_X="https://twitter.com/Jackal_Protocol"
SOCIAL_TELEGRAM="https://t.me/+rtuZnbTlHaIzNjVh"

# Other
SNAPSHOT_URL="https://snapshots.noders.services/jackal"
GITHUB_FOLDER_NAME="auto"
VALIDATOR_URL="https://ping.pub/jackal/staking/jklvaloper132k95jan8ju92jtmkzr49vnusv5xvwvju27kpq"

# Updates
UPDATE_MAIN=true
UPDATE_CATEGORY=true
UPDATE_INSTALL=true
UPDATE_UPGRADE=true
UPDATE_SNAPSHOT=true
UPDATE_STATESYNC=true
UPDATE_LIVE_PEERS=true
UPDATE_CLI_CHEATSHEET=true

# Feature toggles
# Node installation
SHOW_INSTALLATION_GUIDE=true
SHOW_UPGRADE_GUIDE=true
SHOW_GENESIS=true
SHOW_CLI=true
# Endpoints and Sync
SHOW_ENDPOINTS=true
SHOW_STATE_SYNC=true
SHOW_SNAPSHOT=true
SHOW_LIVE_PEERS=true
SHOW_SEED=true
SHOW_ADDRESS_BOOK=true
# Tools
SHOW_EXPLORERS_LIST=false
SHOW_PUBLIC_ENDPOINTS=false
SHOW_USEFUL_TOOLS=false
SHOW_UPGRADE_WATCHER=false
