# App
CHAIN_NAME="Kopi"
CHAIN_SYSTEM_NAME="kopi"
CHAIN_ICON="kopi-icon.svg"
CHAIN_BACKGROUND_COLOR="#B9E17C"

# NODERS
STAKE_URL=""
RESTAKE_URL="https://restake.app/kopi/kopivaloper1ctu3g3m2jyp26m03vhjap2aua8646magep7y36"
VALIDATOR_URL="https://explorer.kopi.money/luwak-1/staking/kopivaloper1ctu3g3m2jyp26m03vhjap2aua8646magep7y36"
EXPLORER_URL=""
EXPLORER_IMAGE=""
APP_URL=""
APP_IMAGE=""
FAUCET_URL=""

# Blockchain
CHAIN_ID="auto"
CHAIN_DENOM="ukopi"
CHAIN_FEES="20000"

# Binary
VERSION="auto"
DAEMON_NAME="uxkp"
DAEMON_SERVICE="kopi.service"
DAEMON_HOME="~/.kopid"

# Endpoints
ENDPOINT_RPC="https://kopi-rpc.noders.services"
ENDPOINT_API="https://kopi-api.noders.services"
ENDPOINT_JRPC=""
ENDPOINT_GRPC="kopi-grpc.noders.services:443"
ENDPOINT_PEER="auto"
ENDPOINT_SEED="7fa77c0236b0c0b99c5c957e11def8a2531ecbce@kopi-seed.noders.services:30733"
ENDPOINT_COSMOSLIST="https://cosmoslist.co/mainnet/kopi"

# Social
SOCIAL_WEBSITE="https://kopi.money/"
SOCIAL_GITHUB="https://github.com/kopi-money/kopi"
SOCIAL_DISCORD="https://discord.gg/GvnwSwsCcs"
SOCIAL_X="https://twitter.com/kopi_money/"
SOCIAL_TELEGRAM="https://t.me/+_hk--L9mKKc4MThk"

# Other
SNAPSHOT_URL="https://snapshots.noders.services/kopi"
GITHUB_FOLDER_NAME="auto"

# Updates
UPDATE_MAIN=true
UPDATE_CATEGORY=true
UPDATE_INSTALL=true
UPDATE_UPGRADE=true
UPDATE_SNAPSHOT=true
UPDATE_STATESYNC=true
UPDATE_LIVE_PEERS=true
UPDATE_CLI_CHEATSHEET=true
UPDATE_ENDPOINTS=true
UPDATE_MONITORING=true

# Feature toggles

# Node installation
SHOW_INSTALLATION_GUIDE=true
SHOW_UPGRADE_GUIDE=true
SHOW_GENESIS=true
SHOW_CLI=true

# Endpoints and Sync
SHOW_ENDPOINTS=true
SHOW_STATE_SYNC=true
SHOW_SNAPSHOT=true
SHOW_LIVE_PEERS=true
SHOW_SEED=true
SHOW_ADDRESS_BOOK=true

# Tools
SHOW_EXPLORERS_LIST=true
SHOW_PUBLIC_ENDPOINTS=false
SHOW_USEFUL_TOOLS=true
SHOW_UPGRADE_WATCHER=false

# Monitoring Configuration
MONITORING_PROMETHEUS_PORT="9090"
MONITORING_GRAFANA_PORT="3000"
MONITORING_NODE_METRICS_PORT="26661"
MONITORING_GRAFANA_PASSWORD="admin123"
MONITORING_MAX_MISSED_BLOCKS="5"

