# Blockchain
CHAIN_NAME="Kyve"
CHAIN_SYSTEM_NAME="kyve"
CHAIN_ID="auto"
VERSION="auto"
CHAIN_DESCRIPTION="""# KYVE Network: Revolutionizing Blockchain Data Integrity

KYVE Network transforms data storage and validation across blockchains, ensuring data remains unchanged and accessible. It emphasizes decentralized storage, accurate data validation, interoperability, customizable data pools, and a token-based incentive mechanism. KYVE supports diverse applications, from enhancing blockchain scalability to enabling secure cross-chain bridges, making it pivotal for future decentralized data ecosystems.

Discover how KYVE is shaping the future of data integrity on the blockchain.

"""
[CHAIN_DESCRIPTION_END]

CHAIN_DENOM="ukyve"
CHAIN_FEES="3000"

# Binary
DAEMON_NAME="kyved"
DAEMON_SERVICE="kyved.service"
DAEMON_HOME="~/.kyve"

# Endpoints
ENDPOINT_RPC="https://kyve-rpc.noders.services"
ENDPOINT_API="https://kyve-api.noders.services"
ENDPOINT_JRPC=""
ENDPOINT_GRPC="http://kyve-grpc.noders.services:15090"
ENDPOINT_PEER="auto"
ENDPOINT_COSMOSLIST="https://cosmoslist.co/mainnet/kyve"

# Social
SOCIAL_WEBSITE="https://www.kyve.network/"
SOCIAL_GITHUB="https://github.com/KYVENetwork"
SOCIAL_DISCORD="https://discord.gg/PATvZvEmxF"
SOCIAL_X="https://twitter.com/KYVENetwork"
SOCIAL_TELEGRAM="https://t.me/kyvenet"

# Other
DOWNLOAD_URL="https://config.noders.services/kyve"
GITHUB_FOLDER_NAME="auto"
VALIDATOR_LINK="https://kyve.explorers.guru/validator/kyvevaloper1sfwfat9p9k7datgy0kzge7pv0szcd5ycc0jxre"

# Updates
UPDATE_MAIN=true
UPDATE_CATEGORY=true
UPDATE_INSTALL=true
UPDATE_UPGRADE=true
UPDATE_SNAPSHOT=true
UPDATE_STATESYNC=true
UPDATE_LIVE_PEERS=true
UPDATE_CLI_CHEATSHEET=true
