# App
CHAIN_NAME="Kyve"
CHAIN_SYSTEM_NAME="kyve"
CHAIN_ICON="kyve-icon.svg"
CHAIN_BACKGROUND_COLOR="#58C9B0"

# NODERS
STAKE_URL="https://wallet.keplr.app/?modal=staking&chain=kyve-1&validator_address=kyvevaloper1sfwfat9p9k7datgy0kzge7pv0szcd5ycc0jxre&step_id=3&action_id=stake"
RESTAKE_URL="https://restake.app/kyve/kyvevaloper1sfwfat9p9k7datgy0kzge7pv0szcd5ycc0jxre"
VALIDATOR_URL="https://kyve.explorers.guru/validator/kyvevaloper1sfwfat9p9k7datgy0kzge7pv0szcd5ycc0jxre"
EXPLORER_URL=""
EXPLORER_IMAGE=""
APP_URL=""
APP_IMAGE=""
FAUCET_URL=""

# Blockchain
CHAIN_ID="auto"
CHAIN_DENOM="ukyve"
CHAIN_FEES="20000"

# Binary
VERSION="auto"
DAEMON_NAME="kyved"
DAEMON_SERVICE="kyved.service"
DAEMON_HOME="~/.kyve"

# Endpoints
ENDPOINT_RPC="https://kyve-rpc.noders.services"
ENDPOINT_API="https://kyve-api.noders.services"
ENDPOINT_JRPC=""
ENDPOINT_GRPC="kyve-grpc.noders.services:443"
ENDPOINT_PEER="auto"
ENDPOINT_SEED="e1356e3df8cb93516037eed48d38e206351b64d4@kyve-seed.noders.services:11033"
ENDPOINT_COSMOSLIST="https://cosmoslist.co/mainnet/kyve"

# Social
SOCIAL_WEBSITE="https://www.kyve.network/"
SOCIAL_GITHUB="https://github.com/KYVENetwork"
SOCIAL_DISCORD="https://discord.gg/PATvZvEmxF"
SOCIAL_X="https://twitter.com/KYVENetwork"
SOCIAL_TELEGRAM="https://t.me/kyvenet"

# Other
SNAPSHOT_URL="https://snapshots.noders.services/kyve"
GITHUB_FOLDER_NAME="auto"

# Updates
UPDATE_MAIN=true
UPDATE_CATEGORY=true
UPDATE_INSTALL=true
UPDATE_UPGRADE=true
UPDATE_SNAPSHOT=true
UPDATE_STATESYNC=true
UPDATE_LIVE_PEERS=true
UPDATE_CLI_CHEATSHEET=true
UPDATE_ENDPOINTS=true
UPDATE_MONITORING=true

# Feature toggles

# Node installation
SHOW_INSTALLATION_GUIDE=true
SHOW_UPGRADE_GUIDE=true
SHOW_GENESIS=true
SHOW_CLI=true

# Endpoints and Sync
SHOW_ENDPOINTS=true
SHOW_STATE_SYNC=true
SHOW_SNAPSHOT=true
SHOW_LIVE_PEERS=true
SHOW_SEED=true
SHOW_ADDRESS_BOOK=true

# Tools
SHOW_EXPLORERS_LIST=true
SHOW_PUBLIC_ENDPOINTS=false
SHOW_USEFUL_TOOLS=true
SHOW_UPGRADE_WATCHER=false
SHOW_MONITORING=true

# Monitoring Configuration
MONITORING_PROMETHEUS_PORT="9090"
MONITORING_GRAFANA_PORT="3000"
MONITORING_NODE_METRICS_PORT="26661"
MONITORING_GRAFANA_PASSWORD="admin123"
MONITORING_MAX_MISSED_BLOCKS="5"

