# Blockchain
CHAIN_NAME="Lambda"
CHAIN_SYSTEM_NAME="lambda"
CHAIN_ID="auto"
VERSION="auto"
CHAIN_DESCRIPTION="""# Lambda: Revolutionizing Decentralized Storage

Lambda introduces a cutting-edge blockchain infrastructure for secure, scalable, and decentralized data storage. It offers a solution that prioritizes data integrity and privacy through distributed storage and Proof of Space-Time. Designed to support the expansive data needs of dApps, Lambda ensures efficient data processing and accessibility. With its emphasis on privacy, scalability, and a marketplace for storage resources, Lambda is setting new standards for decentralized storage, paving the way for a future where data sovereignty and security are paramount.

Discover more about Lambda's approach to decentralized storage.

"""
[CHAIN_DESCRIPTION_END]

CHAIN_DENOM="ulamb"
CHAIN_FEES="3000"

# Binary
DAEMON_NAME="lambdavm"
DAEMON_SERVICE="lambdavm.service"
DAEMON_HOME="~/.lambdavm"

# Endpoints
ENDPOINT_RPC="https://lambda-rpc.noders.services"
ENDPOINT_API="https://lambda-api.noders.services"
ENDPOINT_JRPC=""
ENDPOINT_GRPC="lambda-grpc.noders.services:31090"
ENDPOINT_PEER="auto"

# Social
SOCIAL_WEBSITE="https://lambda.im/"
SOCIAL_GITHUB="https://github.com/LambdaIM"
SOCIAL_DISCORD="https://discord.gg/lambdanetwork"
SOCIAL_X="https://twitter.com/Lambdaim"
SOCIAL_TELEGRAM="https://t.me/HelloLambda"

# Other
DOWNLOAD_URL="https://config.noders.services/lambda"
GITHUB_FOLDER_NAME="auto"
VALIDATOR_LINK="https://ping.pub/lambda/staking/lambvaloper1jwuypnpg2m5rxpr2jl9teqcwerk534x3296hns"

# Updates
UPDATE_MAIN=true
UPDATE_CATEGORY=true
UPDATE_INSTALL=true
UPDATE_UPGRADE=true
UPDATE_SNAPSHOT=true
UPDATE_STATESYNC=true
UPDATE_LIVE_PEERS=true
UPDATE_CLI_CHEATSHEET=true
