# Blockchain
CHAIN_NAME="Lava"
CHAIN_SYSTEM_NAME="lava"
CHAIN_ID="auto"
VERSION="auto"
CHAIN_DESCRIPTION="""# LavaNet: Igniting the Future of Decentralized Connectivity

LavaNet is set to redefine the landscape of decentralized networks by introducing a high-speed, secure, and scalable blockchain infrastructure. Aimed at facilitating seamless and efficient communication across the digital world, LavaNet leverages state-of-the-art cryptographic techniques to ensure data integrity and privacy. With a focus on user empowerment, LavaNet offers a decentralized platform for applications that require reliable data exchange and connectivity. By integrating advanced consensus mechanisms and smart contract functionality, LavaNet provides a robust foundation for developing decentralized applications (dApps) that can operate across multiple industries, including finance, healthcare, and entertainment. LavaNet's vision is to create a fully decentralized internet where users have complete control over their data and digital interactions.

"""
[CHAIN_DESCRIPTION_END]

CHAIN_DENOM="ulava"
CHAIN_FEES="20000"

# Binary
DAEMON_NAME="lavad"
DAEMON_SERVICE="lava.service"
DAEMON_HOME="~/.lava"

# Endpoints
ENDPOINT_RPC="https://lava-rpc.noders.services"
ENDPOINT_API="https://lava-api.noders.services"
ENDPOINT_JRPC=""
ENDPOINT_GRPC="https://lava-grpc.noders.services:443"
ENDPOINT_PEER="auto"
ENDPOINT_COSMOSLIST="https://cosmoslist.co/mainnet/lava"

# Social
SOCIAL_WEBSITE="https://www.lavanet.xyz/"
SOCIAL_GITHUB="https://github.com/lavanet"
SOCIAL_DISCORD="https://discord.gg/Tbk5NxTCdA"
SOCIAL_X="https://twitter.com/lavanetxyz"
SOCIAL_TELEGRAM=""

# Other
DOWNLOAD_URL="https://snapshots.noders.services/lava"
GITHUB_FOLDER_NAME="auto"
VALIDATOR_LINK="https://lava.explorers.guru/validator/lava@valoper1cfup2qa0dcmx9y0tm73rp3yend3chhzkaakd85"

# Updates
UPDATE_MAIN=true
UPDATE_CATEGORY=true
UPDATE_INSTALL=true
UPDATE_UPGRADE=true
UPDATE_SNAPSHOT=true
UPDATE_STATESYNC=true
UPDATE_LIVE_PEERS=true
UPDATE_CLI_CHEATSHEET=true
