# App
CHAIN_NAME="Lava"
CHAIN_SYSTEM_NAME="lava"
CHAIN_ICON="lava-icon.svg"
CHAIN_BACKGROUND_COLOR="#D7001F"

# NODERS
STAKE_URL="https://wallet.keplr.app/?modal=staking&chain=lava-mainnet-1&validator_address=lava@valoper1cfup2qa0dcmx9y0tm73rp3yend3chhzkaakd85&step_id=3&action_id=stake"
RESTAKE_URL="https://restake.app/lava/lava@valoper1cfup2qa0dcmx9y0tm73rp3yend3chhzkaakd85"
VALIDATOR_URL="https://lava.explorers.guru/validator/lava@valoper1cfup2qa0dcmx9y0tm73rp3yend3chhzkaakd85"
EXPLORER_URL=""
EXPLORER_IMAGE="lava-exp.png"
APP_URL=""
APP_IMAGE=""
FAUCET_URL=""

# Blockchain
CHAIN_ID="auto"
CHAIN_DENOM_PRETTY="LAVA"
CHAIN_DENOM="ulava"
CHAIN_FEES="20000"

# Binary
VERSION="auto"
DAEMON_NAME="lavad"
DAEMON_SERVICE="lava.service"
DAEMON_HOME="~/.lava"

# Endpoints
ENDPOINT_RPC="https://lava-rpc.noders.services"
ENDPOINT_API="https://lava-api.noders.services"
ENDPOINT_JRPC=""
ENDPOINT_GRPC="lava-grpc.noders.services:443"
ENDPOINT_PEER="auto"
ENDPOINT_SEED="7f766b97d027ef2e398fa6093f6368c3f1c49b39@lava-seed.noders.services:19933"
ENDPOINT_COSMOSLIST="https://cosmoslist.co/mainnet/lava"
ENDPOINT_SEED=""

# Social
SOCIAL_WEBSITE="https://www.lavanet.xyz/"
SOCIAL_GITHUB="https://github.com/lavanet"
SOCIAL_DISCORD="https://discord.gg/Tbk5NxTCdA"
SOCIAL_X="https://twitter.com/lavanetxyz"
SOCIAL_TELEGRAM=""

# Other
SNAPSHOT_URL="https://snapshots.noders.services/lava"
GITHUB_FOLDER_NAME="auto"

# Updates
UPDATE_MAIN=true
UPDATE_CATEGORY=true
UPDATE_INSTALL=true
UPDATE_UPGRADE=true
UPDATE_SNAPSHOT=true
UPDATE_STATESYNC=true
UPDATE_LIVE_PEERS=true
UPDATE_CLI_CHEATSHEET=true
UPDATE_ENDPOINTS=true
UPDATE_MONITORING=true

# Feature toggles

# Node installation
SHOW_INSTALLATION_GUIDE=true
SHOW_UPGRADE_GUIDE=true
SHOW_GENESIS=true
SHOW_CLI=true

# Endpoints and Sync
SHOW_ENDPOINTS=true
SHOW_STATE_SYNC=true
SHOW_SNAPSHOT=true
SHOW_LIVE_PEERS=true
SHOW_SEED=true
SHOW_ADDRESS_BOOK=true

# Tools
SHOW_EXPLORERS_LIST=true
SHOW_PUBLIC_ENDPOINTS=false
SHOW_USEFUL_TOOLS=true
SHOW_UPGRADE_WATCHER=false

# Monitoring Configuration
MONITORING_PROMETHEUS_PORT="9090"
MONITORING_GRAFANA_PORT="3000"
MONITORING_NODE_METRICS_PORT="26660"
MONITORING_GRAFANA_PASSWORD="admin123"
MONITORING_MAX_MISSED_BLOCKS="5"
MONITORING_DASHBOARD_ID="15991"
