# App
CHAIN_NAME="Namada"
CHAIN_SYSTEM_NAME="namada"
CHAIN_ICON="namada-icon.svg"
CHAIN_BACKGROUND_COLOR=""

# Blockchain
CHAIN_ID="auto"
CHAIN_DENOM="NAM"
CHAIN_FEES="1"

# Binary
VERSION="auto"
DAEMON_NAME="namadad"
DAEMON_SERVICE="namada.service"
DAEMON_HOME="~/.local"

# Endpoints
ENDPOINT_RPC="https://namada-rpc.noders.services/"
ENDPOINT_API=""
ENDPOINT_JRPC=""
ENDPOINT_GRPC=""
ENDPOINT_PEER="auto"
ENDPOINT_COSMOSLIST="https://cosmoslist.co/mainnet/namada"

# Social
SOCIAL_WEBSITE="https://namada.net/"
SOCIAL_GITHUB="https://github.com/anoma/namada"
SOCIAL_DISCORD="https://discord.com/invite/namada"
SOCIAL_X="https://twitter.com/namada"
SOCIAL_TELEGRAM="https://t.me/+pjXZFdE9s-s2OGVi"

# Other
SNAPSHOT_URL=""
GITHUB_FOLDER_NAME="auto"
VALIDATOR_URL="https://namada.coverlet.io/validators/2A8B3E24756A4782D26169B60AB9418816668101220F705DDDDA3C47334ADF5E"

# Updates
UPDATE_MAIN=false
UPDATE_CATEGORY=false
UPDATE_INSTALL=false
UPDATE_UPGRADE=false
UPDATE_SNAPSHOT=false
UPDATE_STATESYNC=false
UPDATE_LIVE_PEERS=false
UPDATE_CLI_CHEATSHEET=false

# Feature toggles
# Node installation
SHOW_INSTALLATION_GUIDE=true
SHOW_UPGRADE_GUIDE=true
SHOW_GENESIS=true
SHOW_CLI=true
# Endpoints and Sync
SHOW_ENDPOINTS=true
SHOW_STATE_SYNC=true
SHOW_SNAPSHOT=true
SHOW_LIVE_PEERS=true
SHOW_SEED=true
SHOW_ADDRESS_BOOK=true
# Tools
SHOW_EXPLORERS_LIST=false
SHOW_PUBLIC_ENDPOINTS=false
SHOW_USEFUL_TOOLS=false
SHOW_UPGRADE_WATCHER=false
