# Blockchain
CHAIN_NAME="Namada"
CHAIN_SYSTEM_NAME="namada"
CHAIN_ID="auto"
VERSION="auto"
CHAIN_DESCRIPTION=""" # Namada

is a Proof-of-Stake L1 for interchain asset-agnostic privacy. Namada uses CometBFT consensus and enables multi-asset shielded transfers for any native or non-native asset. Namada features full IBC protocol support, a natively integrated Ethereum bridge, a modern proof-of-stake system with automatic reward compounding and cubic slashing, and a stake-weighted governance signalling mechanism. Users of shielded transfers are rewarded for their contributions to the privacy set in the form of native protocol tokens. A multi-asset shielded transfer wallet is provided in order to facilitate safe and private user interaction with the protocol.

"""
[CHAIN_DESCRIPTION_END]

CHAIN_DENOM="NAM"
CHAIN_FEES="1"

# Binary
DAEMON_NAME="namadad"
DAEMON_SERVICE="namada.service"
DAEMON_HOME="~/.local"

# Endpoints
ENDPOINT_RPC="https://namada-rpc.noders.services/"
ENDPOINT_API=""
ENDPOINT_JRPC=""
ENDPOINT_GRPC=""
ENDPOINT_PEER="auto"
ENDPOINT_COSMOSLIST="https://cosmoslist.co/mainnet/namada"

# Social
SOCIAL_WEBSITE="https://namada.net/"
SOCIAL_GITHUB="https://github.com/anoma/namada"
SOCIAL_DISCORD="https://discord.com/invite/namada"
SOCIAL_X="https://twitter.com/namada"
SOCIAL_TELEGRAM="https://t.me/+pjXZFdE9s-s2OGVi"

# Other
DOWNLOAD_URL=""
GITHUB_FOLDER_NAME="auto"
VALIDATOR_LINK="https://namada.coverlet.io/validators/2A8B3E24756A4782D26169B60AB9418816668101220F705DDDDA3C47334ADF5E"

# Updates
UPDATE_MAIN=false
UPDATE_CATEGORY=false
UPDATE_INSTALL=false
UPDATE_UPGRADE=false
UPDATE_SNAPSHOT=false
UPDATE_STATESYNC=false
UPDATE_LIVE_PEERS=false
UPDATE_CLI_CHEATSHEET=false
