# App
CHAIN_NAME="Namada"
CHAIN_SYSTEM_NAME="namada"
CHAIN_ICON="namada-icon.svg"
CHAIN_BACKGROUND_COLOR="#feff00"

# NODERS
STAKE_URL="https://namadillo.noders.services/staking/bonding/increment"
RESTAKE_URL=""
VALIDATOR_URL="https://namada.coverlet.io/validators/2A8B3E24756A4782D26169B60AB9418816668101220F705DDDDA3C47334ADF5E"
EXPLORER_URL=""
EXPLORER_IMAGE="namada-exp.png"
APP_URL="https://namadahub.org"
APP_IMAGE="namada-app.png"
FAUCET_URL=""

# Blockchain
CHAIN_ID="namada.5f5de2dd1b88cba30586420"
CHAIN_DENOM_PRETTY="NAM"
CHAIN_DENOM="NAM"
CHAIN_FEES="1"

# Binary
VERSION="v1.0.0"
DAEMON_NAME="namadad"
DAEMON_SERVICE="namada.service"
DAEMON_HOME="~/.local"

# Endpoints
ENDPOINT_RPC="https://namada-rpc.noders.services/"
ENDPOINT_API=""
ENDPOINT_JRPC=""
ENDPOINT_GRPC=""
ENDPOINT_PEER="auto"
ENDPOINT_COSMOSLIST="https://cosmoslist.co/mainnet/namada"
ENDPOINT_SEED=""

# Social
SOCIAL_WEBSITE="https://namada.net/"
SOCIAL_GITHUB="https://github.com/anoma/namada"
SOCIAL_DISCORD="https://discord.com/invite/namada"
SOCIAL_X="https://twitter.com/namada"
SOCIAL_TELEGRAM="https://t.me/+pjXZFdE9s-s2OGVi"

# Other
SNAPSHOT_URL=""
GITHUB_FOLDER_NAME="auto"

# Updates
UPDATE_MAIN=true
UPDATE_CATEGORY=false
UPDATE_INSTALL=false
UPDATE_UPGRADE=false
UPDATE_SNAPSHOT=false
UPDATE_STATESYNC=false
UPDATE_LIVE_PEERS=false
UPDATE_CLI_CHEATSHEET=false
UPDATE_ENDPOINTS=true

# Feature toggles
# Node installation
SHOW_INSTALLATION_GUIDE=true
SHOW_UPGRADE_GUIDE=false
SHOW_GENESIS=false
SHOW_CLI=true
# Endpoints and Sync
SHOW_ENDPOINTS=true
SHOW_STATE_SYNC=false
SHOW_SNAPSHOT=false
SHOW_LIVE_PEERS=false
SHOW_SEED=false
SHOW_ADDRESS_BOOK=false
# Tools
SHOW_EXPLORERS_LIST=true
SHOW_PUBLIC_ENDPOINTS=false
SHOW_USEFUL_TOOLS=true
SHOW_UPGRADE_WATCHER=false
