# Blockchain
CHAIN_NAME="Nibiru"
CHAIN_SYSTEM_NAME="nibiru"
CHAIN_ID="auto"
VERSION="auto"
CHAIN_DESCRIPTION="""# Nibiru: decentralized finance

Nibiru is a decentralized finance (DeFi) platform and part of the Cosmos ecosystem, designed to support the development and operation of distributed applications (dApps).

It features a smart contract framework built with Rust for improved security and performance. The platform uses a unique royalties system where developers receive a portion of the gas fees from transactions involving their smart contracts, incentivizing the creation and maintenance of dApps. Nibiru also includes innovative trading solutions like the Nibi-Perps, a decentralized exchange (DEX) for perpetual futures that allows up to 10x leverage trading, and the Nibi-Swap, an automated market maker (AMM) for spot trading​

"""
[CHAIN_DESCRIPTION_END]

CHAIN_DENOM="unibi"
CHAIN_FEES="3000"

# Binary
DAEMON_NAME="nibid"
DAEMON_SERVICE="nibid.service"
DAEMON_HOME="~/.nibid"

# Endpoints
ENDPOINT_RPC="https://nibiru-rpc.noders.services"
ENDPOINT_API="https://nibiru-api.noders.services"
ENDPOINT_JRPC=""
ENDPOINT_GRPC="http://nibiru-grpc.noders.services:35090"
ENDPOINT_PEER="auto"

# Social
SOCIAL_WEBSITE="https://nibiru.fi/"
SOCIAL_GITHUB="https://github.com/NibiruChain"
SOCIAL_DISCORD="https://discord.gg/nibirufi"
SOCIAL_X="https://twitter.com/NibiruChain"
SOCIAL_TELEGRAM="https://t.me/nibiruchain"

# Other
DOWNLOAD_URL="https://config.noders.services/nibiru"
GITHUB_FOLDER_NAME="auto"
VALIDATOR_LINK=""

# Updates
UPDATE_MAIN=true
UPDATE_CATEGORY=true
UPDATE_INSTALL=true
UPDATE_UPGRADE=true
UPDATE_SNAPSHOT=true
UPDATE_STATESYNC=true
UPDATE_LIVE_PEERS=true
UPDATE_CLI_CHEATSHEET=true
