# Blockchain
CHAIN_NAME="Osmosis"
CHAIN_SYSTEM_NAME="osmosis"
CHAIN_ID="auto"
VERSION="auto"
CHAIN_DESCRIPTION="""# Osmosis: DeFi Innovation on Cosmos

Osmosis is a leading decentralized exchange (DEX) and automated market maker (AMM) on the Cosmos blockchain, revolutionizing DeFi with unparalleled customization and interoperability. It enables advanced DeFi features for liquidity providers and traders, fostering cross-chain liquidity and novel financial products. With customizable AMM pools, Inter-Blockchain Communication (IBC) protocol integration, superfluid staking, and community-driven governance, Osmosis is at the forefront of DeFi innovation, offering dynamic yield farming and sophisticated trading strategies within the Cosmos ecosystem.

Discover more about Osmosis and its innovative features by visiting their official site.

"""
[CHAIN_DESCRIPTION_END]

CHAIN_DENOM="uosmo"
CHAIN_FEES="20000"

# Binary
DAEMON_NAME="osmosisd"
DAEMON_SERVICE="osmosisd.service"
DAEMON_HOME="~/.osmosisd"

# Endpoints
ENDPOINT_RPC="https://osmosis-rpc.noders.services"
ENDPOINT_API="https://osmosis-api.noders.services"
ENDPOINT_JRPC=""
ENDPOINT_GRPC="https://osmosis-grpc.noders.services:443"
ENDPOINT_PEER="auto"
ENDPOINT_COSMOSLIST="https://cosmoslist.co/mainnet/osmosis"

# Social
SOCIAL_WEBSITE="https://app.osmosis.zone/"
SOCIAL_GITHUB="https://github.com/osmosis-labs/osmosis"
SOCIAL_DISCORD="https://discord.com/invite/osmosis"
SOCIAL_X="https://twitter.com/osmosiszone"
SOCIAL_TELEGRAM="https://t.me/osmosiszone"

# Other
SNAPSHOT_URL="https://snapshots.noders.services/osmosis"
GITHUB_FOLDER_NAME="auto"
VALIDATOR_URL=""

# Updates
UPDATE_MAIN=true
UPDATE_CATEGORY=true
UPDATE_INSTALL=true
UPDATE_UPGRADE=true
UPDATE_SNAPSHOT=true
UPDATE_STATESYNC=true
UPDATE_LIVE_PEERS=true
UPDATE_CLI_CHEATSHEET=true

# Feature toggles
# Node installation
SHOW_INSTALLATION_GUIDE=true
SHOW_UPGRADE_GUIDE=true
SHOW_GENESIS=true
SHOW_CLI=true
# Endpoints and Sync
SHOW_ENDPOINTS=true
SHOW_STATE_SYNC=true
SHOW_SNAPSHOT=true
SHOW_LIVE_PEERS=true
SHOW_SEED=true
SHOW_ADDRESS_BOOK=true
# Tools
SHOW_EXPLORERS_LIST=false
SHOW_PUBLIC_ENDPOINTS=false
SHOW_USEFUL_TOOLS=false
SHOW_UPGRADE_WATCHER=false
