# Blockchain
CHAIN_NAME="Osmosis"
CHAIN_SYSTEM_NAME="osmosis"
CHAIN_ID="auto"
CHAIN_DESCRIPTION="Osmosis is a decentralized peer-to-peer blockchain that people can use to create liquidity and trade IBC enabled tokens. The Osmosis blockchain is made up of free, public, and open-source software."
CHAIN_DENOM="uosmo"
CHAIN_FEES="3000"

# Binary
DAEMON_NAME="osmosisd"
DAEMON_VERSION="v23.0.0"
DAEMON_SERVICE="osmosisd.service"
DAEMON_HOME="~/.osmosisd"

# Endpoints
ENDPOINT_RPC="https://osmosis.rpc.mainnet.noders.team"
ENDPOINT_API="https://osmosis.api.mainnet.noders.team"
ENDPOINT_GRPCWEB="https://osmosis.grpc.mainnet.noders.team"
ENDPOINT_GRPC=""
ENDPOINT_PEER="auto"

# Social
SOCIAL_WEBSITE=""
SOCIAL_GITHUB="https://github.com/osmosis-labs/osmosis"
SOCIAL_DISCORD=""
SOCIAL_X=""
SOCIAL_TELEGRAM=""

# Other
DOWNLOAD_URL="https://snapshots.mainnet.noders.team/osmosis/"
GITHUB_FOLDER_NAME="auto"

# Updates
UPDATE_UPGRADE=true
UPDATE_SNAPSHOT=true
UPDATE_STATESYNC=true
UPDATE_LIVE_PEERS=true
UPDATE_CLI_CHEATSHEET=true
