# Blockchain
CHAIN_NAME="Pylons"
CHAIN_SYSTEM_NAME="pylons"
CHAIN_ID="auto"
VERSION="auto"
CHAIN_DESCRIPTION="""# Pylons: Enabling Seamless Blockchain Integration for Digital Assets

Pylons.tech is at the forefront of blockchain development, specializing in digital items and NFTs. It streamlines the creation of freemium DApps, marrying mobile Web3 experiences with traditional in-app purchases. Designed to facilitate easy onboarding, Pylons removes barriers like KYC and initial token buys, making on-chain gaming as accessible as its mainstream counterpart. Its innovative fiat bridge furthers this mission, ensuring direct purchases of digital assets, thereby democratizing access to the blockchain ecosystem.

"""
[CHAIN_DESCRIPTION_END]

CHAIN_DENOM="ubedrock"
CHAIN_FEES="3000"

# Binary
DAEMON_NAME="pylonsd"
DAEMON_SERVICE="pylons.service"
DAEMON_HOME="~/.pylonsd"

# Endpoints
ENDPOINT_RPC="https://pylons-rpc.noders.services"
ENDPOINT_API="https://pylons-api.noders.services"
ENDPOINT_JRPC=""
ENDPOINT_GRPC="http://pylons-grpc.noders.services:23090"
ENDPOINT_PEER="auto"
ENDPOINT_COSMOSLIST="https://cosmoslist.co/mainnet/pylons"

# Social
SOCIAL_WEBSITE="https://www.pylons.tech/home/"
SOCIAL_GITHUB="https://github.com/Pylons-tech/pylons"
SOCIAL_DISCORD="https://discord.gg/pylons"
SOCIAL_X="https://twitter.com/pylonstech"
SOCIAL_TELEGRAM=""

# Other
DOWNLOAD_URL="https://config.noders.services/pylons"
GITHUB_FOLDER_NAME="auto"
VALIDATOR_LINK="https://pylons.explorers.guru/validator/pylovaloper1yc06qqa99vz50jrh64fctt0gvjj7pp7n7029c7"

# Updates
UPDATE_MAIN=true
UPDATE_CATEGORY=true
UPDATE_INSTALL=true
UPDATE_UPGRADE=true
UPDATE_SNAPSHOT=true
UPDATE_STATESYNC=true
UPDATE_LIVE_PEERS=true
UPDATE_CLI_CHEATSHEET=true
