# App
CHAIN_NAME="Pylons"
CHAIN_SYSTEM_NAME="pylons"
CHAIN_ICON="pylons-icon.svg"
CHAIN_BACKGROUND_COLOR=""

# Blockchain
CHAIN_ID="auto"
CHAIN_DENOM="ubedrock"
CHAIN_FEES="20000"

# Binary
VERSION="auto"
DAEMON_NAME="pylonsd"
DAEMON_SERVICE="pylons.service"
DAEMON_HOME="~/.pylonsd"

# Endpoints
ENDPOINT_RPC="https://pylons-rpc.noders.services"
ENDPOINT_API="https://pylons-api.noders.services"
ENDPOINT_JRPC=""
ENDPOINT_GRPC="https://pylons-grpc.noders.services:443"
ENDPOINT_PEER="auto"
ENDPOINT_COSMOSLIST="https://cosmoslist.co/mainnet/pylons"

# Social
SOCIAL_WEBSITE="https://www.pylons.tech/home/"
SOCIAL_GITHUB="https://github.com/Pylons-tech/pylons"
SOCIAL_DISCORD="https://discord.gg/pylons"
SOCIAL_X="https://twitter.com/pylonstech"
SOCIAL_TELEGRAM=""

# Other
SNAPSHOT_URL="https://snapshots.noders.services/pylons"
GITHUB_FOLDER_NAME="auto"
VALIDATOR_URL="https://pylons.explorers.guru/validator/pylovaloper1yc06qqa99vz50jrh64fctt0gvjj7pp7n7029c7"

# Updates
UPDATE_MAIN=true
UPDATE_CATEGORY=true
UPDATE_INSTALL=true
UPDATE_UPGRADE=true
UPDATE_SNAPSHOT=true
UPDATE_STATESYNC=true
UPDATE_LIVE_PEERS=true
UPDATE_CLI_CHEATSHEET=true
UPDATE_ENDPOINTS=true

# Feature toggles
# Node installation
SHOW_INSTALLATION_GUIDE=true
SHOW_UPGRADE_GUIDE=true
SHOW_GENESIS=true
SHOW_CLI=true
# Endpoints and Sync
SHOW_ENDPOINTS=true
SHOW_STATE_SYNC=true
SHOW_SNAPSHOT=true
SHOW_LIVE_PEERS=true
SHOW_SEED=true
SHOW_ADDRESS_BOOK=true
# Tools
SHOW_EXPLORERS_LIST=false
SHOW_PUBLIC_ENDPOINTS=false
SHOW_USEFUL_TOOLS=false
SHOW_UPGRADE_WATCHER=false
