# App
CHAIN_NAME="Quicksilver"
CHAIN_SYSTEM_NAME="quicksilver"
CHAIN_ICON="quicksilver-icon.svg"
CHAIN_BACKGROUND_COLOR="#75757599"

# NODERS
STAKE_URL="https://wallet.keplr.app/?modal=staking&chain=quicksilver-2&validator_address=quickvaloper17gwfcceyvcw53r6cclrhwk5jksmtd96xfjwrcv&step_id=3&action_id=stake"
RESTAKE_URL="https://restake.app/quicksilver/quickvaloper17gwfcceyvcw53r6cclrhwk5jksmtd96xfjwrcv"
VALIDATOR_URL="https://explorer.quicksilver.zone/validators/quickvaloper17gwfcceyvcw53r6cclrhwk5jksmtd96xfjwrcv"
EXPLORER_URL=""
EXPLORER_IMAGE=""
APP_URL=""
APP_IMAGE=""
FAUCET_URL=""

# Blockchain
CHAIN_ID="auto"
CHAIN_DENOM="uqck"
CHAIN_FEES="20000"

# Binary
VERSION="auto"
DAEMON_NAME="quicksilverd"
DAEMON_SERVICE="quicksilverd.service"
DAEMON_HOME="~/.quicksilverd"

# Endpoints
ENDPOINT_RPC="https://quicksilver-rpc.noders.services"
ENDPOINT_API="https://quicksilver-api.noders.services"
ENDPOINT_JRPC=""
ENDPOINT_GRPC="quicksilver-grpc.noders.services:443"
ENDPOINT_PEER="auto"
ENDPOINT_SEED="ac869c9a4dde57428000424e707dfd6478c37629@quicksilver-seed.noders.services:11133"
ENDPOINT_COSMOSLIST="https://cosmoslist.co/mainnet/quicksilver"

# Social
SOCIAL_WEBSITE="https://quicksilver.zone/"
SOCIAL_GITHUB="https://github.com/quicksilver-zone"
SOCIAL_DISCORD="https://discord.com/invite/xrSmYMDVrQ"
SOCIAL_X="https://twitter.com/quicksilverzone"
SOCIAL_TELEGRAM="https://t.me/quicksilverzone"

# Other
SNAPSHOT_URL="https://snapshots.noders.services/quicksilver"
GITHUB_FOLDER_NAME="auto"

# Updates
UPDATE_MAIN=true
UPDATE_CATEGORY=true
UPDATE_INSTALL=true
UPDATE_UPGRADE=true
UPDATE_SNAPSHOT=true
UPDATE_STATESYNC=true
UPDATE_LIVE_PEERS=true
UPDATE_CLI_CHEATSHEET=true
UPDATE_ENDPOINTS=true
UPDATE_MONITORING=true

# Feature toggles
# Node installation
SHOW_INSTALLATION_GUIDE=true
SHOW_UPGRADE_GUIDE=true
SHOW_GENESIS=true
SHOW_CLI=true
# Endpoints and Sync
SHOW_ENDPOINTS=true
SHOW_STATE_SYNC=true
SHOW_SNAPSHOT=true
SHOW_LIVE_PEERS=true
SHOW_SEED=true
SHOW_ADDRESS_BOOK=true
# Tools
SHOW_EXPLORERS_LIST=true
SHOW_PUBLIC_ENDPOINTS=false
SHOW_USEFUL_TOOLS=true
SHOW_UPGRADE_WATCHER=false
# Monitoring Configuration
MONITORING_PROMETHEUS_PORT="9090"
MONITORING_GRAFANA_PORT="3000"
MONITORING_NODE_METRICS_PORT="26660"
MONITORING_GRAFANA_PASSWORD="admin123"
MONITORING_MAX_MISSED_BLOCKS="5"
MONITORING_DASHBOARD_ID="15991"
