# Blockchain
CHAIN_NAME="Quicksilver"
CHAIN_SYSTEM_NAME="quicksilver"
CHAIN_ID="auto"
VERSION="auto"
CHAIN_DESCRIPTION="""# Quicksilver: Enhancing DeFi via Liquid Staking on Cosmos

Quicksilver introduces liquid staking to the Cosmos ecosystem, unlocking liquidity for staked assets while maintaining network security participation. It features liquid staking derivatives, cross-chain functionality through the IBC protocol, decentralized governance, high security, and yield optimization. This protocol enables greater capital efficiency and a vibrant DeFi ecosystem, offering opportunities for lending, borrowing, and trading staked assets across chains, thus innovating within DeFi and Cosmos.

"""
[CHAIN_DESCRIPTION_END]

CHAIN_DENOM="uqck"
CHAIN_FEES="3000"

# Binary
DAEMON_NAME="quicksilverd"
DAEMON_SERVICE="quicksilverd.service"
DAEMON_HOME="~/.quicksilverd"

# Endpoints
ENDPOINT_RPC="https://quicksilver-rpc.noders.services"
ENDPOINT_API="https://quicksilver-api.noders.services"
ENDPOINT_JRPC=""
ENDPOINT_GRPC="http://quicksilver-grpc.noders.services:16090"
ENDPOINT_PEER="auto"

# Social
SOCIAL_WEBSITE="https://quicksilver.zone/"
SOCIAL_GITHUB="https://github.com/quicksilver-zone"
SOCIAL_DISCORD="https://discord.com/invite/xrSmYMDVrQ"
SOCIAL_X="https://twitter.com/quicksilverzone"
SOCIAL_TELEGRAM="https://t.me/quicksilverzone"

# Other
DOWNLOAD_URL="https://config.noders.services/quicksilver"
GITHUB_FOLDER_NAME="auto"
VALIDATOR_LINK="https://quicksilver.explorers.guru/validator/quickvaloper17gwfcceyvcw53r6cclrhwk5jksmtd96xfjwrcv

# Updates
UPDATE_MAIN=true
UPDATE_CATEGORY=true
UPDATE_INSTALL=true
UPDATE_UPGRADE=true
UPDATE_SNAPSHOT=true
UPDATE_STATESYNC=true
UPDATE_LIVE_PEERS=true
UPDATE_CLI_CHEATSHEET=true
