# App
CHAIN_NAME="Quicksilver"
CHAIN_SYSTEM_NAME="quicksilver"
CHAIN_ICON="quicksilver-icon.svg"
CHAIN_BACKGROUND_COLOR=""

# Blockchain
CHAIN_ID="auto"
CHAIN_DENOM="uqck"
CHAIN_FEES="20000"

# Binary
VERSION="auto"
DAEMON_NAME="quicksilverd"
DAEMON_SERVICE="quicksilverd.service"
DAEMON_HOME="~/.quicksilverd"

# Endpoints
ENDPOINT_RPC="https://quicksilver-rpc.noders.services"
ENDPOINT_API="https://quicksilver-api.noders.services"
ENDPOINT_JRPC=""
ENDPOINT_GRPC="https://quicksilver-grpc.noders.services:443"
ENDPOINT_PEER="auto"
ENDPOINT_COSMOSLIST="https://cosmoslist.co/mainnet/quicksilver"

# Social
SOCIAL_WEBSITE="https://quicksilver.zone/"
SOCIAL_GITHUB="https://github.com/quicksilver-zone"
SOCIAL_DISCORD="https://discord.com/invite/xrSmYMDVrQ"
SOCIAL_X="https://twitter.com/quicksilverzone"
SOCIAL_TELEGRAM="https://t.me/quicksilverzone"

# Other
SNAPSHOT_URL="https://snapshots.noders.services/quicksilver"
GITHUB_FOLDER_NAME="auto"
VALIDATOR_URL="https://ping.pub/quicksilver/staking/quickvaloper17gwfcceyvcw53r6cclrhwk5jksmtd96xfjwrcv"

# Updates
UPDATE_MAIN=true
UPDATE_CATEGORY=true
UPDATE_INSTALL=true
UPDATE_UPGRADE=true
UPDATE_SNAPSHOT=true
UPDATE_STATESYNC=true
UPDATE_LIVE_PEERS=true
UPDATE_CLI_CHEATSHEET=true
UPDATE_ENDPOINTS=true

# Feature toggles
# Node installation
SHOW_INSTALLATION_GUIDE=true
SHOW_UPGRADE_GUIDE=true
SHOW_GENESIS=true
SHOW_CLI=true
# Endpoints and Sync
SHOW_ENDPOINTS=true
SHOW_STATE_SYNC=true
SHOW_SNAPSHOT=true
SHOW_LIVE_PEERS=true
SHOW_SEED=true
SHOW_ADDRESS_BOOK=true
# Tools
SHOW_EXPLORERS_LIST=false
SHOW_PUBLIC_ENDPOINTS=false
SHOW_USEFUL_TOOLS=false
SHOW_UPGRADE_WATCHER=false
