# App
CHAIN_NAME="Rebus"
CHAIN_SYSTEM_NAME="rebus"
CHAIN_ICON="rebus-icon.svg"
CHAIN_BACKGROUND_COLOR="#FD3FB1"

# NODERS
STAKE_URL=""
RESTAKE_URL="https://restake.app/rebus/rebusvaloper1ssvn4vrw8c40r6zgyhhxclhp36n75sulca02pl"
VALIDATOR_URL="https://rebus.explorers.guru/validator/rebusvaloper1ssvn4vrw8c40r6zgyhhxclhp36n75sulca02pl"
EXPLORER_URL=""
EXPLORER_IMAGE=""
APP_URL=""
APP_IMAGE=""
FAUCET_URL=""

# Blockchain
CHAIN_ID="auto"
CHAIN_DENOM="arebus"
CHAIN_FEES="300000000000"

# Binary
VERSION="auto"
DAEMON_NAME="rebusd"
DAEMON_SERVICE="rebusd.service"
DAEMON_HOME="~/.rebusd"

# Endpoints
ENDPOINT_RPC="https://rebus-rpc.noders.services"
ENDPOINT_API="https://rebus-api.noders.services"
ENDPOINT_JRPC="https://rebus-jsonrpc.noders.services"
ENDPOINT_GRPC="rebus-grpc.noders.services:443"
ENDPOINT_PEER="auto"
ENDPOINT_SEED="dd65dd00e3c6abf158fdac98ebdb5206f2b205e6@rebus-seed.noders.services:14033"
ENDPOINT_COSMOSLIST="https://cosmoslist.co/mainnet/rebus"

# Social
SOCIAL_WEBSITE="https://www.rebuschain.com/"
SOCIAL_GITHUB="https://github.com/rebuschain"
SOCIAL_DISCORD="https://discord.com/invite/rebuschain"
SOCIAL_X="https://twitter.com/RebusChain"
SOCIAL_TELEGRAM="https://t.me/RebusChain"

# Other
SNAPSHOT_URL="https://snapshots.noders.services/rebus"
GITHUB_FOLDER_NAME="auto"

# Updates
UPDATE_MAIN=true
UPDATE_CATEGORY=true
UPDATE_INSTALL=true
UPDATE_UPGRADE=true
UPDATE_SNAPSHOT=true
UPDATE_STATESYNC=true
UPDATE_LIVE_PEERS=true
UPDATE_CLI_CHEATSHEET=true
UPDATE_ENDPOINTS=true
UPDATE_MONITORING=true

# Feature toggles

# Node installation
SHOW_INSTALLATION_GUIDE=true
SHOW_UPGRADE_GUIDE=true
SHOW_GENESIS=true
SHOW_CLI=true

# Endpoints and Sync
SHOW_ENDPOINTS=true
SHOW_STATE_SYNC=true
SHOW_SNAPSHOT=true
SHOW_LIVE_PEERS=true
SHOW_SEED=true
SHOW_ADDRESS_BOOK=true

# Tools
SHOW_EXPLORERS_LIST=true
SHOW_PUBLIC_ENDPOINTS=false
SHOW_USEFUL_TOOLS=true
SHOW_UPGRADE_WATCHER=false

# Monitoring Configuration
MONITORING_PROMETHEUS_PORT="9090"
MONITORING_GRAFANA_PORT="3000"
MONITORING_NODE_METRICS_PORT="26661"
MONITORING_GRAFANA_PASSWORD="admin123"
MONITORING_MAX_MISSED_BLOCKS="5"
MONITORING_DASHBOARD_ID="15991"
