# App
CHAIN_NAME="Rebus"
CHAIN_SYSTEM_NAME="rebus"
CHAIN_ICON="rebus-icon.svg"
CHAIN_BACKGROUND_COLOR=""

# Blockchain
CHAIN_ID="auto"
CHAIN_DENOM="arebus"
CHAIN_FEES="300000000000"

# Binary
VERSION="auto"
DAEMON_NAME="rebusd"
DAEMON_SERVICE="rebusd.service"
DAEMON_HOME="~/.rebusd"

# Endpoints
ENDPOINT_RPC="https://rebus-rpc.noders.services"
ENDPOINT_API="https://rebus-api.noders.services"
ENDPOINT_JRPC="https://rebus-jsonrpc.noders.services"
ENDPOINT_GRPC="https://rebus-grpc.noders.services:443"
ENDPOINT_PEER="auto"
ENDPOINT_COSMOSLIST="https://cosmoslist.co/mainnet/rebus"

# Social
SOCIAL_WEBSITE="https://www.rebuschain.com/"
SOCIAL_GITHUB="https://github.com/rebuschain"
SOCIAL_DISCORD="https://discord.com/invite/rebuschain"
SOCIAL_X="https://twitter.com/RebusChain"
SOCIAL_TELEGRAM="https://t.me/RebusChain"

# Other
SNAPSHOT_URL="https://snapshots.noders.services/rebus"
GITHUB_FOLDER_NAME="auto"
VALIDATOR_URL="https://rebus.explorers.guru/validator/rebusvaloper1ssvn4vrw8c40r6zgyhhxclhp36n75sulca02pl"

# Updates
UPDATE_MAIN=true
UPDATE_CATEGORY=true
UPDATE_INSTALL=true
UPDATE_UPGRADE=true
UPDATE_SNAPSHOT=true
UPDATE_STATESYNC=true
UPDATE_LIVE_PEERS=true
UPDATE_CLI_CHEATSHEET=true
UPDATE_ENDPOINTS=true

# Feature toggles
# Node installation
SHOW_INSTALLATION_GUIDE=true
SHOW_UPGRADE_GUIDE=true
SHOW_GENESIS=true
SHOW_CLI=true
# Endpoints and Sync
SHOW_ENDPOINTS=true
SHOW_STATE_SYNC=true
SHOW_SNAPSHOT=true
SHOW_LIVE_PEERS=true
SHOW_SEED=true
SHOW_ADDRESS_BOOK=true
# Tools
SHOW_EXPLORERS_LIST=false
SHOW_PUBLIC_ENDPOINTS=false
SHOW_USEFUL_TOOLS=false
SHOW_UPGRADE_WATCHER=false
