# App
CHAIN_NAME="Router"
CHAIN_SYSTEM_NAME="router"
CHAIN_ICON="router-icon.svg"
CHAIN_BACKGROUND_COLOR="#FF3D57"

# NODERS
STAKE_URL=""
RESTAKE_URL=""
VALIDATOR_URL="https://router.explorers.guru/validator/routervaloper1wf2sev9705ujesda8rzncr60xjgvt3mjzd5kne"
EXPLORER_URL=""
EXPLORER_IMAGE=""
APP_URL=""
APP_IMAGE=""
FAUCET_URL=""

# Blockchain
CHAIN_ID="auto"
CHAIN_DENOM="route"
CHAIN_FEES="100000000000000"

# Binary
VERSION="auto"
DAEMON_NAME="routerd"
DAEMON_SERVICE="router.service"
DAEMON_HOME="~/.routerd"

# Endpoints
ENDPOINT_RPC="https://router-rpc.noders.services"
ENDPOINT_API="https://router-api.noders.services"
ENDPOINT_JRPC=""
ENDPOINT_GRPC="router-grpc.noders.services:443"
ENDPOINT_PEER="auto"
ENDPOINT_SEED="0042522fb879ae5a0f19130e82ea5244c52fd061@router-seed.noders.services:23733"
ENDPOINT_COSMOSLIST="https://cosmoslist.co/mainnet/router"

# Social
SOCIAL_WEBSITE="https://www.routerprotocol.com/"
SOCIAL_GITHUB="https://github.com/router-protocol"
SOCIAL_DISCORD="https://discord.com/invite/yjM2fUUHvN"
SOCIAL_X="https://twitter.com/routerprotocol"
SOCIAL_TELEGRAM="https://t.me/routerprotocol"

# Other
DOWNLOAD_URL="https://snapshots.noders.services/router"
GITHUB_FOLDER_NAME="auto"

# Updates
UPDATE_MAIN=true
UPDATE_CATEGORY=true
UPDATE_INSTALL=true
UPDATE_UPGRADE=true
UPDATE_SNAPSHOT=false
UPDATE_STATESYNC=true
UPDATE_LIVE_PEERS=true
UPDATE_CLI_CHEATSHEET=true
UPDATE_ENDPOINTS=true
UPDATE_MONITORING=true

# Feature toggles

# Node installation
SHOW_INSTALLATION_GUIDE=true
SHOW_UPGRADE_GUIDE=true
SHOW_GENESIS=true
SHOW_CLI=true

# Endpoints and Sync
SHOW_ENDPOINTS=true
SHOW_STATE_SYNC=true
SHOW_SNAPSHOT=true
SHOW_LIVE_PEERS=true
SHOW_SEED=true
SHOW_ADDRESS_BOOK=true

# Tools
SHOW_EXPLORERS_LIST=true
SHOW_PUBLIC_ENDPOINTS=false
SHOW_USEFUL_TOOLS=true
SHOW_UPGRADE_WATCHER=false

# Monitoring Configuration
MONITORING_PROMETHEUS_PORT="9090"
MONITORING_GRAFANA_PORT="3000"
MONITORING_NODE_METRICS_PORT="26661"
MONITORING_GRAFANA_PASSWORD="admin123"
MONITORING_MAX_MISSED_BLOCKS="5"

