# Blockchain
CHAIN_NAME="Seda"
CHAIN_SYSTEM_NAME="seda"
CHAIN_ID="auto"
VERSION="auto"
CHAIN_DESCRIPTION="""# SEDA: Simplifying Decentralized Finance

SEDA is at the forefront of the decentralized finance revolution, offering a comprehensive platform designed to democratize access to financial services. By leveraging blockchain technology, SEDA introduces a transparent, secure, and accessible ecosystem where users can engage in lending, borrowing, and trading without the need for traditional financial intermediaries.

This platform is built with the user in mind, featuring an intuitive interface that makes navigating the complexities of DeFi straightforward. SEDA's innovative protocols ensure high liquidity, low slippage, and competitive yields across a variety of digital assets.

"""
[CHAIN_DESCRIPTION_END]

CHAIN_DENOM="aseda"
CHAIN_FEES="3000000"

# Binary
DAEMON_NAME="sedad"
DAEMON_SERVICE="seda.service"
DAEMON_HOME="~/.sedad"

# Endpoints
ENDPOINT_RPC="https://seda-rpc.noders.services"
ENDPOINT_API="https://seda-api.noders.services"
ENDPOINT_JRPC=""
ENDPOINT_GRPC="http://seda-grpc.noders.services:36090"
ENDPOINT_PEER="auto"

# Social
SOCIAL_WEBSITE="https://www.seda.xyz/"
SOCIAL_GITHUB="https://github.com/sedaprotocol"
SOCIAL_DISCORD="https://discord.gg/Ae4V6y6qrW"
SOCIAL_X="https://twitter.com/sedaprotocol"
SOCIAL_TELEGRAM="https://t.me/sedaprotocol"

# Other
DOWNLOAD_URL="https://config.noders.services/seda"
GITHUB_FOLDER_NAME="auto"
VALIDATOR_LINK="https://seda.explorers.guru/validator/sedavaloper1ur9sw064p8zs793cn20y6qapaz4rsccmcjv96y"

# Updates
UPDATE_MAIN=true
UPDATE_CATEGORY=true
UPDATE_INSTALL=true
UPDATE_UPGRADE=true
UPDATE_SNAPSHOT=true
UPDATE_STATESYNC=true
UPDATE_LIVE_PEERS=true
UPDATE_CLI_CHEATSHEET=true
