# App
CHAIN_NAME="Seda"
CHAIN_SYSTEM_NAME="seda"
CHAIN_ICON="seda-icon.svg"
CHAIN_BACKGROUND_COLOR="#6100FF"

# Blockchain
CHAIN_ID="auto"
CHAIN_DENOM="aseda"
CHAIN_FEES="300000000000"

# Binary
VERSION="auto"
DAEMON_NAME="sedad"
DAEMON_SERVICE="seda.service"
DAEMON_HOME="~/.sedad"

# Endpoints
ENDPOINT_RPC="https://seda-rpc.noders.services"
ENDPOINT_API="https://seda-api.noders.services"
ENDPOINT_JRPC=""
ENDPOINT_GRPC="https://seda-grpc.noders.services:443"
ENDPOINT_PEER="auto"
ENDPOINT_COSMOSLIST="https://cosmoslist.co/mainnet/seda"

# Social
SOCIAL_WEBSITE="https://www.seda.xyz/"
SOCIAL_GITHUB="https://github.com/sedaprotocol/seda-chain"
SOCIAL_DISCORD="https://discord.gg/Ae4V6y6qrW"
SOCIAL_X="https://twitter.com/sedaprotocol"
SOCIAL_TELEGRAM="https://t.me/sedaprotocol"

# Other
SNAPSHOT_URL="https://snapshots.noders.services/seda"
GITHUB_FOLDER_NAME="auto"
VALIDATOR_URL="https://seda.explorers.guru/validator/sedavaloper1ur9sw064p8zs793cn20y6qapaz4rsccmcjv96y"

# Updates
UPDATE_MAIN=true
UPDATE_CATEGORY=true
UPDATE_INSTALL=true
UPDATE_UPGRADE=true
UPDATE_SNAPSHOT=true
UPDATE_STATESYNC=true
UPDATE_LIVE_PEERS=true
UPDATE_CLI_CHEATSHEET=true
UPDATE_ENDPOINTS=true

# Feature toggles
# Node installation
SHOW_INSTALLATION_GUIDE=true
SHOW_UPGRADE_GUIDE=true
SHOW_GENESIS=true
SHOW_CLI=true
# Endpoints and Sync
SHOW_ENDPOINTS=true
SHOW_STATE_SYNC=true
SHOW_SNAPSHOT=true
SHOW_LIVE_PEERS=true
SHOW_SEED=true
SHOW_ADDRESS_BOOK=true
# Tools
SHOW_EXPLORERS_LIST=false
SHOW_PUBLIC_ENDPOINTS=false
SHOW_USEFUL_TOOLS=false
SHOW_UPGRADE_WATCHER=false
