# App
CHAIN_NAME="Stratos"
CHAIN_SYSTEM_NAME="stratos"
CHAIN_ICON="stratos-icon.svg"
CHAIN_BACKGROUND_COLOR="#33948A"

# Blockchain
CHAIN_ID="auto"
CHAIN_DENOM="wei"
CHAIN_FEES="300000000000"

# Binary
VERSION="auto"
DAEMON_NAME="stchaind"
DAEMON_SERVICE="stchaind.service"
DAEMON_HOME="~/.stchaind"

# Endpoints
ENDPOINT_RPC="https://stratos-rpc.noders.services"
ENDPOINT_API="https://stratos-api.noders.services"
ENDPOINT_JRPC="https://stratos-jsonrpc.noders.services "
ENDPOINT_GRPC="https://stratos-grpc.noders.services:443"
ENDPOINT_PEER="auto"
ENDPOINT_COSMOSLIST="https://cosmoslist.co/mainnet/stratos"

# Social
SOCIAL_WEBSITE="https://www.thestratos.org/"
SOCIAL_GITHUB="https://github.com/stratosnet/stratos-chain"
SOCIAL_DISCORD="https://discord.gg/79dMCCyjAM"
SOCIAL_X="https://twitter.com/Stratos_Network"
SOCIAL_TELEGRAM="https://t.me/StratosOfficial"

# Other
SNAPSHOT_URL="https://snapshots.noders.services/stratos"
GITHUB_FOLDER_NAME="auto"
VALIDATOR_URL="https://explorer.thestratos.org/stratos/validators/stvaloper1ghkn8ra63422mcepdk0zzglzy6qax637g6fhzm"

# Updates
UPDATE_MAIN=true
UPDATE_CATEGORY=true
UPDATE_INSTALL=true
UPDATE_UPGRADE=true
UPDATE_SNAPSHOT=true
UPDATE_STATESYNC=true
UPDATE_LIVE_PEERS=true
UPDATE_CLI_CHEATSHEET=true
UPDATE_ENDPOINTS=true

# Feature toggles
# Node installation
SHOW_INSTALLATION_GUIDE=true
SHOW_UPGRADE_GUIDE=true
SHOW_GENESIS=true
SHOW_CLI=true
# Endpoints and Sync
SHOW_ENDPOINTS=true
SHOW_STATE_SYNC=true
SHOW_SNAPSHOT=true
SHOW_LIVE_PEERS=true
SHOW_SEED=true
SHOW_ADDRESS_BOOK=true
# Tools
SHOW_EXPLORERS_LIST=false
SHOW_PUBLIC_ENDPOINTS=false
SHOW_USEFUL_TOOLS=false
SHOW_UPGRADE_WATCHER=false
