# Blockchain
CHAIN_NAME="UX"
CHAIN_SYSTEM_NAME="umee"
CHAIN_ID="auto"
VERSION="auto"
CHAIN_DESCRIPTION="""# UX.XYZ: Elevating Blockchain Usability

UX.XYZ pioneers integrating UX design with blockchain to enhance dApp accessibility and engagement. It focuses on user-centric design, interoperability, accessibility, customizable experiences, and robust security. This initiative aims to simplify blockchain for wider adoption, impacting areas like DeFi, NFT marketplaces, decentralized social media, and e-commerce. By prioritizing user experience, UX.XYZ strives to make decentralized applications more intuitive and accessible, encouraging broader participation in the blockchain ecosystem.

Discover how UX.XYZ is reshaping blockchain usability.

"""
[CHAIN_DESCRIPTION_END]

CHAIN_DENOM="uumee"
CHAIN_FEES="20000"

# Binary
DAEMON_NAME="umeed"
DAEMON_SERVICE="umeed.service"
DAEMON_HOME="~/.umee"

# Endpoints
ENDPOINT_RPC="https://umee-rpc.noders.services"
ENDPOINT_API="https://umee-api.noders.services"
ENDPOINT_JRPC=""
ENDPOINT_GRPC="https://umee-grpc.noders.services:443"
ENDPOINT_PEER="auto"
ENDPOINT_COSMOSLIST="https://cosmoslist.co/mainnet/umee"

# Social
SOCIAL_WEBSITE="https://www.ux.xyz/"
SOCIAL_GITHUB="https://github.com/umee-network"
SOCIAL_DISCORD="https://discord.com/invite/uxchain"
SOCIAL_X="https://x.com/ux_xyz"
SOCIAL_TELEGRAM="https://t.me/uxuxchain"

# Other
SNAPSHOT_URL="https://snapshots.noders.services/umee"
GITHUB_FOLDER_NAME="auto"
VALIDATOR_URL="https://ux.explorers.guru/validator/umeevaloper1wwl9f8wcc0am9wruvmx4hjzdv7ewfcex0lz9vp"

# Updates
UPDATE_MAIN=true
UPDATE_CATEGORY=true
UPDATE_INSTALL=true
UPDATE_UPGRADE=true
UPDATE_SNAPSHOT=true
UPDATE_STATESYNC=true
UPDATE_LIVE_PEERS=true
UPDATE_CLI_CHEATSHEET=true
