# App
CHAIN_NAME="UX"
CHAIN_SYSTEM_NAME="umee"
CHAIN_ICON="umee-icon.svg"
CHAIN_BACKGROUND_COLOR=""

# Blockchain
CHAIN_ID="auto"
CHAIN_DENOM="uumee"
CHAIN_FEES="20000"

# Binary
VERSION="auto"
DAEMON_NAME="umeed"
DAEMON_SERVICE="umeed.service"
DAEMON_HOME="~/.umee"

# Endpoints
ENDPOINT_RPC="https://umee-rpc.noders.services"
ENDPOINT_API="https://umee-api.noders.services"
ENDPOINT_JRPC=""
ENDPOINT_GRPC="https://umee-grpc.noders.services:443"
ENDPOINT_PEER="auto"
ENDPOINT_COSMOSLIST="https://cosmoslist.co/mainnet/umee"

# Social
SOCIAL_WEBSITE="https://www.ux.xyz/"
SOCIAL_GITHUB="https://github.com/umee-network"
SOCIAL_DISCORD="https://discord.com/invite/uxchain"
SOCIAL_X="https://x.com/ux_xyz"
SOCIAL_TELEGRAM="https://t.me/uxuxchain"

# Other
SNAPSHOT_URL="https://snapshots.noders.services/umee"
GITHUB_FOLDER_NAME="auto"
VALIDATOR_URL="https://ux.explorers.guru/validator/umeevaloper1wwl9f8wcc0am9wruvmx4hjzdv7ewfcex0lz9vp"

# Updates
UPDATE_MAIN=true
UPDATE_CATEGORY=true
UPDATE_INSTALL=true
UPDATE_UPGRADE=true
UPDATE_SNAPSHOT=true
UPDATE_STATESYNC=true
UPDATE_LIVE_PEERS=true
UPDATE_CLI_CHEATSHEET=true

# Feature toggles
# Node installation
SHOW_INSTALLATION_GUIDE=true
SHOW_UPGRADE_GUIDE=true
SHOW_GENESIS=true
SHOW_CLI=true
# Endpoints and Sync
SHOW_ENDPOINTS=true
SHOW_STATE_SYNC=true
SHOW_SNAPSHOT=true
SHOW_LIVE_PEERS=true
SHOW_SEED=true
SHOW_ADDRESS_BOOK=true
# Tools
SHOW_EXPLORERS_LIST=false
SHOW_PUBLIC_ENDPOINTS=false
SHOW_USEFUL_TOOLS=false
SHOW_UPGRADE_WATCHER=false
