# Blockchain
CHAIN_NAME="Uptick"
CHAIN_SYSTEM_NAME="uptick"
CHAIN_ID="auto"
VERSION="auto"
CHAIN_DESCRIPTION="""# Uptick Project: Revolutionizing Digital Collectibles

The Uptick Project leverages blockchain to transform digital collectibles and NFTs, offering a secure and transparent platform for artists, creators, and collectors. Key features include a comprehensive NFT marketplace, intuitive creator tools for minting NFTs, decentralized operations for enhanced security, cross-chain functionality for broad accessibility, and a strong focus on community engagement through social features and collaboration tools. Uptick is redefining digital ownership and creativity, bridging diverse blockchain networks to enrich the digital art, gaming, and entertainment sectors.

Explore the future of digital collectibles with Uptick Project.

"""
[CHAIN_DESCRIPTION_END]

CHAIN_DENOM="auptick"
CHAIN_FEES="3000"

# Binary
DAEMON_NAME="uptickd"
DAEMON_SERVICE="uptickd.service"
DAEMON_HOME="~/.uptickd"

# Endpoints
ENDPOINT_RPC="https://uptick-rpc.noders.services"
ENDPOINT_API="https://uptick-api.noders.services"
ENDPOINT_JRPC="https://uptick-jsonrpc.noders.services"
ENDPOINT_GRPC="https://uptick-rpc.grpc.noders.services"
ENDPOINT_PEER="auto"

# Social
SOCIAL_WEBSITE="https://www.uptickproject.com/"
SOCIAL_GITHUB="https://github.com/UptickNetwork"
SOCIAL_DISCORD="https://discord.com/invite/teqX78VZUV"
SOCIAL_X="https://twitter.com/Uptickproject"
SOCIAL_TELEGRAM="https://t.me/uptickproject"

# Other
DOWNLOAD_URL="https://config.noders.services/uptick"
GITHUB_FOLDER_NAME="auto"
VALIDATOR_LINK="https://uptick.explorers.guru/validator/uptickvaloper1fl3426k0avvergm7ejzczqy6rfzxk5ma93mqwj"

# Updates
UPDATE_MAIN=true
UPDATE_CATEGORY=true
UPDATE_INSTALL=true
UPDATE_UPGRADE=true
UPDATE_SNAPSHOT=true
UPDATE_STATESYNC=true
UPDATE_LIVE_PEERS=true
UPDATE_CLI_CHEATSHEET=true
