# App
CHAIN_NAME="Uptick"
CHAIN_SYSTEM_NAME="uptick"
CHAIN_ICON="uptick-icon.svg"
CHAIN_BACKGROUND_COLOR="#7600F3"

# NODERS
STAKE_URL=""
RESTAKE_URL="https://restake.app/uptick/uptickvaloper1fl3426k0avvergm7ejzczqy6rfzxk5ma93mqwj"
VALIDATOR_URL="https://uptick.explorers.guru/validator/uptickvaloper1fl3426k0avvergm7ejzczqy6rfzxk5ma93mqwj"
EXPLORER_URL=""
EXPLORER_IMAGE=""
APP_URL=""
APP_IMAGE=""
FAUCET_URL=""

# Blockchain
CHAIN_ID="auto"
CHAIN_DENOM="auptick"
CHAIN_FEES="300000000000"

# Binary
VERSION="auto"
DAEMON_NAME="uptickd"
DAEMON_SERVICE="uptickd.service"
DAEMON_HOME="~/.uptickd"

# Endpoints
ENDPOINT_RPC="https://uptick-rpc.noders.services"
ENDPOINT_API="https://uptick-api.noders.services"
ENDPOINT_JRPC="https://uptick-jsonrpc.noders.services"
ENDPOINT_GRPC="uptick-grpc.noders.services:443"
ENDPOINT_PEER="auto"
ENDPOINT_SEED="29279e5f7339dfefd041f7fe41ad7506e957cbc7@uptick-seed.noders.services:15933"
ENDPOINT_COSMOSLIST="https://cosmoslist.co/mainnet/uptick"

# Social
SOCIAL_WEBSITE="https://www.uptickproject.com/"
SOCIAL_GITHUB="https://github.com/UptickNetwork"
SOCIAL_DISCORD="https://discord.com/invite/teqX78VZUV"
SOCIAL_X="https://twitter.com/Uptickproject"
SOCIAL_TELEGRAM="https://t.me/uptickproject"

# Other
SNAPSHOT_URL="https://snapshots.noders.services/uptick"
GITHUB_FOLDER_NAME="auto"

# Updates
UPDATE_MAIN=true
UPDATE_CATEGORY=true
UPDATE_INSTALL=true
UPDATE_UPGRADE=true
UPDATE_SNAPSHOT=true
UPDATE_STATESYNC=true
UPDATE_LIVE_PEERS=true
UPDATE_CLI_CHEATSHEET=true
UPDATE_ENDPOINTS=true

# Feature toggles
# Node installation
SHOW_INSTALLATION_GUIDE=true
SHOW_UPGRADE_GUIDE=true
SHOW_GENESIS=true
SHOW_CLI=true
# Endpoints and Sync
SHOW_ENDPOINTS=true
SHOW_STATE_SYNC=true
SHOW_SNAPSHOT=true
SHOW_LIVE_PEERS=true
SHOW_SEED=true
SHOW_ADDRESS_BOOK=true
# Tools
SHOW_EXPLORERS_LIST=false
SHOW_PUBLIC_ENDPOINTS=false
SHOW_USEFUL_TOOLS=false
SHOW_UPGRADE_WATCHER=false
