# App
CHAIN_NAME="Zetachain"
CHAIN_SYSTEM_NAME="zetachain"
CHAIN_ICON="zetachain-icon.svg"
CHAIN_BACKGROUND_COLOR="#1A563E"

# NODERS
STAKE_URL="https://wallet.keplr.app/?modal=staking&chain=zetachain_7000-1&validator_address=zetavaloper1r66jlz6qvq74apsx4r5696jkrusn5uvvvcgvn9&step_id=3&action_id=stake"
RESTAKE_URL="https://restake.app/zetachain/zetavaloper1r66jlz6qvq74apsx4r5696jkrusn5uvvvcgvn9/stake"
VALIDATOR_URL="https://zetachain.explorers.guru/validator/zetavaloper1r66jlz6qvq74apsx4r5696jkrusn5uvvvcgvn9"
EXPLORER_URL=""
EXPLORER_IMAGE="zetachain-exp.png"
APP_URL="https://zetaresources.org"
APP_IMAGE="zetachain-app.png"
FAUCET_URL=""

# Blockchain
CHAIN_ID="auto"
CHAIN_DENOM_PRETTY="ZETA"
CHAIN_DENOM="azeta"
CHAIN_FEES="300000000000"

# Binary
VERSION="auto"
DAEMON_NAME="zetacored"
DAEMON_SERVICE="zetacore.service"
DAEMON_HOME="~/.zetacored"

# Endpoints
ENDPOINT_RPC="https://zetachain-rpc.noders.services"
ENDPOINT_API="https://zetachain-api.noders.services"
ENDPOINT_JRPC="https://zetachain-jsonrpc.noders.services"
ENDPOINT_GRPC="zetachain-grpc.noders.services:443"
ENDPOINT_PEER="auto"
ENDPOINT_SEED="8589c18d322c248103a348e08bb96841b79129c5@zetachain-seed.noders.services:22533"
ENDPOINT_COSMOSLIST="https://cosmoslist.co/mainnet/zetachain"
ENDPOINT_SEED=""

# Social
SOCIAL_WEBSITE="https://www.zetachain.com/"
SOCIAL_GITHUB="https://github.com/zeta-chain"
SOCIAL_DISCORD="https://discord.gg/zetachain"
SOCIAL_X="https://twitter.com/zetablockchain"
SOCIAL_TELEGRAM="https://t.me/zetachainofficial"

# Other
SNAPSHOT_URL="https://snapshots.noders.services/zwtachain"
GITHUB_FOLDER_NAME="auto"

# Updates
UPDATE_MAIN=true
UPDATE_CATEGORY=true
UPDATE_INSTALL=true
UPDATE_UPGRADE=true
UPDATE_SNAPSHOT=true
UPDATE_STATESYNC=true
UPDATE_LIVE_PEERS=true
UPDATE_CLI_CHEATSHEET=true
UPDATE_ENDPOINTS=true
UPDATE_MONITORING=true

# Feature toggles

# Node installation
SHOW_INSTALLATION_GUIDE=true
SHOW_UPGRADE_GUIDE=true
SHOW_GENESIS=true
SHOW_CLI=true

# Endpoints and Sync
SHOW_ENDPOINTS=true
SHOW_STATE_SYNC=true
SHOW_SNAPSHOT=true
SHOW_LIVE_PEERS=true
SHOW_SEED=true
SHOW_ADDRESS_BOOK=true

# Tools
SHOW_EXPLORERS_LIST=true
SHOW_PUBLIC_ENDPOINTS=false
SHOW_USEFUL_TOOLS=true
SHOW_UPGRADE_WATCHER=false

# Monitoring Configuration
MONITORING_PROMETHEUS_PORT="9090"
MONITORING_GRAFANA_PORT="3000"
MONITORING_NODE_METRICS_PORT="26661"
MONITORING_GRAFANA_PASSWORD="admin123"
MONITORING_MAX_MISSED_BLOCKS="5"

