# App
CHAIN_NAME="Airchains"
CHAIN_SYSTEM_NAME="airchains"
CHAIN_ICON="airchains-icon.svg"
CHAIN_BACKGROUND_COLOR=""

# Blockchain
CHAIN_ID="auto"
CHAIN_DENOM="uamf"
CHAIN_FEES="20000"

# Binary
VERSION="auto"
DAEMON_NAME="junctiond"
DAEMON_SERVICE="junctiond.service"
DAEMON_HOME="~/.junction"

# Endpoints
ENDPOINT_RPC="https://airchains-t-rpc.noders.services"
ENDPOINT_API="https://airchains-t-api.noders.services"
ENDPOINT_JRPC=""
ENDPOINT_GRPC="https://airchains-t-grpc.noders.services:443"
ENDPOINT_PEER="auto"
ENDPOINT_COSMOSLIST="https://cosmoslist.co/testnet/airchains"

# Social
SOCIAL_WEBSITE="https://www.airchains.io/"
SOCIAL_GITHUB="https://github.com/airchains-network/junction"
SOCIAL_DISCORD="https://discord.gg/ERmFCQc22b"
SOCIAL_X="https://twitter.com/airchains_io"
SOCIAL_TELEGRAM=""

# Other
SNAPSHOT_URL="https://snapshots-t.noders.services/airchains"
GITHUB_FOLDER_NAME="auto"
VALIDATOR_URL="https://explorer.stavr.tech/Airchains-Testnet/staking/airvaloper1z6q26lprv70xgztfzgnfxgm7t57xh0p0hugz54"

# Updates
UPDATE_MAIN=true
UPDATE_CATEGORY=true
UPDATE_INSTALL=true
UPDATE_UPGRADE=true
UPDATE_SNAPSHOT=true
UPDATE_STATESYNC=true
UPDATE_LIVE_PEERS=true
UPDATE_CLI_CHEATSHEET=true
UPDATE_ENDPOINTS=true

# Feature toggles
# Node installation
SHOW_INSTALLATION_GUIDE=true
SHOW_UPGRADE_GUIDE=true
SHOW_GENESIS=true
SHOW_CLI=true
# Endpoints and Sync
SHOW_ENDPOINTS=true
SHOW_STATE_SYNC=true
SHOW_SNAPSHOT=true
SHOW_LIVE_PEERS=true
SHOW_SEED=true
SHOW_ADDRESS_BOOK=true
# Tools
SHOW_EXPLORERS_LIST=false
SHOW_PUBLIC_ENDPOINTS=false
SHOW_USEFUL_TOOLS=false
SHOW_UPGRADE_WATCHER=false
