# Blockchain
CHAIN_NAME="Arkeo"
CHAIN_SYSTEM_NAME="arkeo"
CHAIN_ID="auto"
VERSION="auto"
CHAIN_DESCRIPTION=""" # Arkeo

Arkeo was created to provide decentralized applications with increased development velocity, censorship-resistance, and most importantly to be a needed tool in fully decentralizing the UI layer of the web3 stack, all while reducing reliance on centralized data sources. In short, Arkeo is a free-market solution for decentralized infrastructure.

"""
[CHAIN_DESCRIPTION_END]

CHAIN_DENOM="abgt"
CHAIN_FEES="3000"

# Binary
DAEMON_NAME="arkeod"
DAEMON_SERVICE="arkeo.service"
DAEMON_HOME="~/.arkeo"

# Endpoints
ENDPOINT_RPC="https://arkeo-t-rpc.noders.services"
ENDPOINT_API="https://arkeo-t-api.noders.services"
ENDPOINT_JRPC=""
ENDPOINT_GRPC="http://arkeo-t-grpc.noders.services:31090"
ENDPOINT_PEER="auto"

# Social
SOCIAL_WEBSITE="https://arkeo.network/"
SOCIAL_GITHUB="https://github.com/arkeonetwork"
SOCIAL_DISCORD="https://discord.gg/BfEHpm6uFc"
SOCIAL_X="https://twitter.com/arkeonetwork"
SOCIAL_TELEGRAM=""

# Other
DOWNLOAD_URL="https://config-t.noders.services/arkeo"
GITHUB_FOLDER_NAME="auto"
VALIDATOR_LINK="https://testnet.arkeo.explorers.guru/validator/tarkeovaloper1hsrprv6xpfqrn2x46c4v0jxxvp4hhwrdqw483f"

# Updates
UPDATE_MAIN=true
UPDATE_CATEGORY=true
UPDATE_INSTALL=true
UPDATE_UPGRADE=true
UPDATE_SNAPSHOT=true
UPDATE_STATESYNC=true
UPDATE_LIVE_PEERS=true
UPDATE_CLI_CHEATSHEET=true
