# Blockchain
CHAIN_NAME="Artela"
CHAIN_SYSTEM_NAME="artela"
CHAIN_ID="auto"
VERSION="auto"
CHAIN_DESCRIPTION="""# Artela Network: Empowering Digital Art and Creators with Blockchain

Artela Network revolutionizes the digital art space by leveraging blockchain technology to empower artists and creators. This innovative platform offers a decentralized marketplace for digital artworks, ensuring authenticity, ownership, and provenance through secure NFTs. Artela Network enables artists to monetize their creations directly, fostering a vibrant community where art enthusiasts can discover, buy, and collect unique digital pieces. By integrating blockchain's transparency and security, Artela Network is setting a new standard for digital art, making it accessible and rewarding for creators and collectors alike.

"""
[CHAIN_DESCRIPTION_END]

CHAIN_DENOM="uart"
CHAIN_FEES="3000"

# Binary
DAEMON_NAME="artelad"
DAEMON_SERVICE="artela.service"
DAEMON_HOME="~/.artelad"

# Endpoints
ENDPOINT_RPC="https://artela-t-rpc.noders.services"
ENDPOINT_API="https://artela-t-api.noders.services"
ENDPOINT_JRPC=""
ENDPOINT_GRPC="http://artela-t-grpc.noders.services:18090"
ENDPOINT_PEER="auto"

# Social
SOCIAL_WEBSITE="https://artela.network/"
SOCIAL_GITHUB="https://github.com/artela-network"
SOCIAL_DISCORD="https://discord.com/invite/artela"
SOCIAL_X="https://twitter.com/artela_network"
SOCIAL_TELEGRAM=""

# Other
DOWNLOAD_URL="https://config-t.noders.services/artela"
GITHUB_FOLDER_NAME="auto"
VALIDATOR_LINK="https://testnet.itrocket.net/artela/staking/artvaloper1gjju20vjss6a5w0w3nz575637wg0mrw0rvqujq"

# Updates
UPDATE_MAIN=true
UPDATE_CATEGORY=true
UPDATE_INSTALL=true
UPDATE_UPGRADE=true
UPDATE_SNAPSHOT=true
UPDATE_STATESYNC=true
UPDATE_LIVE_PEERS=true
UPDATE_CLI_CHEATSHEET=true
