# App
CHAIN_NAME="Atomone"
CHAIN_SYSTEM_NAME="atomone"
CHAIN_ICON="atomone-icon.svg"
CHAIN_BACKGROUND_COLOR=""

# NODERS
STAKE_URL=""
RESTAKE_URL=""
VALIDATOR_URL=""
EXPLORER_URL=""
APP_URL=""
APP_IMAGE=""
FAUCET_URL="https://faucet.noders.services/atomone"

# Blockchain
CHAIN_ID="auto"
CHAIN_DENOM_PRETTY="ATONE"
CHAIN_DENOM="uatone"
CHAIN_FEES="20000"

# Binary
VERSION="auto"
DAEMON_NAME="atomoned"
DAEMON_SERVICE="atomone.service"
DAEMON_HOME="~/.atomone"

# Endpoints
ENDPOINT_RPC="https://atomone-t-rpc.noders.services"
ENDPOINT_API="https://atomone-t-api.noders.services"
ENDPOINT_JRPC=""
ENDPOINT_GRPC="https://atomone-t-grpc.noders.services:443"
ENDPOINT_PEER="auto"
ENDPOINT_COSMOSLIST="https://cosmoslist.co/testnet/atomone"
ENDPOINT_SEED=""

# Social
SOCIAL_WEBSITE=""
SOCIAL_GITHUB="https://github.com/atomone-hub/atomone"
SOCIAL_DISCORD="https://discord.gg/FEgcVkNYBA"
SOCIAL_X="https://x.com/_atomone"
SOCIAL_TELEGRAM=""

# Other
SNAPSHOT_URL="https://snapshots-t.noders.services/atomone"
GITHUB_FOLDER_NAME="auto"
VALIDATOR_URL="https://testnet.itrocket.net/atomone/staking/atonevaloper1ae23c50dwazpg98eafy0h8pfjhpkn7e3jqrdvg"

# Updates
UPDATE_MAIN=true
UPDATE_CATEGORY=true
UPDATE_INSTALL=true
UPDATE_UPGRADE=true
UPDATE_SNAPSHOT=true
UPDATE_STATESYNC=true
UPDATE_LIVE_PEERS=true
UPDATE_CLI_CHEATSHEET=true
UPDATE_ENDPOINTS=true

# Feature toggles
# Node installation
SHOW_INSTALLATION_GUIDE=true
SHOW_UPGRADE_GUIDE=true
SHOW_GENESIS=true
SHOW_CLI=true
# Endpoints and Sync
SHOW_ENDPOINTS=true
SHOW_STATE_SYNC=true
SHOW_SNAPSHOT=true
SHOW_LIVE_PEERS=true
SHOW_SEED=true
SHOW_ADDRESS_BOOK=true
# Tools
SHOW_EXPLORERS_LIST=false
SHOW_PUBLIC_ENDPOINTS=false
SHOW_USEFUL_TOOLS=false
SHOW_UPGRADE_WATCHER=false
