# Blockchain
CHAIN_NAME="Babylon"
CHAIN_SYSTEM_NAME="babylon"
CHAIN_ID="bbn-test-5"
VERSION="auto"
CHAIN_DESCRIPTION=""" # Babylon is building native use-cases for Bitcoin! Stake your BTC to secure decentralized networks and receive rewards—all while maintaining self-custody.

"""
[CHAIN_DESCRIPTION_END]

CHAIN_DENOM="ubbn"
CHAIN_FEES="20000"

# Binary
DAEMON_NAME="babylond"
DAEMON_SERVICE="babylon.service"
DAEMON_HOME="~/.babylond"

# Endpoints
ENDPOINT_RPC="https://babylon-t-rpc.noders.services"
ENDPOINT_API="https://babylon-t-api.noders.services"
ENDPOINT_JRPC="https://babylon-t-jsonrpc.noders.services"
ENDPOINT_GRPC=""
ENDPOINT_PEER="auto"
ENDPOINT_COSMOSLIST="https://cosmoslist.co/testnet/babylon"

# Social
SOCIAL_WEBSITE="https://babylonlabs.io/"
SOCIAL_GITHUB="https://discord.com/invite/babylonglobal"
SOCIAL_DISCORD="https://discord.com/invite/babylonglobal"
SOCIAL_X="https://x.com/babylonlabs_io"
SOCIAL_TELEGRAM="https://t.me/babyloncommunity"

# Other
SNAPSHOT_URL="https://snapshots-t.noders.services/babylon"
GITHUB_FOLDER_NAME="auto"
VALIDATOR_URL=""

# Updates
UPDATE_MAIN=true
UPDATE_CATEGORY=true
UPDATE_UPGRADE=true
UPDATE_SNAPSHOT=true
UPDATE_STATESYNC=true
UPDATE_LIVE_PEERS=true
UPDATE_CLI_CHEATSHEET=true
