# App
CHAIN_NAME="Babylon"
CHAIN_SYSTEM_NAME="babylon"
CHAIN_ICON="babylon-icon.svg"
CHAIN_BACKGROUND_COLOR=""

# Blockchain
CHAIN_ID="bbn-test-5"
CHAIN_DENOM="ubbn"
CHAIN_FEES="20000"

# Binary
VERSION="auto"
DAEMON_NAME="babylond"
DAEMON_SERVICE="babylon.service"
DAEMON_HOME="~/.babylond"

# Endpoints
ENDPOINT_RPC=""
ENDPOINT_API=""
ENDPOINT_JRPC=""
ENDPOINT_GRPC=""
ENDPOINT_PEER="auto"
ENDPOINT_COSMOSLIST="https://cosmoslist.co/testnet/babylon"

# Social
SOCIAL_WEBSITE="https://babylonlabs.io/"
SOCIAL_GITHUB="https://discord.com/invite/babylonglobal"
SOCIAL_DISCORD="https://discord.com/invite/babylonglobal"
SOCIAL_X="https://x.com/babylonlabs_io"
SOCIAL_TELEGRAM="https://t.me/babyloncommunity"

# Other
SNAPSHOT_URL="https://snapshots-t.noders.services/babylon"
GITHUB_FOLDER_NAME="auto"
VALIDATOR_URL=""

# Updates
UPDATE_MAIN=true
UPDATE_CATEGORY=true
UPDATE_UPGRADE=true
UPDATE_SNAPSHOT=true
UPDATE_STATESYNC=true
UPDATE_LIVE_PEERS=true
UPDATE_CLI_CHEATSHEET=true

# Feature toggles
# Node installation
SHOW_INSTALLATION_GUIDE=true
SHOW_UPGRADE_GUIDE=true
SHOW_GENESIS=true
SHOW_CLI=true
# Endpoints and Sync
SHOW_ENDPOINTS=true
SHOW_STATE_SYNC=true
SHOW_SNAPSHOT=true
SHOW_LIVE_PEERS=true
SHOW_SEED=true
SHOW_ADDRESS_BOOK=true
# Tools
SHOW_EXPLORERS_LIST=false
SHOW_PUBLIC_ENDPOINTS=false
SHOW_USEFUL_TOOLS=false
SHOW_UPGRADE_WATCHER=false
