# Blockchain
CHAIN_NAME="Band"
CHAIN_SYSTEM_NAME="band"
CHAIN_ID="auto"
VERSION="auto"
CHAIN_DESCRIPTION="""# Band Protocol: Powering Smart Contracts with Real-World Data

Band Protocol offers a cross-chain data oracle platform, enabling smart contracts to access real-world data and APIs efficiently. It emphasizes decentralized data governance, cross-chain compatibility, scalability, flexible oracle design, and security. Band Protocol supports a broad range of applications, including DeFi, prediction markets, and gaming, by providing timely and reliable data access, making it a critical tool for developing complex decentralized applications without relying on centralized oracles.

"""
[CHAIN_DESCRIPTION_END]

CHAIN_DENOM="uband"
CHAIN_FEES="3000"

# Binary
DAEMON_NAME="bandd"
DAEMON_SERVICE="band.service"
DAEMON_HOME="~/.band"

# Endpoints
ENDPOINT_RPC="https://band-t-rpc.noders.services"
ENDPOINT_API="https://band-t-api.noders.services"
ENDPOINT_JRPC=""
ENDPOINT_GRPC="http://band-t-grpc.noders.services:20090"
ENDPOINT_PEER="auto"

# Social
SOCIAL_WEBSITE="https://www.bandprotocol.com/"
SOCIAL_GITHUB="https://github.com/bandprotocol/chain"
SOCIAL_DISCORD="https://discord.com/invite/3t4bsY7"
SOCIAL_X="https://twitter.com/BandProtocol"
SOCIAL_TELEGRAM="https://t.me/bandprotocol"

# Other
DOWNLOAD_URL="https://config-t.noders.services/band"
GITHUB_FOLDER_NAME="auto"
VALIDATOR_LINK="https://laozi-testnet6.cosmoscan.io/validator/bandvaloper1wy08smy5xpwrm3xju7z9usnat90vvp39etv7gh#reports"

# Updates
UPDATE_MAIN=true
UPDATE_CATEGORY=true
UPDATE_INSTALL=true
UPDATE_UPGRADE=true
UPDATE_SNAPSHOT=true
UPDATE_STATESYNC=true
UPDATE_LIVE_PEERS=true
UPDATE_CLI_CHEATSHEET=true
