# Blockchain
CHAIN_NAME="BeraChain"
CHAIN_SYSTEM_NAME="berachain"
CHAIN_ID="auto"
VERSION="auto"
CHAIN_DESCRIPTION=""" (PRIVATE TESTNET) # Berachain: Bridging Traditional Finance and DeFi with Seamless Integration

Berachain is at the forefront of blending traditional financial systems with decentralized finance (DeFi), offering a seamless integration platform. It aims to remove barriers between conventional finance and the blockchain world, facilitating easy access to DeFi solutions without compromising on security or efficiency. Berachain's innovative approach ensures compliance with regulatory standards, making it a trustworthy bridge for institutions and individuals alike. By enabling smooth transactions and interoperability between diverse financial realms, Berachain is paving the way for a unified financial ecosystem that combines the best of both worlds.

"""
[CHAIN_DESCRIPTION_END]

CHAIN_DENOM="uabgt"
CHAIN_FEES="3000"

# Binary
DAEMON_NAME="berad"
DAEMON_SERVICE="bera.service"
DAEMON_HOME="~/.berad"

# Endpoints
ENDPOINT_RPC="https://berachain-t-rpc.noders.services"
ENDPOINT_API="https://berachain-t-api.noders.services"
ENDPOINT_JRPC=""
ENDPOINT_GRPC="http://berachain-t-grpc.noders.services:16090"
ENDPOINT_PEER="auto"

# Social
SOCIAL_WEBSITE="https://www.berachain.com/"
SOCIAL_GITHUB="https://github.com/berachain"
SOCIAL_DISCORD="https://discord.gg/berachain"
SOCIAL_X="https://twitter.com/berachain"
SOCIAL_TELEGRAM="https://t.me/BerachainPortal"

# Other
DOWNLOAD_URL="https://config-t.noders.services/berachain"
GITHUB_FOLDER_NAME="auto"
VALIDATOR_LINK="https://testnets.cosmosrun.info/berachain/staking/beravaloper1eclrktqt5p4waytt7u2826welyvtar297unl6s"

# Updates
UPDATE_MAIN=true
UPDATE_CATEGORY=true
UPDATE_INSTALL=false
UPDATE_UPGRADE=false
UPDATE_SNAPSHOT=true
UPDATE_STATESYNC=true
UPDATE_LIVE_PEERS=true
UPDATE_CLI_CHEATSHEET=true
