# Blockchain
CHAIN_NAME="CrossFI"
CHAIN_SYSTEM_NAME="crossfi"
CHAIN_ID="auto"
VERSION="auto"
CHAIN_DESCRIPTION="""# CrossFi: Pioneering Cross-Chain Finance for Universal Accessibility

CrossFi leverages cutting-edge blockchain technology to facilitate seamless cross-chain financial transactions, enhancing interoperability and accessibility across diverse blockchain networks. It aims to solve the prevalent issues of liquidity fragmentation and high transaction costs in decentralized finance (DeFi) by enabling efficient asset transfers and interactions between different blockchains. CrossFi's innovative approach not only broadens the scope of DeFi applications but also ensures that users enjoy a unified, cost-effective, and transparent financial ecosystem. With its commitment to removing barriers between isolated blockchain networks, CrossFi is setting new standards for a truly interconnected and inclusive digital finance landscape.

"""
[CHAIN_DESCRIPTION_END]

CHAIN_DENOM="mpx"
CHAIN_FEES="3000"

# Binary
DAEMON_NAME="crossfid"
DAEMON_SERVICE="crossfi.service"
DAEMON_HOME="~/.mineplex-chain"

# Endpoints
ENDPOINT_RPC="https://crossfi-t-rpc.noders.services"
ENDPOINT_API="https://crossfi-t-api.noders.services"
ENDPOINT_JRPC=""
ENDPOINT_GRPC="crossfi-t-grpc.noders.services:12090"
ENDPOINT_PEER="auto"

# Social
SOCIAL_WEBSITE="https://crossfi.org/"
SOCIAL_GITHUB="https://github.com/crossfichain"
SOCIAL_DISCORD="https://discord.gg/crossfi"
SOCIAL_X="https://x.com/crossfichain"
SOCIAL_TELEGRAM="https://t.me/crossfichain"

# Other
DOWNLOAD_URL="https://config-t.noders.services/crossfi"
GITHUB_FOLDER_NAME="auto"
VALIDATOR_LINK="https://coinsspor.com/crossfi/staking/mxvaloper1jep3dc0aysyzcj78mer6zps5jftm89s2fzrf7m"

# Updates
UPDATE_MAIN=true
UPDATE_CATEGORY=true
UPDATE_INSTALL=true
UPDATE_UPGRADE=true
UPDATE_SNAPSHOT=true
UPDATE_STATESYNC=true
UPDATE_LIVE_PEERS=true
UPDATE_CLI_CHEATSHEET=true
