# Blockchain
CHAIN_NAME="DoraVota"
CHAIN_SYSTEM_NAME="dora"
CHAIN_ID="auto"
VERSION="auto"
CHAIN_DESCRIPTION="""# Dora: Funding the everlasting hacker movement.

Dora Vota is the appchain supporting decentralized governance and privacy on-chain communication. Currently, the appchain is hosting major quadratic funding and MACI (Minimal Anti-collusion Infrastructure) / aMACI (anonymous MACI) rounds.

"""
[CHAIN_DESCRIPTION_END]

CHAIN_DENOM="peaka"
CHAIN_FEES="3000"

# Binary
DAEMON_NAME="dorad"
DAEMON_SERVICE="dora.service"
DAEMON_HOME="~/.dorad"

# Endpoints
ENDPOINT_RPC="https://dora-t-rpc.noders.services"
ENDPOINT_API="https://dora-t-api.noders.services"
ENDPOINT_JRPC=""
ENDPOINT_GRPC="https://dora-t-grpc.noders.services:443"
ENDPOINT_PEER="auto"
ENDPOINT_COSMOSLIST=""

# Social
SOCIAL_WEBSITE="https://dorafactory.org/"
SOCIAL_GITHUB="https://github.com/DoraFactory/doravota"
SOCIAL_DISCORD="https://discord.com/invite/gKT5DsWwQ5"
SOCIAL_X="https://twitter.com/DoraFactory"
SOCIAL_TELEGRAM=""

# Other
DOWNLOAD_URL="https://snapshots-t.noders.services/dora"
GITHUB_FOLDER_NAME="auto"
VALIDATOR_LINK="https://vota-bobtail-explorer.dorafactory.org/vota-bobtail/staking/doravaloper1zyhzwtehcs4y8pgdhz6a5aqmnaycns57vpetlc"

# Updates
UPDATE_MAIN=true
UPDATE_CATEGORY=true
UPDATE_INSTALL=true
UPDATE_UPGRADE=true
UPDATE_SNAPSHOT=true
UPDATE_STATESYNC=true
UPDATE_LIVE_PEERS=true
UPDATE_CLI_CHEATSHEET=true
