# Blockchain
CHAIN_NAME="Dymension"
CHAIN_SYSTEM_NAME="dymension"
CHAIN_ID="auto"
VERSION="auto"
CHAIN_DESCRIPTION="""# Dymension: Scaling and Interoperability for Blockchains

Dymension introduces a Layer 2 scaling solution using rollup technology to boost Layer 1 blockchains like Ethereum. It emphasizes scalability, interoperability, reduced transaction costs, enhanced security, and developer support. Ideal for high-throughput applications in DeFi, gaming, and NFTs, Dymension facilitates efficient, cost-effective transactions and cross-chain interactions, advancing the blockchain ecosystem towards greater adoption and innovation.

"""
[CHAIN_DESCRIPTION_END]

CHAIN_DENOM="adym"
CHAIN_FEES="300000000"

# Binary
DAEMON_NAME="dymd"
DAEMON_SERVICE="dymd.service"
DAEMON_HOME="~/.dymension"

# Endpoints
ENDPOINT_RPC="https://dymension-t-rpc.noders.services"
ENDPOINT_API="https://dymension-t-api.noders.services"
ENDPOINT_JRPC="https://dymension-t-jsonrpc.noders.services"
ENDPOINT_GRPC="http://dymension-t-grpc.noders.services:27090"
ENDPOINT_PEER="auto"

# Social
SOCIAL_WEBSITE="https://dymension.xyz/"
SOCIAL_GITHUB="https://github.com/dymensionxyz"
SOCIAL_DISCORD="https://discord.gg/dymension"
SOCIAL_X="https://twitter.com/dymension"
SOCIAL_TELEGRAM="https://t.me/dymensionXYZ"

# Other
DOWNLOAD_URL="https://config-t.noders.services/dymension"
GITHUB_FOLDER_NAME="auto"
VALIDATOR_LINK="https://froopyland.explorers.guru/validator/dymvaloper14jmx7s72krq87a8z5065vc0c2sgxtdnmj03pa4"

# Updates
UPDATE_MAIN=true
UPDATE_CATEGORY=true
UPDATE_INSTALL=true
UPDATE_UPGRADE=true
UPDATE_SNAPSHOT=true
UPDATE_STATESYNC=true
UPDATE_LIVE_PEERS=true
UPDATE_CLI_CHEATSHEET=true
