# App
CHAIN_NAME="Empeiria"
CHAIN_SYSTEM_NAME="empeiria"
CHAIN_ICON="empeiria-icon.svg"
CHAIN_BACKGROUND_COLOR="#890098"

# NODERS
STAKE_URL=""
RESTAKE_URL=""
VALIDATOR_URL="https://testnet.ping.pub/empe/staking/empevaloper1ghmjf5nhwqzvd7ztkrf3d5c383lmmsc9az392s"
EXPLORER_URL=""
APP_URL=""
APP_IMAGE=""
FAUCET_URL=""

# Blockchain
CHAIN_ID="auto"
CHAIN_DENOM="uempe"
CHAIN_FEES="20000"

# Binary
VERSION="auto"
DAEMON_NAME="emped"
DAEMON_SERVICE="empeiria.service"
DAEMON_HOME="~/.empe-chain"

# Endpoints
ENDPOINT_RPC="https://empeiria-t-rpc.noders.services"
ENDPOINT_API="https://empeiria-t-api.noders.services"
ENDPOINT_JRPC=""
ENDPOINT_GRPC="empeiria-t-grpc.noders.services:443"
ENDPOINT_PEER="auto"
ENDPOINT_SEED="dd0628195b94fca40ae287333244da00561a3471@empeiria-t-seed.noders.services:11233"
ENDPOINT_COSMOSLIST="https://cosmoslist.co/testnet/empeiria"

# Social
SOCIAL_WEBSITE="https://empe.io/"
SOCIAL_GITHUB="https://github.com/empe-io"
SOCIAL_DISCORD=""
SOCIAL_X="https://twitter.com/empe_io"
SOCIAL_TELEGRAM="https://t.me/web3Empeiria"

# Other
SNAPSHOT_URL="https://snapshots-t.noders.services/empeiria"
GITHUB_FOLDER_NAME="auto"

# Updates
UPDATE_MAIN=true
UPDATE_CATEGORY=true
UPDATE_INSTALL=true
UPDATE_UPGRADE=true
UPDATE_SNAPSHOT=true
UPDATE_STATESYNC=true
UPDATE_LIVE_PEERS=true
UPDATE_CLI_CHEATSHEET=true
UPDATE_ENDPOINTS=true

# Feature toggles
# Node installation
SHOW_INSTALLATION_GUIDE=true
SHOW_UPGRADE_GUIDE=true
SHOW_GENESIS=true
SHOW_CLI=true
# Endpoints and Sync
SHOW_ENDPOINTS=true
SHOW_STATE_SYNC=true
SHOW_SNAPSHOT=true
SHOW_LIVE_PEERS=true
SHOW_SEED=true
SHOW_ADDRESS_BOOK=true
# Tools
SHOW_EXPLORERS_LIST=true
SHOW_PUBLIC_ENDPOINTS=false
SHOW_USEFUL_TOOLS=true
SHOW_UPGRADE_WATCHER=false
