# Blockchain
CHAIN_NAME="Entrypoint"
CHAIN_SYSTEM_NAME="entrypoint"
CHAIN_ID="auto"
VERSION="auto"
CHAIN_DESCRIPTION=""" (PRIVATE TESTNET) # EntryPoint: Bridging the Gap in Blockchain Accessibility

EntryPoint revolutionizes the way users interact with blockchain ecosystems by providing a seamless, user-friendly portal for accessing decentralized applications (dApps) and services. It aims to simplify the blockchain experience, making it more accessible to a broader audience, from crypto enthusiasts to newcomers. By integrating various blockchain networks, EntryPoint offers a unified interface that enables easy transactions, asset management, and cross-chain interoperability. Its platform is designed to support a wide range of blockchain functionalities, including DeFi, NFTs, and more, ensuring users have a one-stop solution for their decentralized needs. With security, scalability, and user experience at its core, EntryPoint is set to become a cornerstone in the blockchain community, fostering adoption and innovation.

"""
[CHAIN_DESCRIPTION_END]

CHAIN_DENOM="uentry"
CHAIN_FEES="3000"

# Binary
DAEMON_NAME="entrypointd"
DAEMON_SERVICE="entrypoint.service"
DAEMON_HOME="~/.entrypoint"

# Endpoints
ENDPOINT_RPC="https://entrypoint-t-rpc.noders.services"
ENDPOINT_API="https://entrypoint-t-api.noders.services"
ENDPOINT_JRPC=""
ENDPOINT_GRPC="http://entrypoint-t-grpc.noders.services:15090"
ENDPOINT_PEER="auto"

# Social
SOCIAL_WEBSITE="https://entrypoint.zone/"
SOCIAL_GITHUB="https://github.com/entrypoint-zone"
SOCIAL_DISCORD="https://discord.gg/6Ec9jDwVnB"
SOCIAL_X="https://twitter.com/entrypointzone"
SOCIAL_TELEGRAM="https://t.me/entrypointzone"

# Other
DOWNLOAD_URL="https://config-t.noders.services/entrypoint"
GITHUB_FOLDER_NAME="auto"
VALIDATOR_LINK="https://explorer.stavr.tech/Entrypoint-Testnet/staking/entrypointvaloper1qadn0mcaf4sk02c44zfkkknkn2k3dys7hqcl7g"

# Updates
UPDATE_MAIN=true
UPDATE_CATEGORY=true
UPDATE_INSTALL=true
UPDATE_UPGRADE=true
UPDATE_SNAPSHOT=true
UPDATE_STATESYNC=true
UPDATE_LIVE_PEERS=true
UPDATE_CLI_CHEATSHEET=true
