# App
CHAIN_NAME="Galactica"
CHAIN_SYSTEM_NAME="galactica"
CHAIN_ICON="galactica-icon.svg"
CHAIN_BACKGROUND_COLOR="#E87C59"

# NODERS
STAKE_URL=""
RESTAKE_URL=""
VALIDATOR_URL="https://testnet.itrocket.net/galactica/staking/galavaloper1p0gs5uq44usv2fnx0qcw785jj2ey76svjtlgx7"
EXPLORER_URL=""
APP_URL=""
APP_IMAGE=""
FAUCET_URL=""

# Blockchain
CHAIN_ID="auto"
CHAIN_DENOM="agnet"
CHAIN_FEES="300000000000"

# Binary
VERSION="auto"
DAEMON_NAME="galacticad"
DAEMON_SERVICE="galactica.service"
DAEMON_HOME="~/.galactica"

# Endpoints
ENDPOINT_RPC="https://galactica-t-rpc.noders.services"
ENDPOINT_API="https://galactica-t-api.noders.services"
ENDPOINT_JRPC="https://galactica-t-json.noders.services"
ENDPOINT_GRPC="galactica-t-grpc.noders.services:443"
ENDPOINT_PEER="auto"
ENDPOINT_SEED="7a74b01d4baa10ae4722d28aaeb6bc422466451f@galactica-t-seed.noders.services:27433"
ENDPOINT_COSMOSLIST="https://cosmoslist.co/testnet/galactica"

# Social
SOCIAL_WEBSITE="https://galactica.com/"
SOCIAL_GITHUB="https://github.com/Galactica-corp/networks"
SOCIAL_DISCORD="https://discord.gg/galactica"
SOCIAL_X="https://twitter.com/GalacticaNet"
SOCIAL_TELEGRAM="https://t.me/TheCypherState"

# Other
SNAPSHOT_URL="https://snapshots-t.noders.services/galactica"
GITHUB_FOLDER_NAME="auto"

# Updates
UPDATE_MAIN=true
UPDATE_CATEGORY=true
UPDATE_INSTALL=true
UPDATE_UPGRADE=true
UPDATE_SNAPSHOT=true
UPDATE_STATESYNC=true
UPDATE_LIVE_PEERS=true
UPDATE_CLI_CHEATSHEET=true
UPDATE_ENDPOINTS=true
UPDATE_MONITORING=true

# Feature toggles

# Node installation
SHOW_INSTALLATION_GUIDE=true
SHOW_UPGRADE_GUIDE=true
SHOW_GENESIS=true
SHOW_CLI=true

# Endpoints and Sync
SHOW_ENDPOINTS=true
SHOW_STATE_SYNC=true
SHOW_SNAPSHOT=true
SHOW_LIVE_PEERS=true
SHOW_SEED=true
SHOW_ADDRESS_BOOK=true

# Tools
SHOW_EXPLORERS_LIST=true
SHOW_PUBLIC_ENDPOINTS=false
SHOW_USEFUL_TOOLS=true
SHOW_UPGRADE_WATCHER=false
SHOW_MONITORING=true

# Monitoring Configuration
MONITORING_PROMETHEUS_PORT="9090"
MONITORING_GRAFANA_PORT="3000"
MONITORING_NODE_METRICS_PORT="26661"
MONITORING_GRAFANA_PASSWORD="admin123"
MONITORING_MAX_MISSED_BLOCKS="5"
MONITORING_DASHBOARD_ID="15991"
