# Blockchain
CHAIN_NAME="Galactica"
CHAIN_SYSTEM_NAME="galactica"
CHAIN_ID="auto"
VERSION="auto"
CHAIN_DESCRIPTION="""# Galactica: We need to solve Identity, Compliance & Privacy

Galactica Network presents itself as a pioneering platform in the Web3 space, aiming to establish the first on-chain nation-state. It's focused on fostering Sybil-resistant, reputation-based systems and decentralized societies (DeSoc), enhancing DeFi and DAOs for a more accountable and compliant future. Galactica emphasizes a community-driven approach, seeking builders to create a better future through innovative DeFi solutions, DAO structures, and a comprehensive DeSoc stack

"""
[CHAIN_DESCRIPTION_END]

CHAIN_DENOM="agnet"
CHAIN_FEES="300000"

# Binary
DAEMON_NAME="galacticad"
DAEMON_SERVICE="galactica.service"
DAEMON_HOME="~/.galactica"

# Endpoints
ENDPOINT_RPC="https://galactica-t-rpc.noders.services"
ENDPOINT_API="https://galactica-t-api.noders.services"
ENDPOINT_JRPC="https://galactica-t-json.noders.services"
ENDPOINT_GRPC="https://galactica-t-grpc.noders.services"
ENDPOINT_PEER="auto"

# Social
SOCIAL_WEBSITE="https://galactica.com/"
SOCIAL_GITHUB="https://github.com/Galactica-corp/networks"
SOCIAL_DISCORD="https://discord.gg/galactica"
SOCIAL_X="https://twitter.com/GalacticaNet"
SOCIAL_TELEGRAM="https://t.me/TheCypherState"

# Other
DOWNLOAD_URL="https://config-t.noders.services/galactica"
GITHUB_FOLDER_NAME="auto"
VALIDATOR_LINK="https://ping.pfc.zone/galactica-testnet/staking/galavaloper1p0gs5uq44usv2fnx0qcw785jj2ey76svjtlgx7"

# Updates
UPDATE_MAIN=true
UPDATE_CATEGORY=true
UPDATE_INSTALL=true
UPDATE_UPGRADE=true
UPDATE_SNAPSHOT=true
UPDATE_STATESYNC=true
UPDATE_LIVE_PEERS=true
UPDATE_CLI_CHEATSHEET=true
