# Blockchain
CHAIN_NAME="Initia"
CHAIN_SYSTEM_NAME="initia"
CHAIN_ID="auto"
VERSION="auto"
CHAIN_DESCRIPTION="""# Initia: Is a network

Initia is a cutting-edge network for interwoven rollups, creating a highly integrated system of modular networks. It combines architectural ownership of the Layer 1 (L1) orchestration layer, Layer 2 (L2) network, and communication protocol to achieve universal consistency. The project aims to enhance scalability, security, and interoperability within the blockchain ecosystem, offering a robust platform for decentralized applications and services.

"""
[CHAIN_DESCRIPTION_END]

CHAIN_DENOM="uinit"
CHAIN_FEES="3000"

# Binary
DAEMON_NAME="initiad"
DAEMON_SERVICE="initiad.service"
DAEMON_HOME="~/.initia"

# Endpoints
ENDPOINT_RPC="https://initia-t-rpc.noders.services"
ENDPOINT_API="https://initia-t-api.noders.services"
ENDPOINT_JRPC=""
ENDPOINT_GRPC="http://initia-t-grpc.noders.services:32090"
ENDPOINT_PEER="auto"

# Social
SOCIAL_WEBSITE="https://initia.xyz/"
SOCIAL_GITHUB="https://github.com/initia-labs/initia"
SOCIAL_DISCORD="https://discord.com/invite/initia"
SOCIAL_X="https://twitter.com/initiaFDN"
SOCIAL_TELEGRAM=""

# Other
DOWNLOAD_URL="https://config-t.noders.services/initia"
GITHUB_FOLDER_NAME="auto"
VALIDATOR_LINK="https://app.testnet.initia.xyz/validator/initvaloper18m5xwp0mgq840sq0udutjpax7ngyymgx4ux903"

# Updates
UPDATE_MAIN=true
UPDATE_CATEGORY=true
UPDATE_INSTALL=true
UPDATE_UPGRADE=true
UPDATE_SNAPSHOT=true
UPDATE_STATESYNC=true
UPDATE_LIVE_PEERS=true
UPDATE_CLI_CHEATSHEET=true
