# Blockchain
CHAIN_NAME="Jackal"
CHAIN_SYSTEM_NAME="jackal"
CHAIN_ID="auto"
VERSION_HAND="canary-17-gb6ed8056"
VERSION="auto"
CHAIN_DESCRIPTION="""# Jackal Protocol: Pioneering Decentralized Data Storage

Jackal Protocol introduces a decentralized file storage solution, enhancing security, efficiency, and cost-effectiveness. It emphasizes privacy, data sovereignty, and global access, decentralizing storage across numerous nodes for enhanced security and redundancy. Features include advanced encryption for privacy, reduced costs by utilizing unused storage space, scalability, and interoperability with various blockchain networks. Jackal Protocol supports a wide range of applications, including secure data backup, decentralized web hosting, and content delivery, marking a significant shift towards a more secure, user-controlled internet.

Explore Jackal Protocol's vision for a decentralized web.

"""
[CHAIN_DESCRIPTION_END]

CHAIN_DENOM="ujckl"
CHAIN_FEES="3000"

# Binary
DAEMON_NAME="canined"
DAEMON_SERVICE="canined.service"
DAEMON_HOME="~/.canine"

# Endpoints
ENDPOINT_RPC="https://jackal-t-rpc.noders.services"
ENDPOINT_API="https://jackal-t-api.noders.services"
ENDPOINT_JRPC=""
ENDPOINT_GRPC="jackal-t-grpc.noders.services:14090"
ENDPOINT_PEER="auto"

# Social
SOCIAL_WEBSITE="https://www.jackalprotocol.com/"
SOCIAL_GITHUB="https://github.com/JackalLabs/canine-chain"
SOCIAL_DISCORD="https://discord.com/invite/5GKym3p6rj"
SOCIAL_X="https://twitter.com/Jackal_Protocol"
SOCIAL_TELEGRAM="https://t.me/+rtuZnbTlHaIzNjVh"

# Other
DOWNLOAD_URL="https://config-t.noders.services/jackal"
GITHUB_FOLDER_NAME="auto"
VALIDATOR_LINK="https://explorer.bccnodes.com/jackal-T/staking/jklvaloper132k95jan8ju92jtmkzr49vnusv5xvwvju27kpq"

# Updates
UPDATE_MAIN=true
UPDATE_CATEGORY=true
UPDATE_INSTALL=true
UPDATE_UPGRADE=true
UPDATE_SNAPSHOT=true
UPDATE_STATESYNC=true
UPDATE_LIVE_PEERS=true
UPDATE_CLI_CHEATSHEET=true
