# Blockchain
CHAIN_NAME="Kopi"
CHAIN_SYSTEM_NAME="kopi"
CHAIN_ID="auto"
VERSION="auto"
CHAIN_DESCRIPTION=""" # Kopi

Kopi is the latest project in DeFi and offers a decentralized exchange as well as its own supply managed coins (kCoins).

"""
[CHAIN_DESCRIPTION_END]

CHAIN_DENOM="abgt"
CHAIN_FEES="3000"

# Binary
DAEMON_NAME="uxkp"
DAEMON_SERVICE="kopi.service"
DAEMON_HOME="~/.kopid"

# Endpoints
ENDPOINT_RPC="https://kopi-t-rpc.noders.services"
ENDPOINT_API="https://kopi-t-api.noders.services"
ENDPOINT_JRPC=""
ENDPOINT_GRPC="http://kopi-t-grpc.noders.services:27690"
ENDPOINT_PEER="auto"

# Social
SOCIAL_WEBSITE="https://kopi.money/"
SOCIAL_GITHUB="https://github.com/kopi-money/kopi"
SOCIAL_DISCORD="https://discord.gg/GvnwSwsCcs"
SOCIAL_X="https://twitter.com/kopi_money/"
SOCIAL_TELEGRAM="https://t.me/+_hk--L9mKKc4MThk"

# Other
DOWNLOAD_URL="https://config-t.noders.services/kopi"
GITHUB_FOLDER_NAME="auto"
VALIDATOR_LINK="https://explorer.kopi.money/kopi-test-4/staking/kopivaloper1en8f3y0wx52npwmxw2jy2qghy2acar55w9h39d"

# Updates
UPDATE_MAIN=true
UPDATE_CATEGORY=true
UPDATE_INSTALL=true
UPDATE_UPGRADE=true
UPDATE_SNAPSHOT=true
UPDATE_STATESYNC=true
UPDATE_LIVE_PEERS=true
UPDATE_CLI_CHEATSHEET=true
