# App
CHAIN_NAME="Lava"
CHAIN_SYSTEM_NAME="lava"
CHAIN_ICON="lava-icon.svg"
CHAIN_BACKGROUND_COLOR="#D7001F"

# Blockchain
CHAIN_ID="auto"
CHAIN_DENOM="ulava"
CHAIN_FEES="20000"

# Binary
VERSION="auto"
DAEMON_NAME="lavad"
DAEMON_SERVICE="lava.service"
DAEMON_HOME="~/.lava"

# Endpoints
ENDPOINT_RPC="https://lava-t-rpc.noders.services"
ENDPOINT_API="https://lava-t-api.noders.services"
ENDPOINT_JRPC=""
ENDPOINT_GRPC="https://lava-t-grpc.noders.services:443"
ENDPOINT_PEER="auto"
ENDPOINT_COSMOSLIST="https://cosmoslist.co/testnet/lava"

# Social
SOCIAL_WEBSITE="https://www.lavanet.xyz/"
SOCIAL_GITHUB="https://github.com/lavanet"
SOCIAL_DISCORD="https://discord.gg/Tbk5NxTCdA"
SOCIAL_X="https://twitter.com/lavanetxyz"
SOCIAL_TELEGRAM=""

# Other
SNAPSHOT_URL="https://snapshots-t.noders.services/lava"
GITHUB_FOLDER_NAME="auto"
VALIDATOR_URL="https://explorer.kjnodes.com/lava-testnet/staking/lava@valoper1tkhehvca5uur6svd2l83lp704mlhc7xu32r2j4"

# Updates
UPDATE_MAIN=true
UPDATE_CATEGORY=true
UPDATE_INSTALL=true
UPDATE_UPGRADE=true
UPDATE_SNAPSHOT=true
UPDATE_STATESYNC=true
UPDATE_LIVE_PEERS=true
UPDATE_CLI_CHEATSHEET=true
UPDATE_ENDPOINTS=true

# Feature toggles
# Node installation
SHOW_INSTALLATION_GUIDE=true
SHOW_UPGRADE_GUIDE=true
SHOW_GENESIS=true
SHOW_CLI=true
# Endpoints and Sync
SHOW_ENDPOINTS=true
SHOW_STATE_SYNC=true
SHOW_SNAPSHOT=true
SHOW_LIVE_PEERS=true
SHOW_SEED=true
SHOW_ADDRESS_BOOK=true
# Tools
SHOW_EXPLORERS_LIST=false
SHOW_PUBLIC_ENDPOINTS=false
SHOW_USEFUL_TOOLS=false
SHOW_UPGRADE_WATCHER=false
