# Blockchain
CHAIN_NAME="Nillion"
CHAIN_SYSTEM_NAME="nillion"
CHAIN_ID="auto"
VERSION="auto"
CHAIN_DESCRIPTION="""# Nillion

Nillion is a decentralized privacy-preserving computation network that enables secure data processing and storage without exposing sensitive information.

"""
[CHAIN_DESCRIPTION_END]

CHAIN_DENOM="unil"
CHAIN_FEES="3000"

# Binary
DAEMON_NAME="nilliond"
DAEMON_SERVICE="nillion.service"
DAEMON_HOME="~/.nilliond"

# Endpoints
ENDPOINT_RPC="https://nillion-t-rpc.noders.services"
ENDPOINT_API="https://nillion-t-api.noders.services"
ENDPOINT_JRPC=""
ENDPOINT_GRPC="http://nillion-t-grpc.noders.services:26690"
ENDPOINT_PEER="auto"
ENDPOINT_COSMOSLIST="https://cosmoslist.co/testnet/nillion"

# Social
SOCIAL_WEBSITE="https://nillion.com"
SOCIAL_GITHUB="https://github.com/NillionNetwork"
SOCIAL_DISCORD="https://discord.com/invite/nillionnetwork"
SOCIAL_X="https://x.com/nillionnetwork"
SOCIAL_TELEGRAM="https://t.me/nillionnetwork"

# Other
DOWNLOAD_URL="https://config.noders.services/nillion"
GITHUB_FOLDER_NAME="auto"
VALIDATOR_LINK="https://testnet.nillion.explorers.guru/validator/nillionvaloper1zuuwwg7234uz7jz2ammnymsmztym4ytdfczztq"

# Updates
UPDATE_MAIN=true
UPDATE_CATEGORY=true
UPDATE_INSTALL=true
UPDATE_UPGRADE=true
UPDATE_SNAPSHOT=true
UPDATE_STATESYNC=true
UPDATE_LIVE_PEERS=true
UPDATE_CLI_CHEATSHEET=true 
