# App
CHAIN_NAME="Nillion"
CHAIN_SYSTEM_NAME="nillion"
CHAIN_ICON="nillion-icon.svg"
CHAIN_BACKGROUND_COLOR="#0000FE"

# NODERS
STAKE_URL=""
RESTAKE_URL=""
VALIDATOR_URL="https://testnet.nillion.explorers.guru/validator/nillionvaloper1zuuwwg7234uz7jz2ammnymsmztym4ytdfczztq"
EXPLORER_URL=""
APP_URL="https://nillionhub.org"
APP_IMAGE="nillion-app.png"
FAUCET_URL="https://faucet.noders.services/nillion"

# Blockchain
CHAIN_ID="auto"
CHAIN_DENOM="unil"
CHAIN_FEES="20000"

# Binary
VERSION="auto"
CHAIN_DENOM_PRETTY="NIL"
DAEMON_NAME="nilliond"
DAEMON_SERVICE="nillion.service"
DAEMON_HOME="~/.nilliond"

# Endpoints
ENDPOINT_RPC="https://nillion-t-rpc.noders.services"
ENDPOINT_API="https://nillion-t-api.noders.services"
ENDPOINT_JRPC=""
ENDPOINT_GRPC="nillion-t-grpc.noders.services:443"
ENDPOINT_PEER="auto"
ENDPOINT_COSMOSLIST="https://cosmoslist.co/testnet/nillion"
ENDPOINT_SEED="7004b5ab387d27ba449b07a19a0a3af431bebb3d@nillion-t-seed.noders.services:29856"

# Social
SOCIAL_WEBSITE="https://nillion.com"
SOCIAL_GITHUB="https://github.com/NillionNetwork"
SOCIAL_DISCORD="https://discord.com/invite/nillionnetwork"
SOCIAL_X="https://x.com/nillionnetwork"
SOCIAL_TELEGRAM="https://t.me/nillionnetwork"

# Other
SNAPSHOT_URL="https://snapshots-t.noders.services/nillion"
GITHUB_FOLDER_NAME="auto"

# Updates
UPDATE_MAIN=true
UPDATE_CATEGORY=true
UPDATE_INSTALL=true
UPDATE_UPGRADE=true
UPDATE_SNAPSHOT=true
UPDATE_STATESYNC=true
UPDATE_LIVE_PEERS=true
UPDATE_CLI_CHEATSHEET=true
UPDATE_ENDPOINTS=true

# Feature toggles
# Node installation
SHOW_INSTALLATION_GUIDE=true
SHOW_UPGRADE_GUIDE=true
SHOW_GENESIS=true
SHOW_CLI=true
# Endpoints and Sync
SHOW_ENDPOINTS=true
SHOW_STATE_SYNC=true
SHOW_SNAPSHOT=true
SHOW_LIVE_PEERS=true
SHOW_SEED=true
SHOW_ADDRESS_BOOK=true
# Tools
SHOW_EXPLORERS_LIST=true
SHOW_PUBLIC_ENDPOINTS=false
SHOW_USEFUL_TOOLS=true
SHOW_UPGRADE_WATCHER=false
