# App
CHAIN_NAME="ZeroGravity"
CHAIN_SYSTEM_NAME="og"
CHAIN_ICON="og-icon.svg"
CHAIN_BACKGROUND_COLOR="#dc6bbd"

# NODERS
STAKE_URL=""
RESTAKE_URL=""
VALIDATOR_URL=""
EXPLORER_URL="https://0ghub.org/explorer"
EXPLORER_IMAGE="og-exp.png"
APP_URL="https://0ghub.org/"
APP_IMAGE="og-app.png"
FAUCET_URL=""

# Blockchain
CHAIN_ID="auto"
CHAIN_DENOM_PRETTY="A0GI"
CHAIN_DENOM="ua0gi"
CHAIN_FEES="20000"

# Binary
VERSION="auto"
DAEMON_NAME="0gchaind"
DAEMON_SERVICE="og.service"
DAEMON_HOME="~/.0gchain"

# Endpoints
ENDPOINT_RPC="https://og-t-rpc.noders.services"
ENDPOINT_API="https://og-t-api.noders.services"
ENDPOINT_JRPC="https://og-t-json.noders.services"
ENDPOINT_GRPC="og-t-grpc.noders.services:443"
ENDPOINT_PEER="auto"
ENDPOINT_COSMOSLIST="https://cosmoslist.co/testnet/og"
ENDPOINT_SEED=""

# Social
SOCIAL_WEBSITE="https://0g.ai/"
SOCIAL_GITHUB="https://github.com/0glabs/0g-chain"
SOCIAL_DISCORD="http://discord.gg/0glabs"
SOCIAL_X="https://twitter.com/0G_labs"
SOCIAL_TELEGRAM="https://t.me/web3_0glabs"

# Other
SNAPSHOT_URL="https://snapshots-t.noders.services/og"
GITHUB_FOLDER_NAME="auto"
VALIDATOR_URL="https://testnet.0g.explorers.guru/validator/0gvaloper1w24g8xczpxuy5y87lwv0dyq9n27mlyul3xf2zk"

# Updates
UPDATE_MAIN=true
UPDATE_CATEGORY=true
UPDATE_INSTALL=true
UPDATE_UPGRADE=true
UPDATE_SNAPSHOT=true
UPDATE_STATESYNC=true
UPDATE_LIVE_PEERS=true
UPDATE_CLI_CHEATSHEET=true
UPDATE_ENDPOINTS=true

# Feature toggles
# Node installation
SHOW_INSTALLATION_GUIDE=true
SHOW_UPGRADE_GUIDE=true
SHOW_GENESIS=true
SHOW_CLI=true
# Endpoints and Sync
SHOW_ENDPOINTS=true
SHOW_STATE_SYNC=true
SHOW_SNAPSHOT=true
SHOW_LIVE_PEERS=true
SHOW_SEED=true
SHOW_ADDRESS_BOOK=true
# Tools
SHOW_EXPLORERS_LIST=false
SHOW_PUBLIC_ENDPOINTS=false
SHOW_USEFUL_TOOLS=false
SHOW_UPGRADE_WATCHER=false
