# Blockchain
CHAIN_NAME="ZeroGravity"
CHAIN_SYSTEM_NAME="og"
CHAIN_ID="auto"
VERSION="auto"
CHAIN_DESCRIPTION=""" # ZeroGravity: the first data availability system with a built-in general purpose storage layer that is super scalable and decentralized.

The scalability of 0G hinges on the idea of separating the workflow of data availability into data publishing lane and data storage lane. Large volume of data transfers happen on the data storage lane that is supported by the storage layer which achieves the horizontal scalability through well designed partitioning, while the data publishing lane guarantees the data availability property through consensus of data availability sampling which only requires tiny data flowing through the consensus protocol to avoid the broadcasting bottleneck. Data storage is an integral part of data availability because it must answer the question of where the data is published.

"""
[CHAIN_DESCRIPTION_END]

CHAIN_DENOM="ua0gi"
CHAIN_FEES="3000"

# Binary
DAEMON_NAME="0gchaind"
DAEMON_HOME="~/.0gchain"

# Endpoints
ENDPOINT_RPC="https://og-t-rpc.noders.services"
ENDPOINT_API="https://og-t-api.noders.services"
ENDPOINT_JRPC="https://og-t-json.noders.services"
ENDPOINT_GRPC="http://og-t-grpc.noders.services:29090"
ENDPOINT_PEER="auto"

# Social
SOCIAL_WEBSITE="https://0g.ai/"
SOCIAL_GITHUB="https://github.com/0glabs/0g-chain"
SOCIAL_DISCORD="http://discord.gg/0glabs"
SOCIAL_X="https://twitter.com/0G_labs"
SOCIAL_TELEGRAM="https://t.me/web3_0glabs"

# Other
DOWNLOAD_URL="https://config-t.noders.services/og"
GITHUB_FOLDER_NAME="auto"
VALIDATOR_LINK="https://explorer.validatorvn.com/OG-Testnet/staking/evmosvaloper1n30zgt2nc3auawqlsgkqmwz9u3r0zdwnu9xjc4"

# Updates
UPDATE_MAIN=true
UPDATE_CATEGORY=true
UPDATE_INSTALL=true
UPDATE_UPGRADE=true
UPDATE_SNAPSHOT=true
UPDATE_STATESYNC=true
UPDATE_LIVE_PEERS=true
UPDATE_CLI_CHEATSHEET=true
