# Blockchain
CHAIN_NAME="Pell"
CHAIN_SYSTEM_NAME="pell"
CHAIN_ID="auto"
VERSION="auto"
CHAIN_DESCRIPTION="""# Pell ｜ BTC Restaking

The First & Omnichain BTC Restaking Network, extending BTCFi into the cryptoeconomic security domain and fully unlocking Bitcoin's potential.

"""
[CHAIN_DESCRIPTION_END]

CHAIN_DENOM="apell"
CHAIN_FEES="300000000000"

# Binary
DAEMON_NAME="pellcored"
DAEMON_SERVICE="pell.service"
DAEMON_HOME="~/.pellcored"

# Endpoints
ENDPOINT_RPC="https://pell-t-rpc.noders.services"
ENDPOINT_API="https://pell-t-api.noders.services"
ENDPOINT_JRPC=""
ENDPOINT_GRPC="https://pell-t-grpc.noders.services:443"
ENDPOINT_PEER="auto"
ENDPOINT_COSMOSLIST="https://cosmoslist.co/testnet/pell"

# Social
SOCIAL_WEBSITE="https://pell.network/"
SOCIAL_GITHUB="https://github.com/0xPellNetwork"
SOCIAL_DISCORD="https://discord.com/invite/pell-network"
SOCIAL_X="https://x.com/Pell_Network"
SOCIAL_TELEGRAM="https://t.me/pellnetwork_chat"

# Other
SNAPSHOT_URL="https://snapshots-t.noders.services/pell"
GITHUB_FOLDER_NAME="auto"
VALIDATOR_URL="https://testnet.pell.explorers.guru/validator/pellvaloper1qkvwaakuf2expvp22kys5z9p8jt9c3dxfjwk0z"

# Updates
UPDATE_MAIN=true
UPDATE_CATEGORY=true
UPDATE_INSTALL=true
UPDATE_UPGRADE=true
UPDATE_SNAPSHOT=true
UPDATE_STATESYNC=true
UPDATE_LIVE_PEERS=true
UPDATE_CLI_CHEATSHEET=true
