# App
CHAIN_NAME="Pell"
CHAIN_SYSTEM_NAME="pell"
CHAIN_ICON="pell-icon.svg"
CHAIN_BACKGROUND_COLOR="#4C67EF"

# NODERS
STAKE_URL=""
RESTAKE_URL=""
VALIDATOR_URL="https://testnet.pell.explorers.guru/validator/pellvaloper1qkvwaakuf2expvp22kys5z9p8jt9c3dxfjwk0z"
EXPLORER_URL=""
APP_URL=""
APP_IMAGE=""
FAUCET_URL=""

# Blockchain
CHAIN_ID="auto"
CHAIN_DENOM="apell"
CHAIN_FEES="300000000000"

# Binary
VERSION="auto"
DAEMON_NAME="pellcored"
DAEMON_SERVICE="pell.service"
DAEMON_HOME="~/.pellcored"

# Endpoints
ENDPOINT_RPC="https://pell-t-rpc.noders.services"
ENDPOINT_API="https://pell-t-api.noders.services"
ENDPOINT_JRPC=""
ENDPOINT_GRPC="pell-t-grpc.noders.services:443"
ENDPOINT_PEER="auto"
ENDPOINT_SEED="fd6dc2772f6965b3e45f945fcad61153e7f1ac34@pell-t-seed.noders.services:47933"
ENDPOINT_COSMOSLIST="https://cosmoslist.co/testnet/pell"

# Social
SOCIAL_WEBSITE="https://pell.network/"
SOCIAL_GITHUB="https://github.com/0xPellNetwork"
SOCIAL_DISCORD="https://discord.com/invite/pell-network"
SOCIAL_X="https://x.com/Pell_Network"
SOCIAL_TELEGRAM="https://t.me/pellnetwork_chat"

# Other
SNAPSHOT_URL="https://snapshots-t.noders.services/pell"
GITHUB_FOLDER_NAME="auto"

# Updates
UPDATE_MAIN=true
UPDATE_CATEGORY=true
UPDATE_INSTALL=true
UPDATE_UPGRADE=true
UPDATE_SNAPSHOT=true
UPDATE_STATESYNC=true
UPDATE_LIVE_PEERS=true
UPDATE_CLI_CHEATSHEET=true
UPDATE_ENDPOINTS=true

# Feature toggles
# Node installation
SHOW_INSTALLATION_GUIDE=true
SHOW_UPGRADE_GUIDE=true
SHOW_GENESIS=true
SHOW_CLI=true
# Endpoints and Sync
SHOW_ENDPOINTS=true
SHOW_STATE_SYNC=true
SHOW_SNAPSHOT=true
SHOW_LIVE_PEERS=true
SHOW_SEED=true
SHOW_ADDRESS_BOOK=true
# Tools
SHOW_EXPLORERS_LIST=true
SHOW_PUBLIC_ENDPOINTS=false
SHOW_USEFUL_TOOLS=true
SHOW_UPGRADE_WATCHER=false
