# Blockchain
CHAIN_NAME="Pryzm"
CHAIN_SYSTEM_NAME="pryzm"
CHAIN_ID="auto"
VERSION="auto"
CHAIN_DESCRIPTION="""# Pryzm: Unleashing the Power of Decentralized Identities

Pryzm is revolutionizing the digital world by providing a secure and decentralized identity management platform. It empowers users with self-sovereign identities, enabling them to control their personal data and digital footprints. By harnessing blockchain technology, Pryzm ensures unmatched security, privacy, and interoperability across various applications and services. This platform facilitates seamless authentication, verification, and data exchange processes, eliminating the need for centralized identity repositories. Pryzm is paving the way for a future where digital interactions are more authentic, private, and user-controlled, fostering trust and efficiency in the digital ecosystem.

"""
[CHAIN_DESCRIPTION_END]

CHAIN_DENOM="upryzm"
CHAIN_FEES="3000"

# Binary
DAEMON_NAME="pryzmd"
DAEMON_SERVICE="pryzm.service"
DAEMON_HOME="~/.pryzm"

# Endpoints
ENDPOINT_RPC="https://pryzm-t-rpc.noders.services"
ENDPOINT_API="https://pryzm-t-api.noders.services"
ENDPOINT_JRPC=""
ENDPOINT_GRPC="https://pryzm-t-grpc.noders.services"
ENDPOINT_PEER="auto"

# Social
SOCIAL_WEBSITE="https://pryzm.zone/"
SOCIAL_GITHUB="https://github.com/pryzm-finance"
SOCIAL_DISCORD="https://discord.gg/mx4kjVG7zN"
SOCIAL_X="https://twitter.com/pryzm_zone"
SOCIAL_TELEGRAM="https://t.me/+uB3fAFC56KIzZDVk"

# Other
DOWNLOAD_URL="https://config-t.noders.services/pryzm"
GITHUB_FOLDER_NAME="auto"
VALIDATOR_LINK="https://explorer.stavr.tech/Pryzm-Testnet/staking/pryzmvaloper1xsuy3ca9z630chuajrrf7au8pn6yymn3ar0qtr"

# Updates
UPDATE_MAIN=true
UPDATE_CATEGORY=true
UPDATE_INSTALL=true
UPDATE_UPGRADE=true
UPDATE_SNAPSHOT=true
UPDATE_STATESYNC=true
UPDATE_LIVE_PEERS=true
UPDATE_CLI_CHEATSHEET=true
