# Blockchain
CHAIN_NAME="Rrouter"
CHAIN_SYSTEM_NAME="router"
CHAIN_ID="auto"
VERSION_HAND="v1.0.0-rc1"
VERSION="auto"
CHAIN_DESCRIPTION="""# Router Protocol: Bridging the Gap in Multi-Chain Connectivity

Router Protocol is at the forefront of enabling seamless interoperability across diverse blockchain networks. By developing a cutting-edge infrastructure, Router Protocol facilitates the transfer of information and assets between otherwise isolated blockchains, fostering a more connected and efficient decentralized ecosystem. This innovative platform addresses the critical challenge of interoperability, allowing for enhanced liquidity, greater accessibility, and expanded functionalities across the crypto space. Router Protocol's commitment to breaking down barriers between blockchains paves the way for a truly interconnected digital asset environment.

"""
[CHAIN_DESCRIPTION_END]

CHAIN_DENOM="uroute"
CHAIN_FEES="3000"

# Binary
DAEMON_NAME="routerd"
DAEMON_SERVICE="router.service"
DAEMON_HOME="~/.routerd"

# Endpoints
ENDPOINT_RPC="https://router-t-rpc.noders.services"
ENDPOINT_API="https://router-t-api.noders.services"
ENDPOINT_JRPC=""
ENDPOINT_GRPC="router-t-grpc.noders.services:22090"
ENDPOINT_PEER="auto"

# Social
SOCIAL_WEBSITE="https://www.routerprotocol.com/"
SOCIAL_GITHUB="https://github.com/router-protocol"
SOCIAL_DISCORD="https://discord.gg/rKf9UYMNWC"
SOCIAL_X="https://twitter.com/routerprotocol?t=Jab_H522Y2fB6uM60Pn6zA&s=09"
SOCIAL_TELEGRAM="https://t.me/routerprotocol"

# Other
DOWNLOAD_URL="https://config-t.noders.services/router"
GITHUB_FOLDER_NAME="auto"
VALIDATOR_LINK="https://testnet.router.explorers.guru/validator/routervaloper1fa8vxy29r3uuex3m3zp8taw7j37006npneg6nc"

# Updates
UPDATE_MAIN=true
UPDATE_CATEGORY=true
UPDATE_INSTALL=true
UPDATE_UPGRADE=true
UPDATE_SNAPSHOT=true
UPDATE_STATESYNC=true
UPDATE_LIVE_PEERS=true
UPDATE_CLI_CHEATSHEET=true
