# App
CHAIN_NAME="Seda"
CHAIN_SYSTEM_NAME="seda"
CHAIN_ICON="seda-icon.svg"
CHAIN_BACKGROUND_COLOR="#6100FF"

# NODERS
STAKE_URL=""
RESTAKE_URL=""
VALIDATOR_URL="https://testnet.seda.explorers.guru/validator/sedavaloper1ws3x9g0e7sx7zaxvtmtjmrdz2fgttr0x57csd9"
EXPLORER_URL=""
APP_URL=""
APP_IMAGE=""
FAUCET_URL=""

# Blockchain
CHAIN_ID="auto"
CHAIN_DENOM="aseda"
CHAIN_FEES="300000000000"

# Binary
VERSION="auto"
DAEMON_NAME="sedad"
DAEMON_SERVICE="seda.service"
DAEMON_HOME="~/.sedad"

# Endpoints
ENDPOINT_RPC="https://seda-t-rpc.noders.services"
ENDPOINT_API="https://seda-t-api.noders.services"
ENDPOINT_JRPC=""
ENDPOINT_GRPC="seda-t-grpc.noders.services:443"
ENDPOINT_PEER="auto"
ENDPOINT_SEED="16e910fb75f1d8f616ddfad945bc9a714d1c0b57@seda-t-seed.noders.services:25833"
ENDPOINT_COSMOSLIST="https://cosmoslist.co/testnet/seda"

# Social
SOCIAL_WEBSITE="https://www.seda.xyz/"
SOCIAL_GITHUB="https://github.com/sedaprotocol/seda-chain"
SOCIAL_DISCORD="https://discord.gg/Ae4V6y6qrW"
SOCIAL_X="https://twitter.com/sedaprotocol"
SOCIAL_TELEGRAM="https://t.me/sedaprotocol"

# Other
SNAPSHOT_URL="https://snapshots-t.noders.services/seda"
GITHUB_FOLDER_NAME="auto"

# Updates
UPDATE_MAIN=true
UPDATE_CATEGORY=true
UPDATE_INSTALL=true
UPDATE_UPGRADE=true
UPDATE_SNAPSHOT=true
UPDATE_STATESYNC=true
UPDATE_LIVE_PEERS=true
UPDATE_CLI_CHEATSHEET=true
UPDATE_ENDPOINTS=true
UPDATE_MONITORING=true

# Feature toggles
# Node installation
SHOW_INSTALLATION_GUIDE=true
SHOW_UPGRADE_GUIDE=true
SHOW_GENESIS=true
SHOW_CLI=true
# Endpoints and Sync
SHOW_ENDPOINTS=true
SHOW_STATE_SYNC=true
SHOW_SNAPSHOT=true
SHOW_LIVE_PEERS=true
SHOW_SEED=true
SHOW_ADDRESS_BOOK=true
# Tools
SHOW_EXPLORERS_LIST=true
SHOW_PUBLIC_ENDPOINTS=false
SHOW_USEFUL_TOOLS=false
SHOW_UPGRADE_WATCHER=false
# Monitoring Configuration
MONITORING_PROMETHEUS_PORT="9090"
MONITORING_GRAFANA_PORT="3000"
MONITORING_NODE_METRICS_PORT="26660"
MONITORING_GRAFANA_PASSWORD="admin123"
MONITORING_MAX_MISSED_BLOCKS="5"
MONITORING_DASHBOARD_ID="15991"
