# App
CHAIN_NAME="Side"
CHAIN_SYSTEM_NAME="side"
CHAIN_ICON="side-icon.svg"
CHAIN_BACKGROUND_COLOR="#EC7926"

# NODERS
STAKE_URL=""
RESTAKE_URL=""
VALIDATOR_URL="https://testnet.side.explorers.guru/validator/sidevaloper1qqfquysyqstp5qq8rsfqypgxq5zs7pc2r5tsv8cezc93gycrpywp22zkf48"
EXPLORER_URL=""
APP_URL=""
APP_IMAGE=""
FAUCET_URL=""

# Blockchain
CHAIN_ID="auto"
CHAIN_DENOM="uside"
CHAIN_FEES="20000"

# Binary
VERSION="auto"
DAEMON_NAME="sided"
DAEMON_SERVICE="sided.service"
DAEMON_HOME="~/.side"

# Endpoints
ENDPOINT_RPC="https://side-t-rpc.noders.services"
ENDPOINT_API="https://side-t-api.noders.services"
ENDPOINT_JRPC=""
ENDPOINT_GRPC="side-t-grpc.noders.services:443"
ENDPOINT_PEER="auto"
ENDPOINT_SEED="9ce6c59a4a3d2a7c6c0780ebc0403316e5cdaec4@side-t-seed.noders.services:26333"
ENDPOINT_COSMOSLIST="https://cosmoslist.co/testnet/side"

# Social
SOCIAL_WEBSITE="https://side.one/"
SOCIAL_GITHUB="https://github.com/sideprotocol"
SOCIAL_DISCORD="https://discord.gg/sideprotocol"
SOCIAL_X="https://twitter.com/SideProtocol"
SOCIAL_TELEGRAM="https://t.me/SideProtocolOfficial"

# Other
SNAPSHOT_URL="https://snapshots-t.noders.services/side"
GITHUB_FOLDER_NAME="auto"

# Updates
UPDATE_MAIN=true
UPDATE_CATEGORY=true
UPDATE_INSTALL=true
UPDATE_UPGRADE=true
UPDATE_SNAPSHOT=true
UPDATE_STATESYNC=true
UPDATE_LIVE_PEERS=true
UPDATE_CLI_CHEATSHEET=true
UPDATE_ENDPOINTS=true

# Feature toggles
# Node installation
SHOW_INSTALLATION_GUIDE=true
SHOW_UPGRADE_GUIDE=true
SHOW_GENESIS=true
SHOW_CLI=true
# Endpoints and Sync
SHOW_ENDPOINTS=true
SHOW_STATE_SYNC=true
SHOW_SNAPSHOT=true
SHOW_LIVE_PEERS=true
SHOW_SEED=true
SHOW_ADDRESS_BOOK=true
# Tools
SHOW_EXPLORERS_LIST=false
SHOW_PUBLIC_ENDPOINTS=false
SHOW_USEFUL_TOOLS=false
SHOW_UPGRADE_WATCHER=false
