# Blockchain
CHAIN_NAME="Side"
CHAIN_SYSTEM_NAME="side"
CHAIN_ID="auto"
VERSION="auto"
CHAIN_DESCRIPTION="""# Side Protocol: Revolutionizing Web3 Exchanges

Side Protocol emerges as a pivotal exchange layer for Web3, aiming to redefine decentralized finance (DeFi) by ensuring secure, transparent, and efficient cryptocurrency transactions. Embracing user-centric and developer-friendly approaches, it offers a robust platform that simplifies DeFi integration and usage. Through its commitment to innovation and reliability, Side Protocol is set to empower the digital asset space, facilitating a seamless exchange experience across the Web3 ecosystem.

"""
[CHAIN_DESCRIPTION_END]

CHAIN_DENOM="uside"
CHAIN_FEES="20000"

# Binary
DAEMON_NAME="sided"
DAEMON_SERVICE="sided.service"
DAEMON_HOME="~/.side"

# Endpoints
ENDPOINT_RPC="https://side-t-rpc.noders.services"
ENDPOINT_API="https://side-t-api.noders.services"
ENDPOINT_JRPC=""
ENDPOINT_GRPC="https://side-t-grpc.noders.services:443"
ENDPOINT_PEER="auto"
ENDPOINT_COSMOSLIST="https://cosmoslist.co/testnet/side"

# Social
SOCIAL_WEBSITE="https://side.one/"
SOCIAL_GITHUB="https://github.com/sideprotocol"
SOCIAL_DISCORD="https://discord.gg/sideprotocol"
SOCIAL_X="https://twitter.com/SideProtocol"
SOCIAL_TELEGRAM="https://t.me/SideProtocolOfficial"

# Other
SNAPSHOT_URL="https://snapshots-t.noders.services/side"
GITHUB_FOLDER_NAME="auto"
VALIDATOR_URL="https://testnet.side.explorers.guru/validator/sidevaloper1qqfquysyqstp5qq8rsfqypgxq5zs7pc2r5tsv8cezc93gycrpywp22zkf48"

# Updates
UPDATE_MAIN=true
UPDATE_CATEGORY=true
UPDATE_INSTALL=true
UPDATE_UPGRADE=true
UPDATE_SNAPSHOT=true
UPDATE_STATESYNC=true
UPDATE_LIVE_PEERS=true
UPDATE_CLI_CHEATSHEET=true

# Feature toggles
# Node installation
SHOW_INSTALLATION_GUIDE=true
SHOW_UPGRADE_GUIDE=true
SHOW_GENESIS=true
SHOW_CLI=true
# Endpoints and Sync
SHOW_ENDPOINTS=true
SHOW_STATE_SYNC=true
SHOW_SNAPSHOT=true
SHOW_LIVE_PEERS=true
SHOW_SEED=true
SHOW_ADDRESS_BOOK=true
# Tools
SHOW_EXPLORERS_LIST=false
SHOW_PUBLIC_ENDPOINTS=false
SHOW_USEFUL_TOOLS=false
SHOW_UPGRADE_WATCHER=false
