# App
CHAIN_NAME="Story"
CHAIN_SYSTEM_NAME="story"
CHAIN_ICON="story-icon.svg"
CHAIN_BACKGROUND_COLOR="#EEE9EA"

# NODERS
STAKE_URL=""
RESTAKE_URL=""
VALIDATOR_URL="https://aeneid.storyscan.app/validators/storyvaloper17kry8akmlwxraf75j5esjal05ltd797dqa0kj5"
EXPLORER_URL="https://ipstoryhub.org/explorer"
APP_URL="https://ipstoryhub.org"
APP_IMAGE="story-app.png"
FAUCET_URL=""

# Blockchain
CHAIN_ID="devnet-1"
CHAIN_DENOM_PRETTY="IP"
CHAIN_DENOM="aip"
CHAIN_FEES="300000000000"

# Binary
VERSION="v1.1.0"
DAEMON_NAME="story"
DAEMON_SERVICE="story.service"
DAEMON_HOME="~/.story"

# Endpoints
ENDPOINT_RPC="https://story-t-rpc.noders.services"
ENDPOINT_API="https://story-t-api.noders.services"
ENDPOINT_JRPC="https://story-t-jsonrpc.noders.services"
ENDPOINT_GRPC=""
ENDPOINT_PEER="auto"
ENDPOINT_COSMOSLIST="https://cosmoslist.co/testnet/story"
ENDPOINT_SEED=""

# Social
SOCIAL_WEBSITE="https://www.story.foundation/"
SOCIAL_GITHUB="https://github.com/piplabs/story"
SOCIAL_DISCORD="https://discord.gg/storyprotocol"
SOCIAL_X="https://x.com/StoryProtocol"
SOCIAL_TELEGRAM=""

# Other
SNAPSHOT_URL="https://snapshots-t.noders.services/story"
GITHUB_FOLDER_NAME="auto"

# Updates
UPDATE_MAIN=true
UPDATE_CATEGORY=true
UPDATE_INSTALL=false
UPDATE_UPGRADE=true
UPDATE_SNAPSHOT=true
UPDATE_STATESYNC=true
UPDATE_LIVE_PEERS=true
UPDATE_CLI_CHEATSHEET=true
UPDATE_ENDPOINTS=true

# Feature toggles
# Node installation
SHOW_INSTALLATION_GUIDE=true
SHOW_UPGRADE_GUIDE=true
SHOW_GENESIS=true
SHOW_CLI=true
# Endpoints and Sync
SHOW_ENDPOINTS=true
SHOW_STATE_SYNC=true
SHOW_SNAPSHOT=true
SHOW_LIVE_PEERS=true
SHOW_SEED=true
SHOW_ADDRESS_BOOK=true
# Tools
SHOW_EXPLORERS_LIST=false
SHOW_PUBLIC_ENDPOINTS=false
SHOW_USEFUL_TOOLS=false
SHOW_UPGRADE_WATCHER=false
