# Blockchain
CHAIN_NAME="Story"
CHAIN_SYSTEM_NAME="story"
CHAIN_ID="devnet-1"
VERSION="v1.1.0"
CHAIN_DESCRIPTION=""" # Story Protocol

Story is the World’s IP Blockchain, onramping Programmable IP to power the next generation of AI, DeFi, and consumer applications.

"""
[CHAIN_DESCRIPTION_END]

CHAIN_DENOM="aip"
CHAIN_FEES="300000000000"

# Binary
DAEMON_NAME="story"
DAEMON_SERVICE="story.service"
DAEMON_HOME="~/.story"

# Endpoints
ENDPOINT_RPC="https://story-t-rpc.noders.services"
ENDPOINT_API="https://story-t-api.noders.services"
ENDPOINT_JRPC="https://story-t-jsonrpc.noders.services"
ENDPOINT_GRPC=""
ENDPOINT_PEER="auto"
ENDPOINT_COSMOSLIST="https://cosmoslist.co/testnet/story"

# Social
SOCIAL_WEBSITE="https://www.story.foundation/"
SOCIAL_GITHUB="https://github.com/piplabs/story"
SOCIAL_DISCORD="https://discord.gg/storyprotocol"
SOCIAL_X="https://x.com/StoryProtocol"
SOCIAL_TELEGRAM=""

# Other
DOWNLOAD_URL="https://snapshots-t.noders.services/story"
GITHUB_FOLDER_NAME="auto"
VALIDATOR_LINK=""

# Updates
UPDATE_MAIN=true
UPDATE_CATEGORY=true
UPDATE_INSTALL=false
UPDATE_UPGRADE=true
UPDATE_SNAPSHOT=true
UPDATE_STATESYNC=true
UPDATE_LIVE_PEERS=true
UPDATE_CLI_CHEATSHEET=true
