# App
CHAIN_NAME="Swisstronik"
CHAIN_SYSTEM_NAME="swisstronik"
CHAIN_ICON="swisstronik-icon.svg"
CHAIN_BACKGROUND_COLOR=""

# Blockchain
CHAIN_ID="auto"
CHAIN_DENOM="uswtr"
CHAIN_FEES="20000"

# Binary
VERSION="auto"
DAEMON_NAME="swisstronikd"
DAEMON_SERVICE="swisstronik.service"
DAEMON_HOME="~/.swisstronik"

# Endpoints
ENDPOINT_RPC="https://swisstronik-t-rpc.noders.services"
ENDPOINT_API="https://swisstronik-t-api.noders.services"
ENDPOINT_JRPC=""
ENDPOINT_GRPC="https://swisstronik-t-grpc.noders.services:443"
ENDPOINT_PEER="auto"
ENDPOINT_COSMOSLIST="https://cosmoslist.co/testnet/swisstronik"

# Social
SOCIAL_WEBSITE="https://www.swisstronik.com/"
SOCIAL_GITHUB="https://github.com/SigmaGmbH"
SOCIAL_DISCORD="https://link.swisstronik.com/a46c36"
SOCIAL_X="https://twitter.com/swisstronik"
SOCIAL_TELEGRAM="https://t.me/swisstronik"

# Other
SNAPSHOT_URL=""
GITHUB_FOLDER_NAME="auto"
VALIDATOR_URL="https://explorer-cosmos.testnet.swisstronik.com/swisstronik/staking/swtrvaloper1jxptedfkfa0dea7zdu238290xxhm2nk6nat2tt"

# Updates
UPDATE_MAIN=true
UPDATE_CATEGORY=true
UPDATE_INSTALL=true
UPDATE_UPGRADE=true
UPDATE_SNAPSHOT=true
UPDATE_STATESYNC=true
UPDATE_LIVE_PEERS=true
UPDATE_CLI_CHEATSHEET=true

# Feature toggles
# Node installation
SHOW_INSTALLATION_GUIDE=true
SHOW_UPGRADE_GUIDE=true
SHOW_GENESIS=true
SHOW_CLI=true
# Endpoints and Sync
SHOW_ENDPOINTS=true
SHOW_STATE_SYNC=true
SHOW_SNAPSHOT=true
SHOW_LIVE_PEERS=true
SHOW_SEED=true
SHOW_ADDRESS_BOOK=true
# Tools
SHOW_EXPLORERS_LIST=false
SHOW_PUBLIC_ENDPOINTS=false
SHOW_USEFUL_TOOLS=false
SHOW_UPGRADE_WATCHER=false
