# Blockchain
CHAIN_NAME="Swisstronik"
CHAIN_SYSTEM_NAME="swisstronik"
CHAIN_ID="auto"
VERSION="auto"
CHAIN_DESCRIPTION="""# Swisstronik: Pioneering the Fusion of Electronics and Blockchain

Swisstronik emerges as a trailblazer at the intersection of electronics and blockchain technology, offering innovative solutions that redefine security, transparency, and efficiency in electronic transactions and operations. By harmoniously integrating cutting-edge electronic technologies with the immutable security of blockchain, Swisstronik is setting new standards for the digital era, ensuring that every transaction and operation benefits from unparalleled security and reliability. This pioneering approach not only enhances the functionality and trustworthiness of electronic systems but also opens up new avenues for the application of blockchain technology in the electronics industry.

"""
[CHAIN_DESCRIPTION_END]

CHAIN_DENOM="uswtr"
CHAIN_FEES="20000"

# Binary
DAEMON_NAME="swisstronikd"
DAEMON_SERVICE="swisstronik.service"
DAEMON_HOME="~/.swisstronik"

# Endpoints
ENDPOINT_RPC="https://swisstronik-t-rpc.noders.services"
ENDPOINT_API="https://swisstronik-t-api.noders.services"
ENDPOINT_JRPC=""
ENDPOINT_GRPC="https://swisstronik-t-grpc.noders.services:443"
ENDPOINT_PEER="auto"
ENDPOINT_COSMOSLIST="https://cosmoslist.co/testnet/swisstronik"

# Social
SOCIAL_WEBSITE="https://www.swisstronik.com/"
SOCIAL_GITHUB="https://github.com/SigmaGmbH"
SOCIAL_DISCORD="https://link.swisstronik.com/a46c36"
SOCIAL_X="https://twitter.com/swisstronik"
SOCIAL_TELEGRAM="https://t.me/swisstronik"

# Other
DOWNLOAD_URL=""
GITHUB_FOLDER_NAME="auto"
VALIDATOR_LINK="https://explorer-cosmos.testnet.swisstronik.com/swisstronik/staking/swtrvaloper1jxptedfkfa0dea7zdu238290xxhm2nk6nat2tt"

# Updates
UPDATE_MAIN=true
UPDATE_CATEGORY=true
UPDATE_INSTALL=true
UPDATE_UPGRADE=true
UPDATE_SNAPSHOT=true
UPDATE_STATESYNC=true
UPDATE_LIVE_PEERS=true
UPDATE_CLI_CHEATSHEET=true
