# App
CHAIN_NAME="Union"
CHAIN_SYSTEM_NAME="union"
CHAIN_ICON="union-icon.svg"
CHAIN_BACKGROUND_COLOR="#ACEBFC"

# NODERS
STAKE_URL=""
RESTAKE_URL=""
VALIDATOR_URL="https://explorer.testnet-9.union.build/union/staking/unionvaloper1qk3g5r2spp9t3a28ek0ken6k62rwyyxay6tl93"
EXPLORER_URL=""
APP_URL=""
APP_IMAGE=""
FAUCET_URL=""

# Blockchain
VERSION_HAND="v0.19.0"
CHAIN_ID="auto"
CHAIN_DENOM="muno"
CHAIN_FEES="20000"

# Binary
VERSION="auto"
DAEMON_NAME="uniond"
DAEMON_SERVICE="union.service"
DAEMON_HOME="~/.union"

# Endpoints
ENDPOINT_RPC="https://union-t-rpc.noders.services"
ENDPOINT_API="https://union-t-api.noders.services"
ENDPOINT_JRPC=""
ENDPOINT_GRPC="union-t-grpc.noders.services:443"
ENDPOINT_PEER="auto"
ENDPOINT_SEED="357169c26433e173698a017f61c892129a6c0f8d@union-t-seed.noders.services:24633"
ENDPOINT_COSMOSLIST="https://cosmoslist.co/testnet/union"

# Social
SOCIAL_WEBSITE="https://union.build/"
SOCIAL_GITHUB="https://github.com/unionlabs"
SOCIAL_DISCORD="https://discord.union.build/"
SOCIAL_X="https://x.com/union_build"
SOCIAL_TELEGRAM=""

# Other
SNAPSHOT_URL="https://snapshots-t.noders.services/union"
GITHUB_FOLDER_NAME="auto"

# Updates
UPDATE_MAIN=true
UPDATE_CATEGORY=true
UPDATE_INSTALL=false
UPDATE_UPGRADE=false
UPDATE_SNAPSHOT=true
UPDATE_STATESYNC=true
UPDATE_LIVE_PEERS=true
UPDATE_CLI_CHEATSHEET=true
UPDATE_ENDPOINTS=true
UPDATE_MONITORING=true

# Feature toggles

# Node installation
SHOW_INSTALLATION_GUIDE=true
SHOW_UPGRADE_GUIDE=true
SHOW_GENESIS=true
SHOW_CLI=true

# Endpoints and Sync
SHOW_ENDPOINTS=true
SHOW_STATE_SYNC=true
SHOW_SNAPSHOT=true
SHOW_LIVE_PEERS=true
SHOW_SEED=true
SHOW_ADDRESS_BOOK=true

# Tools
SHOW_EXPLORERS_LIST=true
SHOW_PUBLIC_ENDPOINTS=false
SHOW_USEFUL_TOOLS=true
SHOW_UPGRADE_WATCHER=false
SHOW_MONITORING=true

# Monitoring Configuration
MONITORING_PROMETHEUS_PORT="9090"
MONITORING_GRAFANA_PORT="3000"
MONITORING_NODE_METRICS_PORT="26661"
MONITORING_GRAFANA_PASSWORD="admin123"
MONITORING_MAX_MISSED_BLOCKS="5"
MONITORING_DASHBOARD_ID="15991"
