# Blockchain
CHAIN_NAME="Union"
CHAIN_SYSTEM_NAME="union"
VERSION_HAND="v0.19.0"
CHAIN_ID="auto"
VERSION="auto"
CHAIN_DESCRIPTION=""" (PRIVATE TESTNET) # Union: Building Bridges in DeFi Ecosystems

Union is poised to transform the decentralized finance landscape by introducing a comprehensive platform designed to enhance connectivity, security, and functionality across various DeFi ecosystems. By leveraging cutting-edge blockchain technology, Union aims to provide a unified framework that addresses the current challenges of interoperability, liquidity, and user experience in DeFi. The platform offers a suite of tools and services, including cross-chain asset swaps, integrated liquidity pools, and advanced security protocols, to empower users and developers alike. Union's mission is to foster a more accessible, efficient, and inclusive financial system by connecting disparate blockchain networks and enabling seamless interaction among diverse DeFi applications.

"""
[CHAIN_DESCRIPTION_END]

CHAIN_DENOM="muno"
CHAIN_FEES="3000"

# Binary
DAEMON_NAME="uniond"
DAEMON_SERVICE="union.service"
DAEMON_HOME="~/.union"

# Endpoints
ENDPOINT_RPC="https://union-t-rpc.noders.services"
ENDPOINT_API="https://union-t-api.noders.services"
ENDPOINT_JRPC=""
ENDPOINT_GRPC="http://union-t-grpc.noders.services:11090"
ENDPOINT_PEER="auto"

# Social
SOCIAL_WEBSITE="https://union.build/"
SOCIAL_GITHUB="https://github.com/unionlabs"
SOCIAL_DISCORD="https://discord.union.build/"
SOCIAL_X="https://x.com/union_build"
SOCIAL_TELEGRAM=""

# Other
DOWNLOAD_URL="https://config-t.noders.services/union"
GITHUB_FOLDER_NAME="auto"
VALIDATOR_LINK="https://testnet.union.explorers.guru/validator/unionvaloper1qk3g5r2spp9t3a28ek0ken6k62rwyyxay6tl93"

# Updates
UPDATE_MAIN=true
UPDATE_CATEGORY=true
UPDATE_INSTALL=false
UPDATE_UPGRADE=false
UPDATE_SNAPSHOT=true
UPDATE_STATESYNC=true
UPDATE_LIVE_PEERS=true
UPDATE_CLI_CHEATSHEET=true
