# Blockchain
CHAIN_NAME="Warden"
CHAIN_SYSTEM_NAME="warden"
CHAIN_ID="auto"
VERSION="auto"
CHAIN_DESCRIPTION="""# Warden Protocol: Enhancing Security in DeFi

Warden Protocol stands as a beacon of innovation in the decentralized finance (DeFi) landscape, focusing on bolstering security measures for blockchain transactions and smart contracts. Aimed at mitigating the risks associated with DeFi operations, Warden Protocol introduces a suite of security tools and services designed to protect users and developers from vulnerabilities, hacks, and financial losses.

"""
[CHAIN_DESCRIPTION_END]

CHAIN_DENOM="uward"
CHAIN_FEES="20000"

# Binary
DAEMON_NAME="wardend"
DAEMON_SERVICE="warden.service"
DAEMON_HOME="~/.warden"

# Endpoints
ENDPOINT_RPC="https://warden-t-rpc.noders.services"
ENDPOINT_API="https://warden-t-api.noders.services"
ENDPOINT_JRPC=""
ENDPOINT_GRPC="https://warden-t-grpc.noders.services:443"
ENDPOINT_PEER="auto"
ENDPOINT_COSMOSLIST="https://cosmoslist.co/testnet/warden"

# Social
SOCIAL_WEBSITE="https://wardenprotocol.org/"
SOCIAL_GITHUB="https://github.com/warden-protocol/wardenprotocol"
SOCIAL_DISCORD="https://discord.gg/wardenprotocol"
SOCIAL_X="https://x.com/wardenprotocol"
SOCIAL_TELEGRAM="https://t.me/wardenprotocol"

# Other
DOWNLOAD_URL="https://snapshots-t.noders.services/warden"
GITHUB_FOLDER_NAME="auto"
VALIDATOR_LINK="https://testnet.warden.explorers.guru/validator/wardenvaloper1nun82ve6x07rhd0vda25acnalea70m28trfp4j"

# Updates
UPDATE_MAIN=true
UPDATE_CATEGORY=true
UPDATE_INSTALL=true
UPDATE_UPGRADE=true
UPDATE_SNAPSHOT=true
UPDATE_STATESYNC=true
UPDATE_LIVE_PEERS=true
UPDATE_CLI_CHEATSHEET=true
