# App
CHAIN_NAME="XRP"
CHAIN_SYSTEM_NAME="xrp"
CHAIN_ICON="xrp-icon.svg"
CHAIN_BACKGROUND_COLOR="#7B00F3"

# NODERS
STAKE_URL=""
RESTAKE_URL=""
VALIDATOR_URL=""
EXPLORER_URL=""
APP_URL=""
APP_IMAGE=""
FAUCET_URL=""

# Blockchain
CHAIN_ID="auto"
CHAIN_DENOM="apoa"
CHAIN_FEES="300000000000"

# Binary
VERSION="auto"
DAEMON_NAME="exrpd"
DAEMON_SERVICE="xrp.service"
DAEMON_HOME="~/.exrpd"

# Endpoints
ENDPOINT_RPC="https://xrp-t-rpc.noders.services"
ENDPOINT_API="https://xrp-t-api.noders.services"
ENDPOINT_JRPC=""
ENDPOINT_GRPC="xrp-t-grpc.noders.services:443"
ENDPOINT_PEER="auto"
ENDPOINT_SEED="1f5ece1cbfba945f79b9d2ddda2582498082093d@xrp-t-seed.noders.services:37933"
ENDPOINT_COSMOSLIST="https://cosmoslist.co/testnet/xrp"

# Social
SOCIAL_WEBSITE="https://xrplevm.org/"
SOCIAL_GITHUB="https://github.com/xrplevm/node"
SOCIAL_DISCORD="https://discord.gg/xrplevm"
SOCIAL_X=""
SOCIAL_TELEGRAM=""

# Other
SNAPSHOT_URL="https://snapshots-t.noders.services/xrp"
GITHUB_FOLDER_NAME="auto"
VALIDATOR_URL=""

# Updates
UPDATE_MAIN=true
UPDATE_CATEGORY=true
UPDATE_INSTALL=true
UPDATE_UPGRADE=true
UPDATE_SNAPSHOT=true
UPDATE_STATESYNC=true
UPDATE_LIVE_PEERS=true
UPDATE_CLI_CHEATSHEET=true
UPDATE_ENDPOINTS=true

# Feature toggles
# Node installation
SHOW_INSTALLATION_GUIDE=true
SHOW_UPGRADE_GUIDE=true
SHOW_GENESIS=true
SHOW_CLI=true
# Endpoints and Sync
SHOW_ENDPOINTS=true
SHOW_STATE_SYNC=true
SHOW_SNAPSHOT=true
SHOW_LIVE_PEERS=true
SHOW_SEED=true
SHOW_ADDRESS_BOOK=true
# Tools
SHOW_EXPLORERS_LIST=false
SHOW_PUBLIC_ENDPOINTS=false
SHOW_USEFUL_TOOLS=false
SHOW_UPGRADE_WATCHER=false
