# App
CHAIN_NAME="Zenrock"
CHAIN_SYSTEM_NAME="zenrock"
CHAIN_ICON="zenrock-icon.svg"
CHAIN_BACKGROUND_COLOR="#050C40"

# NODERS
STAKE_URL=""
RESTAKE_URL=""
VALIDATOR_URL="https://testnet.itrocket.net/zenrock/staking/zenvaloper1jmxxnpl4saratjf46dsv3kfk5ny3qk0923fdwn"
EXPLORER_URL=""
EXPLORER_IMAGE=""
APP_URL=""
APP_IMAGE=""
FAUCET_URL=""

# Blockchain
CHAIN_ID="auto"
CHAIN_DENOM="urock"
CHAIN_FEES="20000"

# Binary
VERSION="auto"
DAEMON_NAME="zenrockd"
DAEMON_SERVICE="zenrock.service"
DAEMON_HOME="~/.zrchain"

# Endpoints
ENDPOINT_RPC="https://zenrock-t-rpc.noders.services"
ENDPOINT_API="https://zenrock-t-api.noders.services"
ENDPOINT_JRPC=""
ENDPOINT_GRPC="zenrock-t-grpc.noders.services:443"
ENDPOINT_PEER="auto"
ENDPOINT_SEED="24cf2d3bd77e9d0eb3b6a5f81ae0048d5739af8c@zenrock-t-seed.noders.services:40956"
ENDPOINT_COSMOSLIST="https://cosmoslist.co/testnet/zenrock"

# Social
SOCIAL_WEBSITE="https://www.zenrocklabs.io"
SOCIAL_GITHUB="https://github.com/Zenrock-Foundation/zrchain"
SOCIAL_DISCORD="https://discord.com/invite/zenrockfoundation"
SOCIAL_X="https://x.com/OfficialZenrock"
SOCIAL_TELEGRAM="https://t.me/officialZenrock"

# Other
SNAPSHOT_URL="https://snapshots-t.noders.services/zenrock"
GITHUB_FOLDER_NAME="auto"

# Updates
UPDATE_MAIN=true
UPDATE_CATEGORY=true
UPDATE_INSTALL=true
UPDATE_UPGRADE=true
UPDATE_SNAPSHOT=true
UPDATE_STATESYNC=true
UPDATE_LIVE_PEERS=true
UPDATE_CLI_CHEATSHEET=true
UPDATE_ENDPOINTS=true
UPDATE_MONITORING=true

# Feature toggles

# Node installation
SHOW_INSTALLATION_GUIDE=true
SHOW_UPGRADE_GUIDE=true
SHOW_GENESIS=true
SHOW_CLI=true

# Endpoints and Sync
SHOW_ENDPOINTS=true
SHOW_STATE_SYNC=true
SHOW_SNAPSHOT=true
SHOW_LIVE_PEERS=true
SHOW_SEED=true
SHOW_ADDRESS_BOOK=true

# Tools
SHOW_EXPLORERS_LIST=false
SHOW_PUBLIC_ENDPOINTS=false
SHOW_USEFUL_TOOLS=false
SHOW_UPGRADE_WATCHER=false

# Monitoring Configuration
MONITORING_PROMETHEUS_PORT="9090"
MONITORING_GRAFANA_PORT="3000"
MONITORING_NODE_METRICS_PORT="26661"
MONITORING_GRAFANA_PASSWORD="admin123"
MONITORING_MAX_MISSED_BLOCKS="5"
MONITORING_DASHBOARD_ID="15991"
