# Blockchain
CHAIN_NAME="Zetachain"
CHAIN_SYSTEM_NAME="zetachain"
CHAIN_ID="auto"
VERSION="auto"
CHAIN_DESCRIPTION="""# ZetaChain: Unifying Chains for a Connected Blockchain World

ZetaChain aims to revolutionize the blockchain landscape by offering a truly interoperable platform that connects disparate blockchain networks, enabling seamless communication and transactions across different ecosystems. As a multi-chain protocol, ZetaChain facilitates the transfer of data and value between all blockchains, whether they are public, private, or consortium, without requiring intermediaries. This open infrastructure supports smart contracts, allowing developers to build applications that can interact with any blockchain from a single platform. ZetaChain's innovative approach not only enhances efficiency and scalability but also opens up new possibilities for decentralized applications, fostering a more integrated and collaborative blockchain environment.

"""
[CHAIN_DESCRIPTION_END]

CHAIN_DENOM="azeta"
CHAIN_FEES="300000000000"

# Binary
DAEMON_NAME="zetacored"
DAEMON_SERVICE="zetacore.service"
DAEMON_HOME="~/.zetacored"

# Endpoints
ENDPOINT_RPC="https://zetachain-t-rpc.noders.services"
ENDPOINT_API="https://zetachain-t-api.noders.services"
ENDPOINT_JRPC="https://zetachain-t-jsonrpc.noders.services"
ENDPOINT_GRPC="https://zetachain-t-grpc.noders.services:443"
ENDPOINT_PEER="auto"
ENDPOINT_COSMOSLIST="https://cosmoslist.co/testnet/zetachain"

# Social
SOCIAL_WEBSITE="https://www.zetachain.com/"
SOCIAL_GITHUB="https://github.com/zeta-chain"
SOCIAL_DISCORD="https://discord.gg/zetachain"
SOCIAL_X="https://twitter.com/zetablockchain"
SOCIAL_TELEGRAM="https://t.me/zetachainofficial"

# Other
SNAPSHOT_URL="https://snapshots-t.noders.services/zetachain"
GITHUB_FOLDER_NAME="auto"
VALIDATOR_URL="https://athens.explorer.zetachain.com/address/0x49A17CCa0Fd5cb5AE9056Bbac316D3FCe098Aed2"

# Updates
UPDATE_MAIN=true
UPDATE_CATEGORY=true
UPDATE_INSTALL=true
UPDATE_UPGRADE=true
UPDATE_SNAPSHOT=true
UPDATE_STATESYNC=true
UPDATE_LIVE_PEERS=true
UPDATE_CLI_CHEATSHEET=true

# Feature toggles
# Node installation
SHOW_INSTALLATION_GUIDE=true
SHOW_UPGRADE_GUIDE=true
SHOW_GENESIS=true
SHOW_CLI=true
# Endpoints and Sync
SHOW_ENDPOINTS=true
SHOW_STATE_SYNC=true
SHOW_SNAPSHOT=true
SHOW_LIVE_PEERS=true
SHOW_SEED=true
SHOW_ADDRESS_BOOK=true
# Tools
SHOW_EXPLORERS_LIST=false
SHOW_PUBLIC_ENDPOINTS=false
SHOW_USEFUL_TOOLS=false
SHOW_UPGRADE_WATCHER=false
