# App
CHAIN_NAME="Zetachain"
CHAIN_SYSTEM_NAME="zetachain"
CHAIN_ICON="zetachain-icon.svg"
CHAIN_BACKGROUND_COLOR="#1A563E"

# NODERS
STAKE_URL=""
RESTAKE_URL=""
VALIDATOR_URL="https://testnet.zetachain.explorers.guru/validator/zetavaloper1fxshejs06h9446g9dwavx9knlnsf3tkj3y4ft2"
EXPLORER_URL=""
EXPLORER_IMAGE="zetachain-exp.png"
APP_URL="https://zetaresources.org"
APP_IMAGE="zetachain-app.png"
FAUCET_URL=""

# Blockchain
CHAIN_ID="auto"
CHAIN_DENOM_PRETTY="ZETA"
CHAIN_DENOM="azeta"
CHAIN_FEES="300000000000"

# Binary
VERSION="auto"
DAEMON_NAME="zetacored"
DAEMON_SERVICE="zetacore.service"
DAEMON_HOME="~/.zetacored"

# Endpoints
ENDPOINT_RPC="https://zetachain-t-rpc.noders.services"
ENDPOINT_API="https://zetachain-t-api.noders.services"
ENDPOINT_JRPC="https://zetachain-t-jsonrpc.noders.services"
ENDPOINT_GRPC="zetachain-t-grpc.noders.services:443"
ENDPOINT_PEER="auto"
ENDPOINT_SEED="7ede5fcf7cb3866494969e35384e2b6accbd692c@zetachain-t-seed.noders.services:22533"
ENDPOINT_COSMOSLIST="https://cosmoslist.co/testnet/zetachain"
ENDPOINT_SEED=""

# Social
SOCIAL_WEBSITE="https://www.zetachain.com/"
SOCIAL_GITHUB="https://github.com/zeta-chain"
SOCIAL_DISCORD="https://discord.gg/zetachain"
SOCIAL_X="https://twitter.com/zetablockchain"
SOCIAL_TELEGRAM="https://t.me/zetachainofficial"

# Other
SNAPSHOT_URL="https://snapshots-t.noders.services/zetachain"
GITHUB_FOLDER_NAME="auto"

# Updates
UPDATE_MAIN=true
UPDATE_CATEGORY=true
UPDATE_INSTALL=true
UPDATE_UPGRADE=true
UPDATE_SNAPSHOT=true
UPDATE_STATESYNC=true
UPDATE_LIVE_PEERS=true
UPDATE_CLI_CHEATSHEET=true
UPDATE_ENDPOINTS=true
UPDATE_MONITORING=true

# Feature toggles

# Node installation
SHOW_INSTALLATION_GUIDE=true
SHOW_UPGRADE_GUIDE=true
SHOW_GENESIS=true
SHOW_CLI=true

# Endpoints and Sync
SHOW_ENDPOINTS=true
SHOW_STATE_SYNC=true
SHOW_SNAPSHOT=true
SHOW_LIVE_PEERS=true
SHOW_SEED=true
SHOW_ADDRESS_BOOK=true

# Tools
SHOW_EXPLORERS_LIST=true
SHOW_PUBLIC_ENDPOINTS=false
SHOW_USEFUL_TOOLS=true
SHOW_UPGRADE_WATCHER=false
SHOW_MONITORING=true

# Monitoring Configuration
MONITORING_PROMETHEUS_PORT="9090"
MONITORING_GRAFANA_PORT="3000"
MONITORING_NODE_METRICS_PORT="26661"
MONITORING_GRAFANA_PASSWORD="admin123"
MONITORING_MAX_MISSED_BLOCKS="5"
MONITORING_DASHBOARD_ID="15991"
