// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
module.exports = {
  mainnetSidebar: [
    {
      type: 'html',
      value: 'Cosmos Networks',
      className: 'sidebar-section-header',
    },
    {
      type: 'category',
      label: 'Osmosis',
      link: {
        type: 'doc',
        id: 'mainnet-networks/osmosis',
        image: 'img/osmosis.svg',
      },
      collapsible: true,
      items: [{type: 'autogenerated', dirName: 'mainnet-networks/osmosis'}],
    },
  ]
};