// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
module.exports = {
  mainnetSidebar: [
    {
      type: 'doc',
      id: 'mainnet/overview',
      label: 'Mainnet Networks',
    },
    {
      type: 'category',
      label: 'Andromeda',
      link: {
        type: 'doc',
        id: 'mainnet/andromeda',
      },
      collapsible: true,
      items: [{ type: 'autogenerated', dirName: 'mainnet/andromeda' }],
      className: 'sidebar-section-with-icon icon-andromeda',
    },
    {
      type: 'category',
      label: 'Althea',
      link: {
        type: 'doc',
        id: 'mainnet/althea',
      },
      collapsible: true,
      items: [{ type: 'autogenerated', dirName: 'mainnet/althea' }],
      className: 'sidebar-section-with-icon icon-althea',
    },
    {
      type: 'category',
      label: 'Arkeo',
      link: {
        type: 'doc',
        id: 'mainnet/arkeo',
      },
      collapsible: true,
      items: [{ type: 'autogenerated', dirName: 'mainnet/arkeo' }],
      className: 'sidebar-section-with-icon icon-arkeo',
    },
    {
      type: 'category',
      label: 'Atomone',
      link: {
        type: 'doc',
        id: 'mainnet/atomone',
      },
      collapsible: true,
      items: [{ type: 'autogenerated', dirName: 'mainnet/atomone' }],
      className: 'sidebar-section-with-icon icon-atomone',
    },
    {
      type: 'category',
      label: 'Aura',
      link: {
        type: 'doc',
        id: 'mainnet/aura',
      },
      collapsible: true,
      items: [{ type: 'autogenerated', dirName: 'mainnet/aura' }],
      className: 'sidebar-section-with-icon icon-aura',
    },
    {
      type: 'category',
      label: 'Babylon',
      link: {
        type: 'doc',
        id: 'mainnet/babylon',
      },
      collapsible: true,
      items: [{ type: 'autogenerated', dirName: 'mainnet/babylon' }],
      className: 'sidebar-section-with-icon icon-babylon',
    },
    {
      type: 'category',
      label: 'Celestia',
      link: {
        type: 'doc',
        id: 'mainnet/celestia',
      },
      collapsible: true,
      items: [{ type: 'autogenerated', dirName: 'mainnet/celestia' }],
      className: 'sidebar-section-with-icon icon-celestia',
    },
    {
      type: 'category',
      label: 'DoraVota',
      link: {
        type: 'doc',
        id: 'mainnet/dora',
      },
      collapsible: true,
      items: [{ type: 'autogenerated', dirName: 'mainnet/dora' }],
      className: 'sidebar-section-with-icon icon-dora',
    },
    {
      type: 'category',
      label: 'Dymension',
      link: {
        type: 'doc',
        id: 'mainnet/dymension',
      },
      collapsible: true,
      items: [{ type: 'autogenerated', dirName: 'mainnet/dymension' }],
      className: 'sidebar-section-with-icon icon-dymension',
    },
    {
      type: 'category',
      label: 'Fuel',
      link: {
        type: 'doc',
        id: 'mainnet/fuel',
      },
      collapsible: true,
      items: [{ type: 'autogenerated', dirName: 'mainnet/fuel' }],
      className: 'sidebar-section-with-icon icon-fuel',
    },
    {
      type: 'category',
      label: 'HAQQ',
      link: {
        type: 'doc',
        id: 'mainnet/haqq',
      },
      collapsible: true,
      items: [{ type: 'autogenerated', dirName: 'mainnet/haqq' }],
      className: 'sidebar-section-with-icon icon-haqq',
    },
    {
      type: 'category',
      label: 'Humans',
      link: {
        type: 'doc',
        id: 'mainnet/humans',
      },
      collapsible: true,
      items: [{ type: 'autogenerated', dirName: 'mainnet/humans' }],
      className: 'sidebar-section-with-icon icon-humans',
    },
    {
      type: 'category',
      label: 'Jackal',
      link: {
        type: 'doc',
        id: 'mainnet/jackal',
      },
      collapsible: true,
      items: [{ type: 'autogenerated', dirName: 'mainnet/jackal' }],
      className: 'sidebar-section-with-icon icon-jackal',
    },
    {
      type: 'category',
      label: 'Kopi',
      link: {
        type: 'doc',
        id: 'mainnet/kopi',
      },
      collapsible: true,
      items: [{ type: 'autogenerated', dirName: 'mainnet/kopi' }],
      className: 'sidebar-section-with-icon icon-kopi',
    },
    {
      type: 'category',
      label: 'Lava',
      link: {
        type: 'doc',
        id: 'mainnet/lava',
      },
      collapsible: true,
      items: [{ type: 'autogenerated', dirName: 'mainnet/lava' }],
      className: 'sidebar-section-with-icon icon-lava',
    },
    {
      type: 'category',
      label: 'Namada',
      link: {
        type: 'doc',
        id: 'mainnet/namada',
      },
      collapsible: true,
      items: [{ type: 'autogenerated', dirName: 'mainnet/namada' }],
      className: 'sidebar-section-with-icon icon-namada',
    },
    {
      type: 'category',
      label: 'Nillion',
      link: {
        type: 'doc',
        id: 'mainnet/nillion',
      },
      collapsible: true,
      items: [{ type: 'autogenerated', dirName: 'mainnet/nillion' }],
      className: 'sidebar-section-with-icon icon-nillion',
    },
    {
      type: 'category',
      label: 'Osmosis',
      link: {
        type: 'doc',
        id: 'mainnet/osmosis',
      },
      collapsible: true,
      items: [{ type: 'autogenerated', dirName: 'mainnet/osmosis' }],
      className: 'sidebar-section-with-icon icon-osmosis',
    },
    {
      type: 'category',
      label: 'Pylons',
      link: {
        type: 'doc',
        id: 'mainnet/pylons',
      },
      collapsible: true,
      items: [{ type: 'autogenerated', dirName: 'mainnet/pylons' }],
      className: 'sidebar-section-with-icon icon-pylons',
    },
    {
      type: 'category',
      label: 'Realio',
      link: {
        type: 'doc',
        id: 'mainnet/realio',
      },
      collapsible: true,
      items: [{ type: 'autogenerated', dirName: 'mainnet/realio' }],
      className: 'sidebar-section-with-icon icon-realio',
    },
    {
      type: 'category',
      label: 'Router',
      link: {
        type: 'doc',
        id: 'mainnet/router',
      },
      collapsible: true,
      items: [{ type: 'autogenerated', dirName: 'mainnet/router' }],
      className: 'sidebar-section-with-icon icon-router',
    },
    {
      type: 'category',
      label: 'Seda',
      link: {
        type: 'doc',
        id: 'mainnet/seda',
      },
      collapsible: true,
      items: [{ type: 'autogenerated', dirName: 'mainnet/seda' }],
      className: 'sidebar-section-with-icon icon-seda',
    },
    {
      type: 'category',
      label: 'Sei',
      link: {
        type: 'doc',
        id: 'mainnet/sei',
      },
      collapsible: true,
      items: [{ type: 'autogenerated', dirName: 'mainnet/sei' }],
      className: 'sidebar-section-with-icon icon-sei',
    },
    {
      type: 'category',
      label: 'Stratos',
      link: {
        type: 'doc',
        id: 'mainnet/stratos',
      },
      collapsible: true,
      items: [{ type: 'autogenerated', dirName: 'mainnet/stratos' }],
      className: 'sidebar-section-with-icon icon-stratos',
    },
    {
      type: 'category',
      label: 'Zenrock',
      link: {
        type: 'doc',
        id: 'mainnet/zenrock',
      },
      collapsible: true,
      items: [{ type: 'autogenerated', dirName: 'mainnet/zenrock' }],
      className: 'sidebar-section-with-icon icon-zenrock',
    },
    {
      type: 'category',
      label: 'Zetachain',
      link: {
        type: 'doc',
        id: 'mainnet/zetachain',
      },
      collapsible: true,
      items: [{ type: 'autogenerated', dirName: 'mainnet/zetachain' }],
      className: 'sidebar-section-with-icon icon-zetachain',
    },
  ],
};
