// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
module.exports = {
  testnetSidebar: [
    {
      type: 'doc',
      id: 'testnet-networks/overview',
      label: 'Cosmos Networks',
    },
    {
      type: 'category',
      label: 'Alignedlayer',
      link: {
        type: 'doc',
        id: 'testnet-networks/alignedlayer',
      },
      collapsible: true,
      items: [{type: 'autogenerated', dirName: 'testnet-networks/alignedlayer'}],
      className: 'sidebar-section-with-icon icon-alignedlayer',
    },
    {
      type: 'category',
      label: 'Artela',
      link: {
        type: 'doc',
        id: 'testnet-networks/artela',
      },
      collapsible: true,
      items: [{type: 'autogenerated', dirName: 'testnet-networks/artela'}],
      className: 'sidebar-section-with-icon icon-artela',
    },
    {
      type: 'category',
      label: 'Band',
      link: {
        type: 'doc',
        id: 'testnet-networks/band',
      },
      collapsible: true,
      items: [{type: 'autogenerated', dirName: 'testnet-networks/band'}],
      className: 'sidebar-section-with-icon icon-band',
    },
    {
      type: 'category',
      label: 'Berachain',
      link: {
        type: 'doc',
        id: 'testnet-networks/bera',
      },
      collapsible: true,
      items: [{type: 'autogenerated', dirName: 'testnet-networks/bera'}],
      className: 'sidebar-section-with-icon icon-berachain',
    },
    {
      type: 'category',
      label: 'Celestia',
      link: {
        type: 'doc',
        id: 'testnet-networks/celestia',
      },
      collapsible: true,
      items: [{type: 'autogenerated', dirName: 'testnet-networks/celestia'}],
      className: 'sidebar-section-with-icon icon-celestia',
    },
    {
      type: 'category',
      label: 'CrossFi',
      link: {
        type: 'doc',
        id: 'testnet-networks/crossfi',
      },
      collapsible: true,
      items: [{type: 'autogenerated', dirName: 'testnet-networks/crossfi'}],
      className: 'sidebar-section-with-icon icon-crossfi',
    },
    {
      type: 'category',
      label: 'Entrypoint',
      link: {
        type: 'doc',
        id: 'testnet-networks/entrypoint',
      },
      collapsible: true,
      items: [{type: 'autogenerated', dirName: 'testnet-networks/entrypoint'}],
      className: 'sidebar-section-with-icon icon-entrypoint',
    },
    {
      type: 'category',
      label: 'Galactica',
      link: {
        type: 'doc',
        id: 'testnet-networks/galactica',
      },
      collapsible: true,
      items: [{type: 'autogenerated', dirName: 'testnet-networks/galactica'}],
      className: 'sidebar-section-with-icon icon-galactica',
    },
    {
      type: 'category',
      label: 'Jackal',
      link: {
        type: 'doc',
        id: 'testnet-networks/jackal',
      },
      collapsible: true,
      items: [{type: 'autogenerated', dirName: 'testnet-networks/jackal'}],
      className: 'sidebar-section-with-icon icon-jackal',
    },
    {
      type: 'category',
      label: 'Lava',
      link: {
        type: 'doc',
        id: 'testnet-networks/lava',
      },
      collapsible: true,
      items: [{type: 'autogenerated', dirName: 'testnet-networks/lava'}],
      className: 'sidebar-section-with-icon icon-lava',
    },
    {
      type: 'category',
      label: 'ZeroGravity',
      link: {
        type: 'doc',
        id: 'testnet-networks/og',
      },
      collapsible: true,
      items: [{type: 'autogenerated', dirName: 'testnet-networks/og'}],
      className: 'sidebar-section-with-icon icon-og',
    },
    {
      type: 'category',
      label: 'Osmosis',
      link: {
        type: 'doc',
        id: 'testnet-networks/osmosis',
      },
      collapsible: true,
      items: [{type: 'autogenerated', dirName: 'testnet-networks/osmosis'}],
      className: 'sidebar-section-with-icon icon-osmosis',
    },
    {
      type: 'category',
      label: 'Pryzm',
      link: {
        type: 'doc',
        id: 'testnet-networks/pryzm',
      },
      collapsible: true,
      items: [{type: 'autogenerated', dirName: 'testnet-networks/pryzm'}],
      className: 'sidebar-section-with-icon icon-pryzm',
    },
    {
      type: 'category',
      label: 'Quicksilver',
      link: {
        type: 'doc',
        id: 'testnet-networks/quicksilver',
      },
      collapsible: true,
      items: [{type: 'autogenerated', dirName: 'testnet-networks/quicksilver'}],
      className: 'sidebar-section-with-icon icon-quicksilver',
    },
    {
      type: 'category',
      label: 'Router',
      link: {
        type: 'doc',
        id: 'testnet-networks/router',
      },
      collapsible: true,
      items: [{type: 'autogenerated', dirName: 'testnet-networks/router'}],
      className: 'sidebar-section-with-icon icon-router',
    },
    {
      type: 'category',
      label: 'Seda',
      link: {
        type: 'doc',
        id: 'testnet-networks/seda',
      },
      collapsible: true,
      items: [{type: 'autogenerated', dirName: 'testnet-networks/seda'}],
      className: 'sidebar-section-with-icon icon-seda',
    },
    {
      type: 'category',
      label: 'Side',
      link: {
        type: 'doc',
        id: 'testnet-networks/side',
      },
      collapsible: true,
      items: [{type: 'autogenerated', dirName: 'testnet-networks/side'}],
      className: 'sidebar-section-with-icon icon-side',
    },
    {
      type: 'category',
      label: 'Swisstronic',
      link: {
        type: 'doc',
        id: 'testnet-networks/swisstronic',
      },
      collapsible: true,
      items: [{type: 'autogenerated', dirName: 'testnet-networks/swisstronic'}],
      className: 'sidebar-section-with-icon icon-swisstronic',
    },
    {
      type: 'category',
      label: 'Union',
      link: {
        type: 'doc',
        id: 'testnet-networks/union',
      },
      collapsible: true,
      items: [{type: 'autogenerated', dirName: 'testnet-networks/union'}],
      className: 'sidebar-section-with-icon icon-union',
    },
    {
      type: 'category',
      label: 'Warden',
      link: {
        type: 'doc',
        id: 'testnet-networks/warden',
      },
      collapsible: true,
      items: [{type: 'autogenerated', dirName: 'testnet-networks/warden'}],
      className: 'sidebar-section-with-icon icon-warden',
    },
    {
      type: 'category',
      label: 'Zetachain',
      link: {
        type: 'doc',
        id: 'testnet-networks/zetachain',
      },
      collapsible: true,
      items: [{type: 'autogenerated', dirName: 'testnet-networks/zetachain'}],
      className: 'sidebar-section-with-icon icon-zetachain',
    }
  ]
};
