// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
module.exports = {
  testnetSidebar: [
    {
      type: 'doc',
      id: 'testnet-networks/overview',
      label: 'Cosmos Networks',
    },
    {
      type: 'category',
      label: 'Airchains',
      link: {
        type: 'doc',
        id: 'testnet-networks/airchains',
      },
      collapsible: true,
      items: [{type: 'autogenerated', dirName: 'testnet-networks/airchains'}],
      className: 'sidebar-section-with-icon icon-airchains',
    },
    {
      type: 'category',
      label: 'Atomone',
      link: {
        type: 'doc',
        id: 'testnet-networks/atomone',
      },
      collapsible: true,
      items: [{type: 'autogenerated', dirName: 'testnet-networks/atomone'}],
      className: 'sidebar-section-with-icon icon-atomone',
    },
    {
      type: 'category',
      label: 'Axone',
      link: {
        type: 'doc',
        id: 'testnet-networks/axone',
      },
      collapsible: true,
      items: [{type: 'autogenerated', dirName: 'testnet-networks/axone'}],
      className: 'sidebar-section-with-icon icon-axone',
    },
    {
      type: 'category',
      label: 'Celestia',
      link: {
        type: 'doc',
        id: 'testnet-networks/celestia',
      },
      collapsible: true,
      items: [{type: 'autogenerated', dirName: 'testnet-networks/celestia'}],
      className: 'sidebar-section-with-icon icon-celestia',
    },
    {
      type: 'category',
      label: 'CrossFi',
      link: {
        type: 'doc',
        id: 'testnet-networks/crossfi',
      },
      collapsible: true,
      items: [{type: 'autogenerated', dirName: 'testnet-networks/crossfi'}],
      className: 'sidebar-section-with-icon icon-crossfi',
    },
    {
      type: 'category',
      label: 'DoraVota',
      link: {
        type: 'doc',
        id: 'testnet-networks/dora',
      },
      collapsible: true,
      items: [{type: 'autogenerated', dirName: 'testnet-networks/dora'}],
      className: 'sidebar-section-with-icon icon-dora',
    },
    {
      type: 'category',
      label: 'Empeiria',
      link: {
        type: 'doc',
        id: 'testnet-networks/empeiria',
      },
      collapsible: true,
      items: [{type: 'autogenerated', dirName: 'testnet-networks/empeiria'}],
      className: 'sidebar-section-with-icon icon-empeiria',
    },
    {
      type: 'category',
      label: 'Galactica',
      link: {
        type: 'doc',
        id: 'testnet-networks/galactica',
      },
      collapsible: true,
      items: [{type: 'autogenerated', dirName: 'testnet-networks/galactica'}],
      className: 'sidebar-section-with-icon icon-galactica',
    },
    {
      type: 'category',
      label: 'Jackal',
      link: {
        type: 'doc',
        id: 'testnet-networks/jackal',
      },
      collapsible: true,
      items: [{type: 'autogenerated', dirName: 'testnet-networks/jackal'}],
      className: 'sidebar-section-with-icon icon-jackal',
    },
    {
      type: 'category',
      label: 'Lava',
      link: {
        type: 'doc',
        id: 'testnet-networks/lava',
      },
      collapsible: true,
      items: [{type: 'autogenerated', dirName: 'testnet-networks/lava'}],
      className: 'sidebar-section-with-icon icon-lava',
    },
    {
      type: 'category',
      label: 'Mantra',
      link: {
        type: 'doc',
        id: 'testnet-networks/mantra',
      },
      collapsible: true,
      items: [{type: 'autogenerated', dirName: 'testnet-networks/mantra'}],
      className: 'sidebar-section-with-icon icon-mantra',
    },
    {
      type: 'category',
      label: 'nillion',
      link: {
        type: 'doc',
        id: 'testnet-networks/nillion',
      },
      collapsible: true,
      items: [{type: 'autogenerated', dirName: 'testnet-networks/nillion'}],
      className: 'sidebar-section-with-icon icon-nillion',
    },
    {
      type: 'category',
      label: 'Osmosis',
      link: {
        type: 'doc',
        id: 'testnet-networks/osmosis',
      },
      collapsible: true,
      items: [{type: 'autogenerated', dirName: 'testnet-networks/osmosis'}],
      className: 'sidebar-section-with-icon icon-osmosis',
    },
    {
      type: 'category',
      label: 'Pell',
      link: {
        type: 'doc',
        id: 'testnet-networks/pell',
      },
      collapsible: true,
      items: [{type: 'autogenerated', dirName: 'testnet-networks/pell'}],
      className: 'sidebar-section-with-icon icon-pell',
    },
    {
      type: 'category',
      label: 'Quicksilver',
      link: {
        type: 'doc',
        id: 'testnet-networks/quicksilver',
      },
      collapsible: true,
      items: [{type: 'autogenerated', dirName: 'testnet-networks/quicksilver'}],
      className: 'sidebar-section-with-icon icon-quicksilver',
    },
    {
      type: 'category',
      label: 'Seda',
      link: {
        type: 'doc',
        id: 'testnet-networks/seda',
      },
      collapsible: true,
      items: [{type: 'autogenerated', dirName: 'testnet-networks/seda'}],
      className: 'sidebar-section-with-icon icon-seda',
    },
    {
      type: 'category',
      label: 'Side',
      link: {
        type: 'doc',
        id: 'testnet-networks/side',
      },
      collapsible: true,
      items: [{type: 'autogenerated', dirName: 'testnet-networks/side'}],
      className: 'sidebar-section-with-icon icon-side',
    },
    {
      type: 'category',
      label: 'Story',
      link: {
        type: 'doc',
        id: 'testnet-networks/story',
      },
      collapsible: true,
      items: [{type: 'autogenerated', dirName: 'testnet-networks/story'}],
      className: 'sidebar-section-with-icon icon-story',
    },
    {
      type: 'category',
      label: 'Sunrise',
      link: {
        type: 'doc',
        id: 'testnet-networks/sunrise',
      },
      collapsible: true,
      items: [{type: 'autogenerated', dirName: 'testnet-networks/sunrise'}],
      className: 'sidebar-section-with-icon icon-sunrise',
    },
    {
      type: 'category',
      label: 'XRP',
      link: {
        type: 'doc',
        id: 'testnet-networks/xrp',
      },
      collapsible: true,
      items: [{type: 'autogenerated', dirName: 'testnet-networks/xrp'}],
      className: 'sidebar-section-with-icon icon-xrp',
    },
    {
      type: 'category',
      label: 'Union',
      link: {
        type: 'doc',
        id: 'testnet-networks/union',
      },
      collapsible: true,
      items: [{type: 'autogenerated', dirName: 'testnet-networks/union'}],
      className: 'sidebar-section-with-icon icon-union',
    },
    {
      type: 'category',
      label: 'Warden',
      link: {
        type: 'doc',
        id: 'testnet-networks/warden',
      },
      collapsible: true,
      items: [{type: 'autogenerated', dirName: 'testnet-networks/warden'}],
      className: 'sidebar-section-with-icon icon-warden',
    },
    {
      type: 'category',
      label: 'ZeroGravity',
      link: {
        type: 'doc',
        id: 'testnet-networks/og',
      },
      collapsible: true,
      items: [{type: 'autogenerated', dirName: 'testnet-networks/og'}],
      className: 'sidebar-section-with-icon icon-og',
    },
    {
      type: 'category',
      label: 'Zetachain',
      link: {
        type: 'doc',
        id: 'testnet-networks/zetachain',
      },
      collapsible: true,
      items: [{type: 'autogenerated', dirName: 'testnet-networks/zetachain'}],
      className: 'sidebar-section-with-icon icon-zetachain',
    },
  ],
};
