// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
module.exports = {
  testnetSidebar: [
    {
      type: 'doc',
      id: 'testnet/overview',
      label: 'Testnet Networks',
    },
    {
      type: 'category',
      label: 'Airchains',
      link: {
        type: 'doc',
        id: 'testnet/airchains',
      },
      collapsible: true,
      items: [{ type: 'autogenerated', dirName: 'testnet/airchains' }],
      className: 'sidebar-section-with-icon icon-airchains',
    },
    {
      type: 'category',
      label: 'Arkeo',
      link: {
        type: 'doc',
        id: 'testnet/arkeo',
      },
      collapsible: true,
      items: [{ type: 'autogenerated', dirName: 'testnet/arkeo' }],
      className: 'sidebar-section-with-icon icon-arkeo',
    },
    {
      type: 'category',
      label: 'Atomone',
      link: {
        type: 'doc',
        id: 'testnet/atomone',
      },
      collapsible: true,
      items: [{ type: 'autogenerated', dirName: 'testnet/atomone' }],
      className: 'sidebar-section-with-icon icon-atomone',
    },
    {
      type: 'category',
      label: 'Axone',
      link: {
        type: 'doc',
        id: 'testnet/axone',
      },
      collapsible: true,
      items: [{ type: 'autogenerated', dirName: 'testnet/axone' }],
      className: 'sidebar-section-with-icon icon-axone',
    },
    {
      type: 'category',
      label: 'Celestia',
      link: {
        type: 'doc',
        id: 'testnet/celestia',
      },
      collapsible: true,
      items: [{ type: 'autogenerated', dirName: 'testnet/celestia' }],
      className: 'sidebar-section-with-icon icon-celestia',
    },
    {
      type: 'category',
      label: 'CrossFi',
      link: {
        type: 'doc',
        id: 'testnet/crossfi',
      },
      collapsible: true,
      items: [{ type: 'autogenerated', dirName: 'testnet/crossfi' }],
      className: 'sidebar-section-with-icon icon-crossfi',
    },
    {
      type: 'category',
      label: 'DoraVota',
      link: {
        type: 'doc',
        id: 'testnet/dora',
      },
      collapsible: true,
      items: [{ type: 'autogenerated', dirName: 'testnet/dora' }],
      className: 'sidebar-section-with-icon icon-dora',
    },
    {
      type: 'category',
      label: 'Empeiria',
      link: {
        type: 'doc',
        id: 'testnet/empeiria',
      },
      collapsible: true,
      items: [{ type: 'autogenerated', dirName: 'testnet/empeiria' }],
      className: 'sidebar-section-with-icon icon-empeiria',
    },
    {
      type: 'category',
      label: 'Galactica',
      link: {
        type: 'doc',
        id: 'testnet/galactica',
      },
      collapsible: true,
      items: [{ type: 'autogenerated', dirName: 'testnet/galactica' }],
      className: 'sidebar-section-with-icon icon-galactica',
    },
    {
      type: 'category',
      label: 'Jackal',
      link: {
        type: 'doc',
        id: 'testnet/jackal',
      },
      collapsible: true,
      items: [{ type: 'autogenerated', dirName: 'testnet/jackal' }],
      className: 'sidebar-section-with-icon icon-jackal',
    },
    {
      type: 'category',
      label: 'Lava',
      link: {
        type: 'doc',
        id: 'testnet/lava',
      },
      collapsible: true,
      items: [{ type: 'autogenerated', dirName: 'testnet/lava' }],
      className: 'sidebar-section-with-icon icon-lava',
    },
    {
      type: 'category',
      label: 'Mantra',
      link: {
        type: 'doc',
        id: 'testnet/mantra',
      },
      collapsible: true,
      items: [{ type: 'autogenerated', dirName: 'testnet/mantra' }],
      className: 'sidebar-section-with-icon icon-mantra',
    },
    {
      type: 'category',
      label: 'Nillion',
      link: {
        type: 'doc',
        id: 'testnet/nillion',
      },
      collapsible: true,
      items: [{ type: 'autogenerated', dirName: 'testnet/nillion' }],
      className: 'sidebar-section-with-icon icon-nillion',
    },
    {
      type: 'category',
      label: 'Osmosis',
      link: {
        type: 'doc',
        id: 'testnet/osmosis',
      },
      collapsible: true,
      items: [{ type: 'autogenerated', dirName: 'testnet/osmosis' }],
      className: 'sidebar-section-with-icon icon-osmosis',
    },
    {
      type: 'category',
      label: 'Pell',
      link: {
        type: 'doc',
        id: 'testnet/pell',
      },
      collapsible: true,
      items: [{ type: 'autogenerated', dirName: 'testnet/pell' }],
      className: 'sidebar-section-with-icon icon-pell',
    },
    {
      type: 'category',
      label: 'Quicksilver',
      link: {
        type: 'doc',
        id: 'testnet/quicksilver',
      },
      collapsible: true,
      items: [{ type: 'autogenerated', dirName: 'testnet/quicksilver' }],
      className: 'sidebar-section-with-icon icon-quicksilver',
    },
    {
      type: 'category',
      label: 'Seda',
      link: {
        type: 'doc',
        id: 'testnet/seda',
      },
      collapsible: true,
      items: [{ type: 'autogenerated', dirName: 'testnet/seda' }],
      className: 'sidebar-section-with-icon icon-seda',
    },
    {
      type: 'category',
      label: 'Side',
      link: {
        type: 'doc',
        id: 'testnet/side',
      },
      collapsible: true,
      items: [{ type: 'autogenerated', dirName: 'testnet/side' }],
      className: 'sidebar-section-with-icon icon-side',
    },
    {
      type: 'category',
      label: 'Story',
      link: {
        type: 'doc',
        id: 'testnet/story',
      },
      collapsible: true,
      items: [{ type: 'autogenerated', dirName: 'testnet/story' }],
      className: 'sidebar-section-with-icon icon-story',
    },
    {
      type: 'category',
      label: 'Sunrise',
      link: {
        type: 'doc',
        id: 'testnet/sunrise',
      },
      collapsible: true,
      items: [{ type: 'autogenerated', dirName: 'testnet/sunrise' }],
      className: 'sidebar-section-with-icon icon-sunrise',
    },
    {
      type: 'category',
      label: 'XRP',
      link: {
        type: 'doc',
        id: 'testnet/xrp',
      },
      collapsible: true,
      items: [{ type: 'autogenerated', dirName: 'testnet/xrp' }],
      className: 'sidebar-section-with-icon icon-xrp',
    },
    {
      type: 'category',
      label: 'Union',
      link: {
        type: 'doc',
        id: 'testnet/union',
      },
      collapsible: true,
      items: [{ type: 'autogenerated', dirName: 'testnet/union' }],
      className: 'sidebar-section-with-icon icon-union',
    },
    {
      type: 'category',
      label: 'Warden',
      link: {
        type: 'doc',
        id: 'testnet/warden',
      },
      collapsible: true,
      items: [{ type: 'autogenerated', dirName: 'testnet/warden' }],
      className: 'sidebar-section-with-icon icon-warden',
    },
    {
      type: 'category',
      label: 'ZeroGravity',
      link: {
        type: 'doc',
        id: 'testnet/og',
      },
      collapsible: true,
      items: [{ type: 'autogenerated', dirName: 'testnet/og' }],
      className: 'sidebar-section-with-icon icon-og',
    },
    {
      type: 'category',
      label: 'Zenrock',
      link: {
        type: 'doc',
        id: 'testnet/zenrock',
      },
      collapsible: true,
      items: [{ type: 'autogenerated', dirName: 'testnet/zenrock' }],
      className: 'sidebar-section-with-icon icon-zenrock',
    },
    {
      type: 'category',
      label: 'Zetachain',
      link: {
        type: 'doc',
        id: 'testnet/zetachain',
      },
      collapsible: true,
      items: [{ type: 'autogenerated', dirName: 'testnet/zetachain' }],
      className: 'sidebar-section-with-icon icon-zetachain',
    },
  ],
};
