name: Deploy to Remote Host

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths-ignore:
      - 'docs/**'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Connect to the remote host and execute deployment script
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVICE_HOST }}
          port: ${{ secrets.SERVICE_PORT }}
          username: ${{ secrets.SERVICE_USERNAME }}
          key: ${{ secrets.SERVICE_SSH_KEY }}
          script: |
            cd $HOME/service/config
            ./update_and_deploy-repo-sync.sh
