name: Deploy to Remote Host

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'src/**'
      - 'static/**'
      - 'sidebars/**'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Connect to the remote host and execute deployment script
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.MONITOR_HOST }}
          port: ${{ secrets.MONITOR_PORT }}
          username: ${{ secrets.MONITOR_USERNAME }}
          key: ${{ secrets.MONITOR_SSH_KEY }}
          script: |
            cd $HOME/service/config
            ./update_and_deploy.sh
